const doodadApi = require("lib.扩展函数.KK扩展API.00．装饰物函数");
const eventApi = require("lib.扩展函数.KK扩展API.02．事件注册函数");
const utilApi = require("lib.扩展函数.KK扩展API.03．工具函数");
export const DzDoodadCreate = doodadApi.DzDoodadCreate;
export const DzDoodadGetTypeId = doodadApi.DzDoodadGetTypeId;
export const DzDoodadSetModel = doodadApi.DzDoodadSetModel;
export const DzDoodadSetTeamColor = doodadApi.DzDoodadSetTeamColor;
export const DzDoodadSetColor = doodadApi.DzDoodadSetColor;
export const DzDoodadGetX = doodadApi.DzDoodadGetX;
export const DzDoodadGetY = doodadApi.DzDoodadGetY;
export const DzDoodadGetZ = doodadApi.DzDoodadGetZ;
export const DzDoodadSetPosition = doodadApi.DzDoodadSetPosition;
export const DzDoodadSetOrientMatrixRotate = doodadApi.DzDoodadSetOrientMatrixRotate;
export const DzDoodadSetOrientMatrixScale = doodadApi.DzDoodadSetOrientMatrixScale;
export const DzDoodadSetOrientMatrixResize = doodadApi.DzDoodadSetOrientMatrixResize;
export const DzDoodadSetVisible = doodadApi.DzDoodadSetVisible;
export const DzDoodadSetAnimation = doodadApi.DzDoodadSetAnimation;
export const DzDoodadSetTimeScale = doodadApi.DzDoodadSetTimeScale;
export const DzDoodadGetTimeScale = doodadApi.DzDoodadGetTimeScale;
export const DzDoodadGetCurrentAnimationIndex = doodadApi.DzDoodadGetCurrentAnimationIndex;
export const DzDoodadGetAnimationCount = doodadApi.DzDoodadGetAnimationCount;
export const DzDoodadGetAnimationName = doodadApi.DzDoodadGetAnimationName;
export const DzDoodadGetAnimationTime = doodadApi.DzDoodadGetAnimationTime;
export const DzTriggerRegisterMouseEventTrg = eventApi.DzTriggerRegisterMouseEventTrg;
export const DzTriggerRegisterKeyEventTrg = eventApi.DzTriggerRegisterKeyEventTrg;
export const DzTriggerRegisterMouseMoveEventTrg = eventApi.DzTriggerRegisterMouseMoveEventTrg;
export const DzTriggerRegisterMouseWheelEventTrg = eventApi.DzTriggerRegisterMouseWheelEventTrg;
export const DzTriggerRegisterWindowResizeEventTrg = eventApi.DzTriggerRegisterWindowResizeEventTrg;
export const DzF2I = eventApi.DzF2I;
export const DzI2F = eventApi.DzI2F;
export const DzK2I = eventApi.DzK2I;
export const DzI2K = eventApi.DzI2K;
export const DzTriggerRegisterMallItemSyncData = eventApi.DzTriggerRegisterMallItemSyncData;
export const DzGetTriggerMallItemPlayer = eventApi.DzGetTriggerMallItemPlayer;
export const DzGetTriggerMallItem = eventApi.DzGetTriggerMallItem;
export const DzSyncData = eventApi.DzSyncData;
export const DzSyncDataImmediately = eventApi.DzSyncDataImmediately;
export const DzSyncBuffer = eventApi.DzSyncBuffer;
export const DzTriggerRegisterDialogEntrySyncData = eventApi.DzTriggerRegisterDialogEntrySyncData;
export const DzSyncDialogEntryData = eventApi.DzSyncDialogEntryData;
export const DzGetTriggerDialogEntryPlayer = eventApi.DzGetTriggerDialogEntryPlayer;
export const DzGetTriggerDialogEntryData = eventApi.DzGetTriggerDialogEntryData;
export const DzTriggerRegisterSyncDataTrg = eventApi.DzTriggerRegisterSyncDataTrg;
export const DzGetTriggerSyncPlayer = eventApi.DzGetTriggerSyncPlayer;
export const DzGetTriggerSyncData = eventApi.DzGetTriggerSyncData;
export const DzGetColor2 = utilApi.DzGetColor2;
export const DzOpenQQGroupUrl = utilApi.DzOpenQQGroupUrl;
export const DzExecuteFunc = utilApi.DzExecuteFunc;
function expose(name, fn) {
    if (typeof fn !== "function")
        return;
    const g = globalThis;
    if (typeof g[name] === "function")
        return;
    g[name] = fn;
}
export function registerBridge() {
    expose("DzDoodadCreate", doodadApi.DzDoodadCreate);
    expose("DzDoodadGetTypeId", doodadApi.DzDoodadGetTypeId);
    expose("DzDoodadSetModel", doodadApi.DzDoodadSetModel);
    expose("DzDoodadSetTeamColor", doodadApi.DzDoodadSetTeamColor);
    expose("DzDoodadSetColor", doodadApi.DzDoodadSetColor);
    expose("DzDoodadGetX", doodadApi.DzDoodadGetX);
    expose("DzDoodadGetY", doodadApi.DzDoodadGetY);
    expose("DzDoodadGetZ", doodadApi.DzDoodadGetZ);
    expose("DzDoodadSetPosition", doodadApi.DzDoodadSetPosition);
    expose("DzDoodadSetOrientMatrixRotate", doodadApi.DzDoodadSetOrientMatrixRotate);
    expose("DzDoodadSetOrientMatrixScale", doodadApi.DzDoodadSetOrientMatrixScale);
    expose("DzDoodadSetOrientMatrixResize", doodadApi.DzDoodadSetOrientMatrixResize);
    expose("DzDoodadSetVisible", doodadApi.DzDoodadSetVisible);
    expose("DzDoodadSetAnimation", doodadApi.DzDoodadSetAnimation);
    expose("DzDoodadSetTimeScale", doodadApi.DzDoodadSetTimeScale);
    expose("DzDoodadGetTimeScale", doodadApi.DzDoodadGetTimeScale);
    expose("DzDoodadGetCurrentAnimationIndex", doodadApi.DzDoodadGetCurrentAnimationIndex);
    expose("DzDoodadGetAnimationCount", doodadApi.DzDoodadGetAnimationCount);
    expose("DzDoodadGetAnimationName", doodadApi.DzDoodadGetAnimationName);
    expose("DzDoodadGetAnimationTime", doodadApi.DzDoodadGetAnimationTime);
    expose("DzTriggerRegisterMouseEventTrg", eventApi.DzTriggerRegisterMouseEventTrg);
    expose("DzTriggerRegisterKeyEventTrg", eventApi.DzTriggerRegisterKeyEventTrg);
    expose("DzTriggerRegisterMouseMoveEventTrg", eventApi.DzTriggerRegisterMouseMoveEventTrg);
    expose("DzTriggerRegisterMouseWheelEventTrg", eventApi.DzTriggerRegisterMouseWheelEventTrg);
    expose("DzTriggerRegisterWindowResizeEventTrg", eventApi.DzTriggerRegisterWindowResizeEventTrg);
    expose("DzF2I", eventApi.DzF2I);
    expose("DzI2F", eventApi.DzI2F);
    expose("DzK2I", eventApi.DzK2I);
    expose("DzI2K", eventApi.DzI2K);
    expose("DzTriggerRegisterMallItemSyncData", eventApi.DzTriggerRegisterMallItemSyncData);
    expose("DzGetTriggerMallItemPlayer", eventApi.DzGetTriggerMallItemPlayer);
    expose("DzGetTriggerMallItem", eventApi.DzGetTriggerMallItem);
    expose("DzSyncData", eventApi.DzSyncData);
    expose("DzSyncDataImmediately", eventApi.DzSyncDataImmediately);
    expose("DzSyncBuffer", eventApi.DzSyncBuffer);
    expose("DzTriggerRegisterDialogEntrySyncData", eventApi.DzTriggerRegisterDialogEntrySyncData);
    expose("DzSyncDialogEntryData", eventApi.DzSyncDialogEntryData);
    expose("DzGetTriggerDialogEntryPlayer", eventApi.DzGetTriggerDialogEntryPlayer);
    expose("DzGetTriggerDialogEntryData", eventApi.DzGetTriggerDialogEntryData);
    expose("DzTriggerRegisterSyncDataTrg", eventApi.DzTriggerRegisterSyncDataTrg);
    expose("DzGetTriggerSyncPlayer", eventApi.DzGetTriggerSyncPlayer);
    expose("DzGetTriggerSyncData", eventApi.DzGetTriggerSyncData);
    expose("DzGetColor2", utilApi.DzGetColor2);
    expose("DzOpenQQGroupUrl", utilApi.DzOpenQQGroupUrl);
    expose("DzExecuteFunc", utilApi.DzExecuteFunc);
}
