/** @noSelfInFile */

export const 欧菲莉亚单位技能配置 = {
  英雄名: "欧菲莉亚",
  单位类型ID: "H013",
  Q技能ID: "A0J4",
  W技能ID: "A0J5",
  E技能ID: "A0J6",
  R技能ID: "A0J7",
  D技能ID: "A0J8",
  Q: {
    快捷键序号: 1,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0,
    全局音效键: "gg_snd_OFLY_Q",
    范围: 750,
    基础治疗攻击力倍率: 1,
    每级治疗攻击力倍率: 0.08,
    每级额外魔法恢复: 100,
    主体特效模型: "war3mapImported\\ancientexplode.mdl",
    主体特效Z: 100,
    主体特效缩放: 2,
    主体特效持续秒: 3,
    特效: [
      { 模型: "Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt.mdl", Z: 10, Z轴角度: 270, 缩放: 1 },
      { 模型: "Abilities\\Spells\\Items\\AIre\\AIreTarget.mdl", Z: 10, Z轴角度: 270, 缩放: 1.5 },
    ],
    特效持续秒: 1,
  },
  W: {
    快捷键序号: 2,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0,
    全局音效键: ["gg_snd_OFLY_W", "gg_snd_OFLY_W2"],
    基础攻击力倍率: 1.5,
    每级攻击力倍率: 0.1,
    光弱额外倍率: 1.5,
    溅射范围: 350,
    溅射倍率: 0.4,
    命中特效模型: "Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt.mdl",
    命中特效Z: 10,
    命中特效Z轴角度: 270,
    命中特效缩放: 2,
    命中特效持续秒: 1,
  },
  E: {
    快捷键序号: 3,
    每级魔法恢复: 1,
    每级智力: 8,
    首级治疗率: 0.1,
    每级治疗率: 0.04,
  },
  R: {
    快捷键序号: 4,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0,
    全局音效键: "gg_snd_OFLY_R",
    被动复活生命百分比: 50,
    被动冷却基础秒: 200,
    被动冷却每级减少秒: 5,
    主动生命基础百分比: 15,
    主动生命每级百分比: 2,
    主动魔法基础百分比: 2,
    主动魔法每级百分比: 1,
    复活特效模型: "Abilities\\Spells\\Human\\Resurrect\\ResurrectTarget.mdl",
    复活特效持续秒: 2,
    复活移动步数: 20,
    复活移动单步距离: 30,
    复活移动间隔毫秒: 10,
  },
  D: {
    快捷键序号: 5,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0,
    全局音效键: "gg_snd_OFLY_D",
    原生状态技能ID: "S00E",
    BuffID: "B020",
    魔抗增加: 0.5,
    持续秒: 3,
  },
} as const;

export {};
