/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";

export const 坂井悠二BuffID = {
  Q命中定身: "SYJ1",
  W眩晕: "SYJ2",
  E语法眩晕: "SYJ3",
  E抵挡: "SYJ4",
  R2减速: "SYJ5",
  D鼓舞: "SYJ6",
  D暗属性加成: "SYJ7",
  D期间状态: "SYJ8",
} as const;

export const 坂井悠二Buff表: Record<string, BuffData> = {
  [坂井悠二BuffID.Q命中定身]: {
    buffID: 坂井悠二BuffID.Q命中定身,
    buffName: "Q-命中定身",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_q_control.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: true,
    tooltip: "吸血鬼命中，几乎无法移动。",
  },
  [坂井悠二BuffID.W眩晕]: {
    buffID: 坂井悠二BuffID.W眩晕,
    buffName: "W-银之监牢",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_silver_prison.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: true,
    tooltip: "银之监牢束缚，无法行动。",
  },
  [坂井悠二BuffID.E语法眩晕]: {
    buffID: 坂井悠二BuffID.E语法眩晕,
    buffName: "E-语法眩晕",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_misty_shock.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: true,
    tooltip: "语法瞬移附带短暂眩晕。",
  },
  [坂井悠二BuffID.E抵挡]: {
    buffID: 坂井悠二BuffID.E抵挡,
    buffName: "E-语法抵挡",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_grammatica_guard.blp",
    effect: "",
    type: "Buff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 85,
    canPurge: false,
    data属性名: "伤害减免",
    tooltip: "语法自施法抵挡，单次受伤>=20%最大生命或致死时移除。",
  },
  [坂井悠二BuffID.R2减速]: {
    buffID: 坂井悠二BuffID.R2减速,
    buffName: "R2-胧天震减速",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_divine_gate.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 60,
    canPurge: true,
    data属性名: "移动速度",
    tooltip: "胧天震激震，移动速度降低30%。",
  },
  [坂井悠二BuffID.D鼓舞]: {
    buffID: 坂井悠二BuffID.D鼓舞,
    buffName: "D-祭礼之蛇鼓舞",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_ally_command.blp",
    effect: "",
    type: "Buff:magic:positive",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 75,
    canPurge: false,
    tooltip: "祭礼之蛇鼓舞：基础攻击力+100%，移动速度+20，持续10秒。",
  },
  [坂井悠二BuffID.D暗属性加成]: {
    buffID: 坂井悠二BuffID.D暗属性加成,
    buffName: "D-暗属性强化",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_snake_aura.blp",
    effect: "",
    type: "Buff:magic:positive",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: false,
    data属性名: "暗属性伤害加成",
    tooltip: "祭礼之蛇附身：暗属性伤害+30%，持续10秒。",
  },
  [坂井悠二BuffID.D期间状态]: {
    buffID: 坂井悠二BuffID.D期间状态,
    buffName: "D-祭礼之蛇状态",
    icon: "BuffIcon\\Hero\\SakaiYuuji\\sakai_snake_descent.blp",
    effect: "",
    type: "Buff:magic:positive",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: false,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "祭礼之蛇附身期间：移速最大化、E冷却固定为2.5秒、飞行高度+500。",
  },
};

export default 坂井悠二Buff表;
