/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";

/**
 * 铃仙 - 英雄 Buff 表
 * 图标：imports\BuffIcon\Hero\Reisen\（已生成 10 个）
 */
export const 铃仙BuffID = {
  /** Q 命中英雄：铃仙自身隐身 1 秒 */
  Q隐身: "RSN1",
  /** Q 命中目标：减速 20% 2 秒 */
  Q减速: "RSN2",
  /** Q 命中英雄：干扰附近反隐效果（1 秒） */
  Q反隐干扰: "RSN3",
  /** W 施放：周围没有『疯狂』的敌人 +1 秒对视时间 */
  W对视: "RSN4",
  /** W 分身状态：本体隐藏、5 分身期间 */
  W替身: "RSN5",
  /** E 跳跃空中闪避 0.3 秒 */
  E空中闪避: "RSN6",
  /** E 爆炸命中眩晕 1 秒 */
  E爆炸眩晕: "RSN7",
  /** R 翻滚/瞄准状态 */
  R翻滚: "RSN8",
  /** R2 裁决冲击命中眩晕 3 秒 */
  R眩晕: "RSN9",
  /** D 幻胧月睨持续波次状态 */
  D波次: "RSNA",
} as const;

export const 铃仙Buff表: Record<string, BuffData> = {
  [铃仙BuffID.Q隐身]: {
    buffID: 铃仙BuffID.Q隐身,
    buffName: "Q-幻觉隐身",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_q_stealth.blp",
    effect: "",
    type: "Buff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: false,
    tooltip: "命中英雄后短暂隐身，任何行为都不会解除。",
  },
  [铃仙BuffID.Q减速]: {
    buffID: 铃仙BuffID.Q减速,
    buffName: "Q-精神干扰减速",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_q_slow.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 60,
    canPurge: true,
    data属性名: "移动速度",
    tooltip: "精神波长干扰，移动速度降低 20%。",
  },
  [铃仙BuffID.Q反隐干扰]: {
    buffID: 铃仙BuffID.Q反隐干扰,
    buffName: "Q-反隐干扰",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_q_anti_stealth.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: true,
    tooltip: "命中英雄后干扰附近反隐效果，持续 1 秒。",
  },
  [铃仙BuffID.W对视]: {
    buffID: 铃仙BuffID.W对视,
    buffName: "W-疯狂对视",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_w_madness.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 60,
    canPurge: true,
    tooltip: "与铃仙对视，『疯狂』计时增加 1 秒。",
  },
  [铃仙BuffID.W替身]: {
    buffID: 铃仙BuffID.W替身,
    buffName: "W-赤眼替身",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_w_decoy.blp",
    effect: "",
    type: "Buff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 85,
    canPurge: false,
    tooltip: "本体隐藏，5 个分身期间可选择分身出现。",
  },
  [铃仙BuffID.E空中闪避]: {
    buffID: 铃仙BuffID.E空中闪避,
    buffName: "E-空中闪避",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_e_air_dodge.blp",
    effect: "",
    type: "Buff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 85,
    canPurge: false,
    tooltip: "跳跃空中 0.3 秒内躲避伤害。",
  },
  [铃仙BuffID.E爆炸眩晕]: {
    buffID: 铃仙BuffID.E爆炸眩晕,
    buffName: "E-近眼花火眩晕",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_e_stun.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: true,
    tooltip: "精神炸弹爆炸眩晕 1 秒。",
  },
  [铃仙BuffID.R翻滚]: {
    buffID: 铃仙BuffID.R翻滚,
    buffName: "R-翻滚瞄准",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_r_roll.blp",
    effect: "",
    type: "Buff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: false,
    tooltip: "翻滚后进入 2 秒瞄准窗口，可释放丧心疮痍二段。",
  },
  [铃仙BuffID.R眩晕]: {
    buffID: 铃仙BuffID.R眩晕,
    buffName: "R-丧心眩晕",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_r_stun.blp",
    effect: "",
    type: "Debuff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: true,
    tooltip: "丧心疮痍命中眩晕 3 秒。",
  },
  [铃仙BuffID.D波次]: {
    buffID: 铃仙BuffID.D波次,
    buffName: "D-幻胧月睨",
    icon: "BuffIcon\\Hero\\Reisen\\reisen_d_wave.blp",
    effect: "",
    type: "Buff:magic:skill",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: false,
    tooltip: "释放波长漩涡，5 秒内每秒发射 15 发弹幕。",
  },
};

export default 铃仙Buff表;
