/** @noSelfInFile */

export const 安兹乌尔恭单位技能配置 = {
  BossKey: 'AinzOoalGown',
  单位名称: '安兹·乌尔·恭',
  正式单位ID: 'U007',
  旧候选单位ID: 'E005',
  模型路径: 'Boss\\AinzOoalGown\\AinzOoalGown.mdx',
  普通攻击: {
    射程: 1200,
    弹道速度: 1400,
    弹道模型: 'Boss\\AinzOoalGown\\Projectile\\AinzMagicMissile.mdx',
  },
  技能壳: {
    现实断裂: 'AT08',
    心脏掌握: 'BT08',
    高阶魔法箭: 'CT08',
    光辉翠绿体: 'AN00',
  },
  主动技能提示: [
    { 技能ID: 'AT08', 提示: '现实断裂', 扩展提示: '预警宽240码、长1300码的固定矩形切面，1.2秒后沿路径移动0.35秒。（离开红色矩形预警区。）' },
    { 技能ID: 'BT08', 提示: '心脏掌握', 扩展提示: '点名1名玩家并开始12秒倒计时；至少1名队友需进入目标320码范围协助破解，否则处决。（被点名者停留原地等待队友靠近。）' },
    { 技能ID: 'CT08', 提示: '高阶魔法箭', 扩展提示: '施法0.9秒后连续3轮锁定落点，每轮间隔0.45秒，落点预警0.85秒且伤害半径230码。（持续移动，避开圆形落点。）' },
    { 技能ID: 'AN00', 提示: '光辉翠绿体', 扩展提示: '施法0.75秒后获得持续8秒的防护，抵挡1次达到目标最大生命0.5%的直接攻击；低于门槛的伤害不会消耗。（等待防护结束，或用一次有效重击破盾。）' },
  ] as Array<{ 技能ID: string; 提示: string; 扩展提示: string }>,
  护卫: {
    BossKey: 'AlbedoGuardian',
    单位名称: '雅儿贝德',
    正式单位ID: 'U008',
    模型路径: 'Boss\\AinzOoalGown\\Albedo.mdx',
  },
  阶段阈值: {
    P2生命比例: 0.7,
    P3生命比例: 0.35,
    P3预告生命比例: 0.4,
    至尊宣言生命比例: 0.15,
  },
  挑战模式: ['至尊的试炼', '守护者介入'] as const,
  广播持续时间Ms: 4200,
  配音裁断距离: 4000,
  开场台词时间: {
    战斗开始延迟Ms: 4800,
    守护者命令延迟Ms: 9000,
  },
  台词: {
    登场: ['很好，你们竟能来到这里。那么，就来接受我的试炼吧。（保持距离，等待战斗提示。）'],
    战斗开始: ['那么，开始吧。尽你们所能挣扎给我看。（留意技能预警和安全区。）'],
    进入P2: ['原来如此，看来值得让我稍微展示一些力量。（接下来会加入时间停止与大型技能，分散站位。）'],
    现实断裂: ['安兹展开宽240码、长1300码的空间切面，1.2秒后移动0.35秒。（离开红色矩形预警区。）'],
    心脏掌握: ['心脏掌握点名1名玩家并倒计时12秒；至少1名队友进入320码范围即可破解。（被点名者停留原地等待队友靠近。）'],
    高阶魔法箭: ['高阶魔法箭将在0.9秒后连续锁定3轮落点，每轮间隔0.45秒。（持续移动，避开半径230码的圆形预警。）'],
    光辉翠绿体: ['光辉翠绿体将在0.75秒后生效，持续8秒并抵挡1次达到目标最大生命0.5%的直接攻击。（等待防护结束，或用一次有效重击破盾。）'],
    时间停止启动: ['时间停止将在2.8秒预展示后冻结全场1.6秒，解冻后开始依次结算。（预展示期间离开预警并分散站位。）'],
    时间停止结算: ['时间恢复，随后依次结算法阵、现实断裂和魔法箭。（继续避开仍在场的结算区域。）'],
    高阶亡灵召唤: ['1.2秒后召唤1名死亡骑士；其存活时亡灵箭伤害提高35%，击败后12秒内降至基础值的75%；死亡骑士首次受到致命伤害时保留1点生命并免伤1秒，之后可正常击败。（护盾消失后再次集火。）'],
    天空坠落: ['天空坠落引导4.0~4.8秒后落地，随后每1秒产生1次余波，共2次；场上有3个半径210码墓碑阴影安全区。（进入墓碑背后的白色安全区。）', '天空坠落将在4.0~4.8秒引导后落地，并在随后1秒、2秒各产生1次余波。（进入墓碑背后的白色安全区。）'],
    一切生命的终点: ['一切生命的终点开始12秒倒计时，需激活3座生命锚，每座在230码内停留0.8秒。（分工踩点，优先处理被暗金屏障封锁的锚点。）', '一切生命的终点开始12秒倒计时；3座生命锚全部激活后获得14秒生命庇护，并在女妖哭嚎后开放8秒输出窗口。（分工踩点并及时破盾。）'],
    守护者命令: ['雅儿贝德将介入战斗并执行护卫技能。（注意她的冲锋直线与扇形预警。）'],
    进入P3: ['很出色。但你们无法逃离死亡之理。（保留位移技能，准备处理生命锚点。）'],
    至尊宣言: ['安兹·乌尔·恭绝无败北。（不要贪刀，先处理正在生效的机制。）'],
    挑战结束: ['试炼到此为止。雅儿贝德，收起武器。（停止攻击，等待传送门出现。）'],
  },
  配音资源: {
    登场: ['Sound\\Boss\\AinzOoalGown\\Voice\\01_intro_trial.mp3'],
    战斗开始: ['Sound\\Boss\\AinzOoalGown\\Voice\\02_battle_start.mp3'],
    进入P2: ['Sound\\Boss\\AinzOoalGown\\Voice\\03_phase_two_acknowledge.mp3'],
    现实断裂: ['Sound\\Boss\\AinzOoalGown\\Voice\\04_reality_fracture.mp3'],
    心脏掌握: ['Sound\\Boss\\AinzOoalGown\\Voice\\05_grasp_heart.mp3'],
    高阶魔法箭: ['Sound\\Boss\\AinzOoalGown\\Voice\\06_magic_arrow_volley.mp3'],
    光辉翠绿体: ['Sound\\Boss\\AinzOoalGown\\Voice\\07_green_guard.mp3'],
    时间停止启动: ['Sound\\Boss\\AinzOoalGown\\Voice\\08_time_stop.mp3'],
    时间停止结算: ['Sound\\Boss\\AinzOoalGown\\Voice\\09_time_resume.mp3'],
    高阶亡灵召唤: ['Sound\\Boss\\AinzOoalGown\\Voice\\10_undead_summon.mp3'],
    天空坠落: [
      'Sound\\Boss\\AinzOoalGown\\Voice\\11_fallen_down.mp3',
      'Sound\\Boss\\AinzOoalGown\\Voice\\ainz_fallen_down_super_tier_01.mp3',
    ],
    一切生命的终点: [
      'Sound\\Boss\\AinzOoalGown\\Voice\\12_goal_of_all_life.mp3',
      'Sound\\Boss\\AinzOoalGown\\Voice\\ainz_goal_of_all_life_is_death_01.mp3',
    ],
    守护者命令: ['Sound\\Boss\\AinzOoalGown\\Voice\\13_guardian_order.mp3'],
    进入P3: ['Sound\\Boss\\AinzOoalGown\\Voice\\14_final_phase.mp3'],
    至尊宣言: ['Sound\\Boss\\AinzOoalGown\\Voice\\15_no_defeat.mp3'],
    挑战结束: ['Sound\\Boss\\AinzOoalGown\\Voice\\16_trial_end.mp3'],
    至尊拦截: ['Sound\\Boss\\AinzOoalGown\\Voice\\17_albedo_guardian_intercept.mp3'],
    黑翼横扫: ['Sound\\Boss\\AinzOoalGown\\Voice\\18_albedo_black_wing_sweep.mp3'],
    守护者之职责: ['Sound\\Boss\\AinzOoalGown\\Voice\\19_albedo_guardian_duty.mp3'],
    至尊共护: ['Sound\\Boss\\AinzOoalGown\\Voice\\20_albedo_guardian_shared_protection.mp3'],
    黑翼拘束: ['Sound\\Boss\\AinzOoalGown\\Voice\\21_albedo_black_wing_bind.mp3'],
    生命锚点封锁: ['Sound\\Boss\\AinzOoalGown\\Voice\\22_albedo_life_anchor_lock.mp3'],
    守护回归: ['Sound\\Boss\\AinzOoalGown\\Voice\\23_albedo_guardian_return.mp3'],
    护卫反击: ['Sound\\Boss\\AinzOoalGown\\Voice\\24_albedo_guardian_counterattack.mp3'],
  },
  雅儿贝德台词: {
    至尊拦截: ['雅儿贝德发动至尊拦截，0.6秒预警后沿直线冲向安兹并在落点攻击。（离开红色冲锋线和落点。）'],
    黑翼横扫: ['雅儿贝德将在0.8秒后横扫前方100度、半径520码区域并击退目标。（离开扇形预警区。）'],
    守护者之职责: ['雅儿贝德建立1秒预连接，随后持续6秒与安兹分担50%的直接伤害；距离超过900码会断开。（远离另一名目标，或在连接建立前打断。）'],
    至尊共护: ['雅儿贝德为安兹与自身生成共同护盾：总量为雅儿贝德当前生命的60%，安兹获得70%、雅儿贝德获得30%，持续至引导结束后8秒。（优先击破护盾并趁其失衡输出。）'],
    黑翼拘束: ['雅儿贝德将在天空坠落引导开始0.8秒后拘束1名玩家，持续3.2~4.0秒；多人模式暂停，单人模式攻速与移速降低70%。（优先击破拘束核心。）'],
    生命锚点封锁: ['雅儿贝德封锁1座未激活生命锚点，并生成持续12秒的暗金屏障；击破屏障后才能激活。（集火暗金屏障，已激活锚点不会再次封锁。）'],
    守护回归: ['雅儿贝德将在0.65秒预警后用0.5秒冲回安兹身边，沿途命中并击退目标。（离开冲锋直线。）'],
    护卫反击: ['雅儿贝德进入2秒守势，正面承伤降至40%；单次达到自身最大生命4%的直接伤害会触发反击。（从背后攻击或等待守势结束。）'],
  },
  当前状态: {
    目录结构已建立: true,
    单位数据已确认: true,
    技能已实现: true,
    现实断裂已实现: true,
    心脏掌握已实现: true,
    高阶魔法箭已实现: true,
    光辉翠绿体已实现: true,
    天空坠落已实现: true,
    P2阶段调度已实现: true,
    时间停止已实现: true,
    高阶亡灵召唤已实现: true,
    一切生命的终点已实现: true,
    守护者模式已实现: true,
    基础运行时已实现: true,
    战斗启动上下文已注册: true,
  },
} as const;

export type 安兹台词类型 = keyof typeof 安兹乌尔恭单位技能配置.台词;
