// NPC配置数据 - 自动生成
// 生成时间: 2026-04-08 21:36:54

export interface NPCData {
  NpcName?: string;
  requireID?: number;
  NPCrequireName?: string;
  unitCode?: string;
  requireType?: string;
  X?: number;
  Y?: number;
  Facing?: number;
  modelFIle?: string;
  initaction?: string;
  enabled?: boolean;
}

export const NPC_CONFIGS: NPCData[] = [
  {
    NpcName: "人类农民",
    requireID: 1000,
    NPCrequireName: "人类农民",
    unitCode: "hpea",
    requireType: "任务",
    X: -336.2,
    Y: -92.3,
    Facing: 270,
    enabled: true,
  },
  {
    NpcName: "人类猎人",
    requireID: 1001,
    NPCrequireName: "人类猎人",
    unitCode: "hmil",
    requireType: "对话",
    X: -26819.3,
    Y: -8344.6,
    Facing: 220,
    enabled: false,
  },
  {
    NpcName: "精灵村信使",
    requireID: 1002,
    NPCrequireName: "精灵村信使",
    unitCode: "n01H",
    requireType: "对话",
    X: -27392.3,
    Y: -28285.2,
    Facing: 200,
    modelFIle: "units\\critters\\HighElfPeasant\\HighElfPeasant",
    enabled: false,
  },
  {
    NpcName: "精灵村民",
    requireID: 1003,
    NPCrequireName: "精灵村NPC001",
    unitCode: "nhef",
    requireType: "对话",
    X: -26657.5,
    Y: -28275.3,
    Facing: 165,
    modelFIle: "war3mapImported\\ElfVillagerWomanV2.02.mdl",
    enabled: false,
  },
  {
    NpcName: "沙漠神秘刺客",
    requireID: 1004,
    NPCrequireName: "沙漠神秘刺客",
    unitCode: "nass",
    requireType: "对话",
    X: -15871.9,
    Y: -20945.1,
    Facing: 270,
    modelFIle: "units\\creeps\\BanditSpearThrower\\BanditSpearThrower",
    initaction: "RemoveItemFromStockBJ:itemId(I0AG|I0AH|I0AI;random)",
    enabled: false,
  },
  {
    NpcName: "沙漠战斗商人",
    requireID: 1005,
    NPCrequireName: "沙漠战斗商人",
    unitCode: "n02I",
    requireType: "对话",
    X: -6926.7,
    Y: -22781,
    Facing: 62.82,
    modelFIle: "units\\creeps\\Bandit\\Bandit.mdl",
    enabled: false,
  },
  {
    NpcName: "精灵村弓箭手",
    requireID: 10001,
    NPCrequireName: "猎杀豺狼人",
    unitCode: "n01I",
    requireType: "任务",
    X: -25549.1,
    Y: -26008.7,
    Facing: 120,
    modelFIle: "units\\creeps\\HighElfArcher\\HighElfArcher",
    enabled: false,
  },
  {
    NpcName: "精灵村民3",
    requireID: 10002,
    NPCrequireName: "采集荧光草",
    unitCode: "n01J",
    requireType: "任务",
    X: -23827.3,
    Y: -27726.2,
    Facing: 220,
    modelFIle: "war3mapImported\\ElfVillagerWomanV2.02.mdl",
    enabled: false,
  },
  {
    NpcName: "黑暗巫师",
    requireID: 10003,
    NPCrequireName: "收集蜘蛛毒液",
    unitCode: "n01N",
    requireType: "任务",
    X: -18313.7,
    Y: -25518.5,
    Facing: 0,
    modelFIle: "units\\creeps\\BanditMage\\BanditMage",
    enabled: false,
  },
  {
    NpcName: "亡灵法师-安格斯",
    requireID: 10004,
    NPCrequireName: "收集熔岩能量",
    unitCode: "n040",
    requireType: "任务",
    modelFIle: "units\\undead\\Necromancer\\Necromancer.mdl",
    enabled: false,
  },
  {
    NpcName: "精灵村民1",
    requireID: 10005,
    NPCrequireName: "收集豺狼皮",
    unitCode: "nhef",
    requireType: "任务",
    X: -26609,
    Y: -26978,
    Facing: 138,
    modelFIle: "war3mapImported\\ElfVillagerWomanV2.02.mdl",
    enabled: false,
  },
  {
    NpcName: "布里强",
    requireID: 10006,
    NPCrequireName: "收集20个蝎肉",
    unitCode: "nban",
    requireType: "任务",
    X: -5460.2,
    Y: -24955.4,
    Facing: 90,
    modelFIle: "units\\creeps\\Bandit\\Bandit",
    enabled: false,
  },
  {
    NpcName: "树魔",
    requireID: 10007,
    NPCrequireName: "收集7个蝎壳",
    unitCode: "nftt",
    requireType: "任务",
    X: -8105.6,
    Y: -21191.5,
    Facing: 270,
    modelFIle: "war3mapImported\\ForestTrollShadowPriest.mdl",
    enabled: false,
  },
  {
    NpcName: "精灵猎手",
    requireID: 10008,
    NPCrequireName: "收集有毒杂草",
    unitCode: "e08B",
    requireType: "任务",
    X: -23856.2,
    Y: -29293.1,
    Facing: 270,
    modelFIle: "war3mapImported\\Watcher.mdl",
    enabled: false,
  },
  {
    NpcName: "精灵村民2",
    requireID: 10009,
    NPCrequireName: "寻找聚灵花",
    unitCode: "nhef",
    requireType: "任务",
    X: -23161.8,
    Y: -26556.9,
    Facing: 45,
    modelFIle: "war3mapImported\\ElfVillagerWomanV2.02.mdl",
    enabled: false,
  },
  {
    NpcName: "熔岩术士",
    requireID: 10010,
    NPCrequireName: "送信",
    unitCode: "nsra",
    requireType: "任务",
    X: 6903.8,
    Y: -25005.3,
    Facing: 10,
    modelFIle: "units\\creeps\\OrcWarlock\\OrcWarlock",
    enabled: false,
  },
  {
    NpcName: "守望者",
    requireID: 10011,
    NPCrequireName: "希望获得品质较好的道具或饰品",
    unitCode: "n036",
    requireType: "任务",
    X: 8864.6,
    Y: -22209.2,
    Facing: 255.96,
    modelFIle: "units\\creeps\\assassin\\assassin",
    enabled: false,
  },
  {
    NpcName: "精灵弓箭手",
    requireID: 10012,
    NPCrequireName: "有提高视力的道具吗",
    unitCode: "e06Q",
    requireType: "任务",
    X: -27950.6,
    Y: -26851.8,
    Facing: 45,
    modelFIle: "war3mapImported\\maleelfarcher.mdl",
    enabled: false,
  },
  {
    NpcName: "冒险者阿利亚",
    requireID: 10013,
    NPCrequireName: "消失的笛子",
    unitCode: "n058",
    requireType: "任务",
    X: -27974.4,
    Y: -7209.5,
    Facing: 270,
    modelFIle: "units\\critters\\VillagerMan\\VillagerMan",
    enabled: false,
  },
  {
    NpcName: "德鲁伊学者-卢伊",
    requireID: 10014,
    NPCrequireName: "暗狱之书",
    unitCode: "n059",
    requireType: "任务",
    X: 29335.3,
    Y: -27943.2,
    Facing: 270,
    modelFIle: "war3mapImported\\Hero Druid.mdl",
    enabled: false,
  },
  {
    NpcName: "下级异端审查官-卢修斯",
    requireID: 10015,
    NPCrequireName: "|cffff9900协助异端调查|r（|cffff00008级精英战斗任务|r）",
    unitCode: "h010",
    requireType: "任务",
    X: -22800.6,
    Y: -29084.3,
    Facing: 90,
    modelFIle: "units\\human\\BloodElfSpellThief\\BloodElfSpellThief",
    enabled: false,
  },
  {
    NpcName: "德鲁伊指引者-阿莫斯",
    requireID: 10016,
    NPCrequireName: "净化狂暴之熊",
    unitCode: "n04M",
    requireType: "任务",
    X: -22620.5,
    Y: -14275.9,
    Facing: 235,
    modelFIle: "war3mapImported\\DruidGuide.mdl",
    enabled: false,
  },
  {
    NpcName: "德鲁伊看守者-阿尔文",
    requireID: 10017,
    NPCrequireName: "给予圣果",
    unitCode: "n04O",
    requireType: "任务",
    modelFIle: "war3mapImported\\Annurion.mdl",
    enabled: false,
  },
  {
    NpcName: "知识古树",
    requireID: 10018,
    NPCrequireName: "补充生命力",
    unitCode: "e06N",
    requireType: "任务",
    X: -18950.5,
    Y: -14412.4,
    Facing: 270,
    modelFIle: "war3mapImported\\druidtreeform.mdl",
    enabled: false,
  },
  {
    NpcName: "精灵族长-斯韦尔",
    requireID: 10019,
    NPCrequireName: "|cffff0000失踪的精灵村民（Boss战任务）|r",
    unitCode: "edot",
    requireType: "任务",
    modelFIle: "units\\nightelf\\DruidoftheTalon\\DruidoftheTalon",
    enabled: false,
  },
];

export default NPC_CONFIGS;
