/** @noSelfInFile */

export const 利尔伯特技能配置 = {
  正义审判: {
    面向扇区角度: 90,
    附加已损生命比例: 0.2,
    周期秒: 5,
    周期Boss攻击力比例: 1,
    命中特效: {
      路径: 'Abilities\\Spells\\Orc\\LightningShield\\LightningShieldBuff.mdl',
      Z: 0,
      朝向: 270,
      缩放: 1.5,
      动画速度: 1,
      持续秒: 1,
    },
  },
  裂地斩: {
    通魔施法秒: 0.5,
    预警秒: 1.1,
    施法硬直秒: 1.1,
    读条通道: '常规技能',
    读条颜色ID: 1,
    动作编号: 14,
    搜索半径: 1750,
    作用半径: 275,
    Boss攻击力比例: 2,
    眩晕秒: 1,
    起始特效: { 路径: 'Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl', Z: 0, 朝向: 270, 缩放: 2.5, 动画速度: 1, 持续秒: 1 },
    预警特效: { 路径: 'war3mapImported\\mr.war3_ring.mdl', Z: 0, 朝向: 270, 缩放: 1.2, 动画速度: 1, 持续秒: 0.1 },
    命中特效: { 路径: 'Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl', Z: 0, 朝向: 270, 缩放: 2.5, 动画速度: 1, 持续秒: 1 },
    爆炸特效: { 路径: 'war3mapImported\\explosion.mdl', Z: 0, 朝向: 270, 缩放: 1, 动画速度: 1, 持续秒: 1 },
    读条标题: '裂地斩',
    读条提示: '目标脚下即将发生裂地冲击',
  },
  审判拷问: {
    通魔施法秒: 0.7,
    施法硬直秒: 0.7,
    读条通道: '常规技能',
    读条颜色ID: 1,
    动作编号: 11,
    持续秒: 5,
    原位置安全半径: 233,
    基础最大生命比例: 0.3,
    每难度N最大生命比例: 0.1,
    眩晕秒: 1,
    起始特效: { 路径: 'war3mapImported\\mr.war3_ring2.mdl', Z: 0, 朝向: 270, 缩放: 1, 动画速度: 1, 持续秒: 0.5 },
    命中特效: { 路径: 'war3mapImported\\Judgement_impact_chest_red.mdl', Z: 0, 朝向: 270, 缩放: 2, 动画速度: 1, 持续秒: 1 },
    命中音效全局变量名: 'gg_snd_LightningShieldTarget',
    读条标题: '审判拷问',
    读条提示: '站稳并面向利尔·伯特',
  },
  检查: {
    通魔施法秒: 0.7,
    施法硬直秒: 0.7,
    读条通道: '常规技能',
    读条颜色ID: 1,
    动作编号: 11,
    检查持续秒: 3,
    失败惩罚延迟秒: 2,
    基础伤害阈值: 560,
    每难度N降低阈值: 60,
    目标最大生命比例: 0.2,
    Boss攻击力比例: 2.5,
    失败惩罚命中特效: {
      路径: 'Common\\Effect\\Form\\Explosion\\SpiritGuardGateSlamCrimson.mdx',
      Z: 0,
      朝向: 270,
      缩放: 3,
      动画速度: 1,
      持续秒: 1.2,
    },
    读条标题: '检查',
    读条提示: '利尔·伯特正在检查装备',
  },
} as const;
