-- Second Legion special caster.

createSecondLegionUnit('n062', 'edot', {
  name = '第二军团术士',
  description = '负责侵蚀王城防御阵法的第二军团特殊施法者。',
  modelFile = 'Unit\\Special\\SecondLegionWarlock.mdx',
  icon = 'Unit\\Special\\Icon\\SecondLegionWarlock.blp',
  scale = 1.25,
  hp = 7000,
  hpRegen = 56.0,
  mana = 1000,
  manaRegen = 10.0,
  defense = 35,
  speed = 320,
  collision = 24.0,
  acquire = 850.0,
  pointValue = 200,
  bounty = 750,
  damage = 900,
  attackCooldown = 2.00,
  attackRange = 700,
  rangeBuffer = 250.0,
  attackTargets = 'ground,air,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Magic,
  weaponType = WeaponType.Missile,
  weaponSound = WeaponSound.Nothing,
  projectileArt = 'Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl',
  projectileSpeed = 900,
  projectileArc = 0.15,
  projectileHoming = true,
  projectileLaunchZ = 90.0,
  projectileImpactZ = 60.0,
  attackBackswing = 0.60,
  attackDamagePoint = 0.50,
})
