// 任务配置数据 - 自动生成
// 生成时间: 2026-05-27 02:51:50

export interface QuestData {
  requireID?: number;
  name?: string;
  type?: string;
  startNpc?: string;
  endNpc?: string;
  endNpcLocation?: string;
  requireQuest?: number;
  questItems?: string;
  requireItem?: string;
  requiredResources?: string;
  targetUnit?: string;
  requireCount?: number;
  requirements?: string;
  targetRegion?: string;
  reward?: string;
  rewardDisplay?: string;
  rewardItem?: string;
  desc?: string;
  progressText?: string;
  failText?: string;
  NpcStartText?: string;
  QuestAcceptedMsg?: string;
  AcceptFailedText?: string;
  NpcCompleteText?: string;
  afterCompleteDialog ?: string;
  repeatable?: boolean;
  enabled?: boolean;
}

export const QUEST_CONFIGS: QuestData[] = [
  {
    requireID: 10001,
    name: "猎杀豺狼人",
    type: "击杀",
    startNpc: "精灵弓箭手",
    targetUnit: "n004|ngna|ngns|ngno|ngnb|ngnv",
    requireCount: 10,
    reward: "所有玩家+200金币;1能量碎片",
    desc: "前往精灵森击杀10只豺狼人",
    progressText: "击杀豺狼人N/10",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10002,
    name: "采集荧光草",
    type: "收集",
    startNpc: "精灵村民",
    requireItem: "shwd",
    requireCount: 3,
    reward: "所有玩家+400经验;1能量碎片",
    desc: "前往史莱姆草原采集3颗荧光草",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10003,
    name: "收集蜘蛛毒液",
    type: "收集",
    startNpc: "黑暗巫师",
    requireItem: "I03L",
    requireCount: 10,
    reward: "所有玩家+1200金币;1等级",
    desc: "收集10份蜘蛛毒液",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10004,
    name: "收集熔岩能量",
    type: "收集",
    startNpc: "亡灵法师-安格斯",
    requireItem: "I05V",
    requireCount: 3,
    reward: "所有玩家+5000金币;1等级",
    desc: "收集3分熔岩能量",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 1000,
    name: "收集豺狼皮2",
    type: "收集",
    startNpc: "人类农民",
    requireItem: "I01O",
    requireCount: 5,
    reward: "所有玩家+700经验;400金币",
    desc: "收集5张豺狼皮",
    NpcStartText: "NPC：你好冒险家，我目前急需一些豺狼皮。\nNPC：你愿意帮助我吗?我会给你报酬。",
    QuestAcceptedMsg: "Player：好的，有时间我会帮助你\nNPC：多谢帮忙..我会在此地等候的",
    NpcCompleteText: "NPC：这是说好的报酬多谢\n没想到你真的完成了",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10005,
    name: "收集豺狼皮",
    type: "收集",
    startNpc: "精灵村民",
    requireItem: "I01O",
    requireCount: 5,
    reward: "所有玩家+700经验;400金币",
    desc: "收集5张豺狼皮",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10006,
    name: "收集20个蝎肉",
    type: "限时收集",
    startNpc: "布里强",
    requireItem: "I0AB",
    requireCount: 20,
    reward: "完成任务的玩家+8000金币;5智力",
    desc: "收集20个蝎肉",
    failText: "|cffffff00『系统提示』：|r时间已到，此任务失败+NPC:哎...看来只能和兄弟们吃这一点烤肉了",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10007,
    name: "收集7个蝎壳",
    type: "收集",
    startNpc: "树魔",
    requireItem: "I03Y",
    requireCount: 7,
    reward: "所有玩家+5000经验;3000金币",
    desc: "收集20个蝎壳",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10008,
    name: "收集有毒杂草",
    type: "收集",
    startNpc: "精灵猎手",
    requireItem: "I0CS",
    requireCount: 5,
    reward: "所有玩家+2500金币;金属性抗性:2%",
    desc: "收集5个有毒杂草",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10009,
    name: "寻找聚灵花",
    type: "收集",
    startNpc: "精灵村民",
    requireItem: "I0A0",
    requireCount: 1,
    reward: "所有玩家+IMaxBJ(20000-(等级-20)*1000, 10000)",
    failText: "完成了|Cffff00ff『寻找聚灵花』|r任务，所有玩家|Cffffcc99英雄经验+20000（根据等级会有所减少)|r，|Cffffff00金币+10000|r",
    NpcCompleteText: "NPC：哇，居然真的是聚灵花，太好了，这下事情有着落了。",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10010,
    name: "送信",
    type: "送货",
    startNpc: "熔岩术士",
    endNpcLocation: "createUnit(n03W,12765.50,-19360.30,270.00)",
    questItems: "I0AO",
    requireItem: "I0AO",
    requireCount: 1,
    reward: "所有玩家+10000经验",
    desc: "将信件送往恶魔城的某人",
    NpcCompleteText: "Player：请问这封信你认识吗？\nNPC：....没错，一眼就认出来了，这确实是我朋友的信，多谢。\nNPC：这是信封上写的报酬，我就替我朋友交付了。\nPlayer：好的。",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10011,
    name: "希望获得品质较好的道具或饰品",
    type: "给予",
    startNpc: "守望者",
    requireItem: "装备等级:D+,C-,C,C+",
    reward: "外部：\n给予它品质较好的道具或饰品，NPC会给予报酬\n内部：\ntype=道具/戒指/饰品的装备\n装备等级<D+:null\n装备等级>D+&<C:所有玩家+3000金币;1能量碎片\n装备等级=C+:所有玩家+6000金币;2能量碎片\nI067|I08G:所有玩家+3能量碎片",
    NpcStartText: "NPC：可以给我一件较好的道具或者饰品吗？不过希望能是我喜欢的，我会给你不错的报酬",
    NpcCompleteText: "这个也太一搬了...还给你，我不需要\n多谢，这是说好的报酬\n此物相当不错，非常好，这是说的好的报酬，另外多送你些\n这就是我想要的，真是太好了！",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10012,
    name: "有提高视力的道具吗",
    type: "给予",
    startNpc: "精灵弓箭手",
    requireItem: "I083|I08B",
    reward: "英雄等级＞30:所有玩家+10000经验\n英雄等级≤30:所有玩家+1等级",
    NpcStartText: "NPC：你好我是精灵村的守望者，但是我近几十年来视力越来越不如以前，如果有能提高视力的道具就好了",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10013,
    name: "消失的笛子",
    type: "给予",
    startNpc: "冒险者阿利亚",
    requireItem: "afac",
    reward: "完成任务的玩家+18000金币;1能量碎片;12攻击力",
    NpcStartText: "NPC：奇怪..我的|cffff6600笛子|r去哪里了..好像是经过|cffff6600飓风沙漠|r后就发现找不到了..",
    QuestAcceptedMsg: "NPC：多谢帮忙..我会在此地等候的",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10014,
    name: "暗狱之书",
    type: "给予",
    startNpc: "德鲁伊学者-卢伊",
    requireItem: "I0CQ",
    requireCount: 1,
    reward: "完成任务的玩家+25000金币;1能量碎片;2%魔法伤害",
    NpcStartText: "NPC：这本|cffffcc99『精灵族远古历史』|r写到上古时期精灵族曾经有族人异端化，但是更为详细资料没有了,如果有更详细的资料就好了",
    QuestAcceptedMsg: "NPC：多谢帮忙..我会在此地等候的",
    NpcCompleteText: "NPC：居然真的被你找到了暗狱之书，这是说好的报酬！多谢！\nNPC：....原来是这样，但上面的一些内容还是有些模糊，好像是和帝国相关..",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10015,
    name: "|cffff9900协助异端调查|r（|cffff00008级精英战斗任务|r）",
    type: "击杀",
    startNpc: "下级异端审查官-卢修斯",
    questItems: "I0CN",
    requirements: "英雄等级＜10",
    NpcStartText: "NPC：被上级派来此地调查精灵森异端的审查官，但调查几天了却没有丝毫进展，最后凭借直觉告诉他可能是|cffff9900豺狼人|r有问题",
    QuestAcceptedMsg: "NPC：敬请期待了",
    AcceptFailedText: "NPC：我已经调查完成了，多谢你的好意",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10016,
    name: "净化狂霸之熊",
    type: "收集",
    startNpc: "德鲁伊指引者-阿莫斯",
    requireItem: "I0BD",
    requireCount: 20,
    reward: "所有玩家+10000金币;(英雄等级)*800经验",
    rewardItem: "I0BH",
    NpcStartText: "NPC：一些同族受到不明原因变得更加原始化了，带上|cffccffff『德鲁伊灯笼（净化）』|r帮我们净化一些同族吧",
    QuestAcceptedMsg: "NPC：老朽先提前谢过了",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10017,
    name: "给予圣果",
    type: "给予",
    startNpc: "德鲁伊看守者-阿尔文",
    requireItem: "I09M",
    requireCount: 1,
    reward: "所有玩家+2能量碎片;1等级",
    NpcStartText: "NPC：咳咳..老朽年事已高，如果有传说中的|cffff9900伊达灵果|r就太好了…年轻人，你愿意帮我吗?",
    QuestAcceptedMsg: "NPC：年轻人，这是给你的报酬！",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10018,
    name: "补充生命力",
    type: "给予",
    startNpc: "知识古树",
    requiredResources: "能量碎片",
    requireCount: 6,
    reward: "完成任务的玩家+(英雄等级*0.6)智力;1智力成长",
    NpcStartText: "Player：这颗知识古树似乎没有多少寿命了....可以尝试帮助它补充生命力",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
  {
    requireID: 10019,
    name: "|cffff0000失踪的精灵村民（Boss战任务）|r",
    type: "目标击杀",
    startNpc: "精灵族长-斯韦尔",
    reward: "英雄等级≤17:所有玩家+10000金币;暴击伤害+1%;暴击率+1%\n英雄等级＞17:所有玩家+5000金币;暴击伤害+1%",
    desc: "调查精灵人员为何失踪\n|cffffff00『系统提示』：|r|cffff0000此任务难度特别高，推荐等级：17|r",
    NpcStartText: "NPC：最近精灵村陆续失踪一些人员，根据我们目前的线索，|cffffff00初始之森（玩家出生地）|r可能有点踪迹，你愿意帮助我们吗？",
    QuestAcceptedMsg: "NPC：感谢你们，有你们的帮助这件事我想一定会有眉目。\nPlayer：长老，可以介绍下具体情况吗\nNPC：嗯..就是精灵村最近1个月开始陆陆续续有村民失踪\nNPC：根据哨手来报，精灵村的空气中混杂着一丝血液，很明显，这件事是人为，不是自然发生的。\nPlayer：居然是血案..\nNPC：来着恐怕不凡，估计是针对我们精灵族而来，目前的踪迹全部指向精灵初始森\nNPC：去哪里调查一下吧，我想会有线索的..\nPlayer：好的，精灵族也是我的朋友..这件事我会当做自己的事情处理..",
    afterCompleteDialog : "默认",
    repeatable: false,
    enabled: true,
  },
];

export default QUEST_CONFIGS;
