/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 巴尔扎罗斯BuffID = {
  灼热: "BBZ1",
  熔核封印: "BBZ2",
  火焰锁链: "BBZ3",
  熔岩护盾: "BBZ4",
  炙热奉献: "BBZ5",
  塞拉火焰形态: "BBZ6",
  塞拉冰霜形态: "BBZ7",
  熔岩暴走: "BBZ8",
  绝对零度领域: "BBZ9",
} as const;

export type 巴尔扎罗斯BuffID类型 = typeof 巴尔扎罗斯BuffID[keyof typeof 巴尔扎罗斯BuffID];

export const 巴尔扎罗斯Buff表: Record<string, BuffData> = {
  [巴尔扎罗斯BuffID.灼热]: {
    buffID: 巴尔扎罗斯BuffID.灼热,
    buffName: "灼热",
    icon: "BuffIcon\\Boss\\Balzaroth\\scorching_heat.blp",
    effect: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeEmbers.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:fire:stack",
    interval: 1,
    maxStack: 12,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 86,
    canPurge: false,
    tooltip: "每次获得后持续30秒并刷新计时，最多12层。来源包括：熔岩重锤命中+2层；熔岩火径线上每0.25秒+1层、穿越火径+1层；冰焰双星火球命中+2层；王者天罚连续命中3波+2层；熔岩喷发爆发与残留各+1层；地核每3秒对全场+1层。当前版本每层只记录灼热层数，不直接造成额外周期伤害；绝对零度领域生成时清除3层、领域内每1秒清除2层，冷却水晶清除全部层数。",
  },
  [巴尔扎罗斯BuffID.熔核封印]: {
    buffID: 巴尔扎罗斯BuffID.熔核封印,
    buffName: "熔核封印",
    icon: "BuffIcon\\Boss\\Balzaroth\\molten_core_seal.blp",
    effect: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:seal",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 95,
    canPurge: false,
    tooltip: "战斗开始登记，持续至格鲁姆与塞拉全部死亡；巴尔扎罗斯无法移动，受到的最终伤害降低80%（只承受20%）。双护卫全部死亡后解除。",
  },
  [巴尔扎罗斯BuffID.火焰锁链]: {
    buffID: 巴尔扎罗斯BuffID.火焰锁链,
    buffName: "火焰锁链",
    icon: "BuffIcon\\Boss\\Balzaroth\\flame_chain.blp",
    effect: "Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl",
    effectMode: "attach",
    effectAttachPoint: "chest",
    type: "Debuff:dot:fire:chain",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 92,
    canPurge: false,
    tooltip: "持续8秒；优先点名距Boss至少600码的最远目标，不足600码时随机点名。目标脚下显示半径180码锁定提示；场中生成可攻击锁链单位（最大生命=Boss最大生命值×7%）。Boss与目标距离超过650码时每1秒造成Boss当前攻击力×80%+目标最大生命值×2%伤害；锁链单位死亡或Buff被清除时立即结束。",
  },
  [巴尔扎罗斯BuffID.熔岩护盾]: {
    buffID: 巴尔扎罗斯BuffID.熔岩护盾,
    buffName: "熔岩护盾",
    icon: "BuffIcon\\Boss\\Balzaroth\\lava_shield.blp",
    effect: "Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:shield",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 88,
    canPurge: false,
    tooltip: "Boss生命低于85%、55%、25%时各触发1次，持续10秒；护盾值=Boss最大生命值×7%。近战攻击者每1秒最多触发1次反弹，受到攻击者最大生命值×2%+Boss攻击力×20%伤害；冰霜/水属性伤害使护盾消耗提高50%，冰霜伤害击破护盾时移除1层熔岩暴走。",
  },
  [巴尔扎罗斯BuffID.炙热奉献]: {
    buffID: 巴尔扎罗斯BuffID.炙热奉献,
    buffName: "炙热奉献",
    icon: "BuffIcon\\Boss\\Balzaroth\\scorching_devotion.blp",
    effect: "Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:channel",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "格鲁姆生命低于20%时触发8秒献祭引导；引导期间击杀或打断格鲁姆可阻止完成。引导成功后格鲁姆死亡，巴尔扎罗斯恢复最大生命值12%，并获得持续15秒的熔岩暴走。",
  },
  [巴尔扎罗斯BuffID.塞拉火焰形态]: {
    buffID: 巴尔扎罗斯BuffID.塞拉火焰形态,
    buffName: "塞拉·火焰形态",
    icon: "BuffIcon\\Boss\\Balzaroth\\sera_fire_stance.blp",
    effect: "Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:stance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "持续22秒（元素转换周期20秒+2秒补偿）。塞拉的火焰技能伤害提高25%；受到克制属性伤害提高20%。",
  },
  [巴尔扎罗斯BuffID.塞拉冰霜形态]: {
    buffID: 巴尔扎罗斯BuffID.塞拉冰霜形态,
    buffName: "塞拉·冰霜形态",
    icon: "BuffIcon\\Boss\\Balzaroth\\sera_frost_stance.blp",
    effect: "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:stance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "持续22秒（元素转换周期20秒+2秒补偿）。塞拉的冰霜技能伤害提高25%；受到克制属性伤害提高20%。",
  },
  [巴尔扎罗斯BuffID.熔岩暴走]: {
    buffID: 巴尔扎罗斯BuffID.熔岩暴走,
    buffName: "熔岩暴走",
    icon: "BuffIcon\\Boss\\Balzaroth\\lava_rampage.blp",
    effect: "Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:rage",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 94,
    canPurge: false,
    tooltip: "P3进入时获得1层，持续3600秒；每次用冰霜伤害击破熔岩护盾时移除1层。当前运行时仅作为P3状态标记与熔岩护盾联动，不额外提高攻击力、技能伤害或场地压力百分比。",
  },
  [巴尔扎罗斯BuffID.绝对零度领域]: {
    buffID: 巴尔扎罗斯BuffID.绝对零度领域,
    buffName: "绝对零度领域",
    icon: "BuffIcon\\Boss\\Balzaroth\\absolute_zero_domain.blp",
    effect: "",
    type: "Debuff:field:frost:damage-down",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 87,
    canPurge: false,
    data属性名: "造成伤害降低",
    tooltip: "领域半径320码，持续10秒；生成时立即清除3层灼热，领域内每1秒清除2层。领域内造成的伤害降低15%，离开领域后该减伤继续3秒。",
  },
};

export default 巴尔扎罗斯Buff表;
