/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 菲尼克斯尔BuffID = {
  凤凰火印: "BPH1",
  冷焰印记: "BPH2",
  毒火蚀痕: "BPH3",
  怨火烙印: "BPH4",
  导管破封: "BPH5",
  怨火链接: "BPH6",
  永恒轮回: "BPH7",
} as const;

export type 菲尼克斯尔BuffID类型 = typeof 菲尼克斯尔BuffID[keyof typeof 菲尼克斯尔BuffID];

export const 菲尼克斯尔Buff表: Record<string, BuffData> = {
  [菲尼克斯尔BuffID.凤凰火印]: {
    buffID: 菲尼克斯尔BuffID.凤凰火印,
    buffName: "凤凰火印",
    icon: "BuffIcon\\Boss\\Phoenixel\\phoenix_fire_mark.blp",
    effect: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeEmbers.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:fire:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "最多6层；每次获得或刷新持续30秒。炽羽散射落点、燃烧区、熔岩吐息和凤凰漩涡会增加1层。元素爆发读取最高层时，凤凰火印成为最高层则按当前攻击力×120%+目标最大生命值×5%结算，结算后该最高层减少2层。",
  },
  [菲尼克斯尔BuffID.冷焰印记]: {
    buffID: 菲尼克斯尔BuffID.冷焰印记,
    buffName: "冷焰印记",
    icon: "BuffIcon\\Boss\\Phoenixel\\coldflame_mark.blp",
    effect: "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:ice:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "最多6层；每次获得或刷新持续30秒。元素爆发读取最高层时，冷焰印记成为最高层则按当前攻击力×80%+目标最大生命值×3%结算，结算后该最高层减少2层。",
  },
  [菲尼克斯尔BuffID.毒火蚀痕]: {
    buffID: 菲尼克斯尔BuffID.毒火蚀痕,
    buffName: "毒火蚀痕",
    icon: "BuffIcon\\Boss\\Phoenixel\\venomfire_corrosion.blp",
    effect: "Abilities\\Spells\\NightElf\\shadowstrike\\shadowstrike.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:poison:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "最多6层；每次获得或刷新持续30秒。元素爆发读取最高层时，毒火蚀痕成为最高层则按目标已损失生命值×20%结算，结算后该最高层减少2层。",
  },
  [菲尼克斯尔BuffID.怨火烙印]: {
    buffID: 菲尼克斯尔BuffID.怨火烙印,
    buffName: "怨火烙印",
    icon: "BuffIcon\\Boss\\Phoenixel\\vengeful_flame_brand.blp",
    effect: "Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "chest",
    type: "Debuff:dot:dark:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "最多6层；每次获得或刷新持续30秒。骸骨弹幕、怨火链接和凤凰挽歌圈外命中会增加1层。元素爆发读取最高层时，怨火烙印成为最高层则按当前攻击力×150%+目标最大生命值×4%结算，结算后该最高层减少2层。",
  },
  [菲尼克斯尔BuffID.导管破封]: {
    buffID: 菲尼克斯尔BuffID.导管破封,
    buffName: "导管破封",
    icon: "BuffIcon\\Boss\\Phoenixel\\conduit_breach.blp",
    effect: "",
    type: "Buff:boss:phase",
    interval: 0,
    maxStack: 4,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "持续3600秒。每摧毁1根能量导管获得1层，最多4层；每层使菲尼克斯尔受到的最终伤害提高8%、技能强度提高6%。1/2/3/4层分别为承伤+8%/+16%/+24%/+32%，技能强度+6%/+12%/+18%/+24%。",
  },
  [菲尼克斯尔BuffID.怨火链接]: {
    buffID: 菲尼克斯尔BuffID.怨火链接,
    buffName: "怨火链接",
    icon: "BuffIcon\\Boss\\Phoenixel\\vengeful_flame_link.blp",
    effect: "Abilities\\Spells\\Orc\\SpiritLink\\SpiritLinkTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "chest",
    type: "Debuff:boss:chain",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 92,
    canPurge: false,
    tooltip: "链接持续8秒，连线宽90码。两端距离超过850码时断链，双方各承受目标已损失生命值×18%+当前攻击力×120%，并各获得1层怨火烙印；其他单位进入连线宽度内时，每0.5秒承受当前攻击力×40%+目标最大生命值×1.5%，并获得1层怨火烙印。",
  },
  [菲尼克斯尔BuffID.永恒轮回]: {
    buffID: 菲尼克斯尔BuffID.永恒轮回,
    buffName: "永恒轮回",
    icon: "BuffIcon\\Boss\\Phoenixel\\eternal_rebirth.blp",
    effect: "Abilities\\Spells\\Orc\\Reincarnation\\ReincarnationTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:channel",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 96,
    canPurge: false,
    tooltip: "菲尼克斯尔生命值≤5%时触发，持续15秒并生成4枚凤凰之卵；每枚凤凰蛋最大生命值为Boss最大生命值的8%。15秒后若仍有蛋存活，每枚恢复Boss最大生命值12%，并对全场每名玩家结算目标最大生命值20%+Boss当前攻击力×150%；4枚全部摧毁则Boss死亡。",
  },
};

export default 菲尼克斯尔Buff表;
