/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 菲尼克斯尔BuffID = {
  凤凰火印: "BPH1",
  冷焰印记: "BPH2",
  毒火蚀痕: "BPH3",
  怨火烙印: "BPH4",
  导管破封: "BPH5",
  怨火链接: "BPH6",
  永恒轮回: "BPH7",
} as const;

export type 菲尼克斯尔BuffID类型 = typeof 菲尼克斯尔BuffID[keyof typeof 菲尼克斯尔BuffID];

export const 菲尼克斯尔Buff表: Record<string, BuffData> = {
  [菲尼克斯尔BuffID.凤凰火印]: {
    buffID: 菲尼克斯尔BuffID.凤凰火印,
    buffName: "凤凰火印",
    icon: "BuffIcon\\Boss\\Phoenixel\\phoenix_fire_mark.blp",
    effect: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeEmbers.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:fire:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "凤凰火焰留下的元素烙印。元素爆发会读取最高层元素，火印最高时触发火焰惩罚；脱离对应危险区后逐步衰减。",
  },
  [菲尼克斯尔BuffID.冷焰印记]: {
    buffID: 菲尼克斯尔BuffID.冷焰印记,
    buffName: "冷焰印记",
    icon: "BuffIcon\\Boss\\Phoenixel\\coldflame_mark.blp",
    effect: "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:ice:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "冷焰侵入体内形成的元素烙印。元素爆发会读取最高层元素，冷焰最高时触发冷焰伤害和短暂硬直；脱离对应危险区后逐步衰减。",
  },
  [菲尼克斯尔BuffID.毒火蚀痕]: {
    buffID: 菲尼克斯尔BuffID.毒火蚀痕,
    buffName: "毒火蚀痕",
    icon: "BuffIcon\\Boss\\Phoenixel\\venomfire_corrosion.blp",
    effect: "Abilities\\Spells\\NightElf\\shadowstrike\\shadowstrike.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:poison:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "毒火腐蚀留下的元素烙印。元素爆发会读取最高层元素，毒火最高时触发已损失生命伤害并降低治疗效果；脱离对应危险区后逐步衰减。",
  },
  [菲尼克斯尔BuffID.怨火烙印]: {
    buffID: 菲尼克斯尔BuffID.怨火烙印,
    buffName: "怨火烙印",
    icon: "BuffIcon\\Boss\\Phoenixel\\vengeful_flame_brand.blp",
    effect: "Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "chest",
    type: "Debuff:dot:dark:stack",
    interval: 0,
    maxStack: 6,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    tooltip: "怨火与骸骨烈焰留下的元素烙印。元素爆发会读取最高层元素，怨火最高时触发暗火伤害并提高下一次大招威胁；脱离对应危险区后逐步衰减。",
  },
  [菲尼克斯尔BuffID.导管破封]: {
    buffID: 菲尼克斯尔BuffID.导管破封,
    buffName: "导管破封",
    icon: "BuffIcon\\Boss\\Phoenixel\\conduit_breach.blp",
    effect: "",
    type: "Buff:boss:phase",
    interval: 0,
    maxStack: 4,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "能量导管被摧毁后，菲尼克斯尔受到的伤害提高，同时技能强度提高。每摧毁1根导管叠加1层，最多4层。",
  },
  [菲尼克斯尔BuffID.怨火链接]: {
    buffID: 菲尼克斯尔BuffID.怨火链接,
    buffName: "怨火链接",
    icon: "BuffIcon\\Boss\\Phoenixel\\vengeful_flame_link.blp",
    effect: "Abilities\\Spells\\Orc\\SpiritLink\\SpiritLinkTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "chest",
    type: "Debuff:boss:chain",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 92,
    canPurge: false,
    tooltip: "被怨火链接锁定。链接穿过单位会造成暗火伤害并叠加怨火烙印；主动拉断链接会触发爆炸惩罚。",
  },
  [菲尼克斯尔BuffID.永恒轮回]: {
    buffID: 菲尼克斯尔BuffID.永恒轮回,
    buffName: "永恒轮回",
    icon: "BuffIcon\\Boss\\Phoenixel\\eternal_rebirth.blp",
    effect: "Abilities\\Spells\\Orc\\Reincarnation\\ReincarnationTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:channel",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 96,
    canPurge: false,
    tooltip: "菲尼克斯尔进入永恒轮回，引导重生并召唤凤凰之卵。摧毁全部凤凰之卵可打断轮回，否则按存活凤凰蛋数量恢复生命并造成全场惩罚。",
  },
};

export default 菲尼克斯尔Buff表;
