/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 菲利斯BuffID = {
  领袖光环: "BFE1",
  剑魂狼印: "BFE2",
  侵蚀残留: "BFE3",
  封印标记: "BFE4",
  异形化: "BFE5",
  魔力汲取: "BFE6",
} as const;

export type 菲利斯BuffID类型 = typeof 菲利斯BuffID[keyof typeof 菲利斯BuffID];

export const 菲利斯Buff表: Record<string, BuffData> = {
  [菲利斯BuffID.领袖光环]: {
    buffID: 菲利斯BuffID.领袖光环,
    buffName: "领袖光环",
    icon: "BuffIcon\\Boss\\Felice\\leader_aura.blp",
    effect: "",
    type: "Aura:boss",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 72,
    canPurge: false,
    tooltip: "菲利斯统御军团。生命值50%以上时提高其他友方攻击力；50%以下时削弱其他友方攻击力，并加快剑气灵斩循环。",
  },
  [菲利斯BuffID.剑魂狼印]: {
    buffID: 菲利斯BuffID.剑魂狼印,
    buffName: "剑魂狼印",
    icon: "BuffIcon\\Boss\\Felice\\sword_soul_wolf_mark.blp",
    effect: "",
    type: "Debuff:mark",
    interval: 0,
    maxStack: 2,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 64,
    canPurge: true,
    tooltip: "被剑魂杀路径命中，短时间记录命中层数；命中数量用于判断剑魂狼是否合并为大狼。",
  },
  [菲利斯BuffID.侵蚀残留]: {
    buffID: 菲利斯BuffID.侵蚀残留,
    buffName: "侵蚀残留",
    icon: "BuffIcon\\Boss\\Felice\\erosion_residue.blp",
    effect: "",
    type: "Debuff:dot:magic",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 68,
    canPurge: true,
    tooltip: "站在剑气灵斩侵蚀路径内或刚离开路径，持续受到风属性魔法伤害并损失魔法值。",
  },
  [菲利斯BuffID.封印标记]: {
    buffID: 菲利斯BuffID.封印标记,
    buffName: "封印标记",
    icon: "BuffIcon\\Boss\\Felice\\seal_mark.blp",
    effect: "Common\\Effect\\Form\\MagicCircle\\Mage aura.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:magic",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 78,
    canPurge: true,
    tooltip: "全力封印斩锁定QWER全部冷却的玩家。结算时扣除魔法、造成暗魔法伤害、眩晕，并使菲利斯瞬移到目标身边。",
  },
  [菲利斯BuffID.异形化]: {
    buffID: 菲利斯BuffID.异形化,
    buffName: "异形化",
    icon: "BuffIcon\\Boss\\Felice\\aberration.blp",
    effect: "Common\\Effect\\Form\\Aura\\devil aura.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:burst",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 92,
    canPurge: true,
    tooltip: "菲利斯异形化5秒，造成和受到的伤害提高50%，刷新剑气灵斩，并持续牵引附近玩家；受到光属性伤害会缩短持续时间。",
  },
  [菲利斯BuffID.魔力汲取]: {
    buffID: 菲利斯BuffID.魔力汲取,
    buffName: "魔力汲取",
    icon: "BuffIcon\\Boss\\Felice\\mana_drain.blp",
    effect: "",
    type: "Buff:boss:resource",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: false,
    tooltip: "菲利斯造成伤害会积累魔法值。魔法达到10000时允许启用异形化；该状态可用于测试资源循环。",
  },
};

export default 菲利斯Buff表;
