/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 里科特BuffID = {
  精灵之风: "BRC1",
  神明祝福: "BRC2",
  神风印记: "BRC3",
  神风护体: "BRC4",
  湮灭锁定: "BRC5",
  破魔反击: "BRC6",
} as const;

export type 里科特BuffID类型 = typeof 里科特BuffID[keyof typeof 里科特BuffID];

export const 里科特Buff表: Record<string, BuffData> = {
  [里科特BuffID.精灵之风]: {
    buffID: 里科特BuffID.精灵之风,
    buffName: "精灵之风",
    icon: "BuffIcon\\Boss\\Ricote\\spirit_wind.blp",
    effect: "Abilities\\Spells\\Human\\DispelMagic\\DispelMagicTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:passive",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: false,
    tooltip: "每1秒清除里科特身上的减速、残废、诅咒等软控制；该Buff每次刷新持续2秒。",
  },
  [里科特BuffID.神明祝福]: {
    buffID: 里科特BuffID.神明祝福,
    buffName: "神明祝福",
    icon: "BuffIcon\\Boss\\Ricote\\divine_blessing.blp",
    effect: "Common\\Effect\\Form\\Aura\\GaiaOrbs6.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:passive",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 86,
    canPurge: false,
    tooltip: "每秒恢复最大生命值的1%；单次受到的伤害最多按最大生命值的19%结算；该Buff每次刷新持续2秒。",
  },
  [里科特BuffID.神风印记]: {
    buffID: 里科特BuffID.神风印记,
    buffName: "神风印记",
    icon: "BuffIcon\\Boss\\Ricote\\kamikaze_mark.blp",
    effect: "Common\\Effect\\Form\\MagicCircle\\ShiningSquareAura_noTC.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:magic:stack",
    interval: 0,
    maxStack: 20,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 78,
    canPurge: true,
    tooltip: "持续4.5秒；攻击神风护体期间的里科特会使攻击者获得1层。粉碎时清除全部层数，每层按目标最大生命值的20%结算伤害，并眩晕0.4+0.2×层数秒；Buff显示最多20层。",
  },
  [里科特BuffID.神风护体]: {
    buffID: 里科特BuffID.神风护体,
    buffName: "神风护体",
    icon: "BuffIcon\\Boss\\Ricote\\wind_guard.blp",
    effect: "Common\\Effect\\Form\\Shield\\BlessingOfAzeroth.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:shield",
    interval: 0,
    maxStack: 12,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "持续4秒，初始7层。每次受到攻击消耗1层，使本次伤害降低50%，并让攻击者获得1层神风印记；持续时间结束后按印记层数结算粉碎。",
  },
  [里科特BuffID.湮灭锁定]: {
    buffID: 里科特BuffID.湮灭锁定,
    buffName: "湮灭锁定",
    icon: "BuffIcon\\Boss\\Ricote\\annihilation_lock.blp",
    effect: "",
    type: "Debuff:mark",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "湮灭之炮锁定你：P1延迟3秒、P2/P3延迟2秒，随后持续3秒，每0.1秒沿1200码直线炮击。该Buff实际持续P1为6秒、P2/P3为5秒；P3每个投影另有0~2秒随机落点预警，预警1秒后结算半径250码眩晕1秒。",
  },
  [里科特BuffID.破魔反击]: {
    buffID: 里科特BuffID.破魔反击,
    buffName: "破魔反击",
    icon: "BuffIcon\\Boss\\Ricote\\counter_reflect.blp",
    effect: "Common\\Effect\\Form\\Shield\\CounterShieldImpact.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:counter",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 94,
    canPurge: false,
    tooltip: "预备1~5秒后进入2秒反击窗口。窗口内受击时：攻击者距里科特≤300码，移除其当前生命70%；超过300码，移除99%；随后眩晕0.8秒，触发后窗口立即结束。",
  },
};

export default 里科特Buff表;
