/** @noSelfInFile */

import type { BuffData } from "../01．Buff表";

// 控制类 Buff：眩晕、沉默、缴械、禁锢、恐惧等控制语义优先放这里。
export const 控制Buff表: Record<string, BuffData> = {
  // C001-C020 为快速 Buff / 纯 TS 控制效果的自定义 UI 行；原生魔法效果和附着特效由魔兽技能自身管理，不在 Buff 表里配置周期特效。
    "C001": {
      buffID: "C001",
      buffName: "击晕",
      icon: "ReplaceableTextures\\CommandButtons\\BTNStormBolt.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
        tooltip: "受到了『击晕』，被重击得头晕目眩，在time秒内无法行动。"
      },
  "C002": {
      buffID: "C002",
      buffName: "冰冻",
      icon: "ReplaceableTextures\\CommandButtons\\BTNFreezingBreath.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『冰冻』，身体被彻底冻结，在time秒内无法行动。"
    },
  "C003": {
      buffID: "C003",
      buffName: "沉默",
      icon: "ReplaceableTextures\\CommandButtons\\BTNSilence.blp",
      effect: "",
      type: "Debuff:control:strong",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 8,
      canPurge: true,
      tooltip: "受到了『沉默』，力量被封住，在time秒内无法施放技能。"
    },
  "C004": {
      buffID: "C004",
      buffName: "变形",
      icon: "ReplaceableTextures\\CommandButtons\\BTNPolymorph.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『变形』，暂时失去原本的姿态，在time秒内无法行动。"
    },
  "C006": {
      buffID: "C006",
      buffName: "缴械",
      icon: "ReplaceableTextures\\CommandButtons\\BTNRegenerate.blp",
      effect: "",
      type: "Debuff:control:strong",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 8,
      canPurge: true,
      tooltip: "受到了『缴械』，武器难以施展，在time秒内无法攻击。"
    },
  "C007": {
      buffID: "C007",
      buffName: "减速",
      icon: "ReplaceableTextures\\CommandButtons\\BTNSlow.blp",
      effect: "",
      type: "Debuff:control:soft:slow",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 1,
      priority: 6,
      canPurge: true,
      tooltip: "受到了『减速』，动作变得迟缓，在time秒内移动与行动都会变慢。"
    },
  "C008": {
      buffID: "C008",
      buffName: "硬直",
      icon: "ReplaceableTextures\\CommandButtons\\BTNStun.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『硬直』，身体一时僵住，在time秒内无法行动。"
    },
  "C009": {
      buffID: "C009",
      buffName: "暂停",
      icon: "BuffIcon\Pause.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『暂停』，整个人像被定住一样，在time秒内无法行动。"
    },
  "C010": {
      buffID: "C010",
      buffName: "EX暂停",
      icon: "BuffIcon\EXPause.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: false,
      tooltip: "受到了『EX暂停』，被更强的力量彻底定住，在time秒内无法行动，而且无法被普通净化驱散。"
    },
  "C037": {
      buffID: "C037",
      buffName: "施法硬直",
      icon: "ReplaceableTextures\\CommandButtons\\BTNReplay-Pause.blp",
      effect: "",
      type: "Debuff:control:cast",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 0,
      priority: 10,
      canPurge: false,
      tooltip: "正在施法硬直中，time秒内暂时无法行动。"
    },
  "C016": {
      buffID: "C016",
      buffName: "睡眠",
      icon: "ReplaceableTextures\\CommandButtons\\BTNSleep.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『睡眠』，沉沉睡去，在time秒内无法行动。"
    },
  "C017": {
      buffID: "C017",
      buffName: "纠缠根须",
      icon: "ReplaceableTextures\\CommandButtons\\BTNEntanglingRoots.blp",
      effect: "",
      type: "Debuff:control:strong",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 9,
      canPurge: true,
      禁止位移: true,
      tooltip: "受到了『纠缠根须』，被藤蔓牢牢缠住，在time秒内无法移动。"
    },
  "C018": {
      buffID: "C018",
      buffName: "飓风",
      icon: "ReplaceableTextures\\CommandButtons\\BTNCyclone.blp",
      effect: "",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『飓风』，被狂风卷上半空，在time秒内无法行动。"
    },
  "C020": {
      buffID: "C020",
      buffName: "嘲讽",
      icon: "ReplaceableTextures\\CommandButtons\\BTNTaunt.blp",
      effect: "",
      type: "Debuff:control:strong",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 8,
      canPurge: true,
      tooltip: "受到了『嘲讽』，怒火被彻底挑起，在time秒内会被迫攻击来源单位。"
    },
  "C022": {
      buffID: "C022",
      buffName: "魅惑",
      icon: "ReplaceableTextures\\CommandButtons\\BTNCharm.blp",
      effect: "Abilities\\Spells\\Other\\SoulBurn\\SoulBurnbuff.mdl",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『魅惑』，心神被迷惑，在time秒内会失去控制并跟随来源单位。"
    },
  "C023": {
      buffID: "C023",
      buffName: "恐惧",
      icon: "ReplaceableTextures\\CommandButtons\\BTNHowlOfTerror.blp",
      effect: "BuffIcon\\model\\Grin Curse.mdx",
      type: "Debuff:control:full",
      interval: 0,
      maxStack: 1,
      stackRule: 'highest',
      stackRefresh: true,
      dispelLevel: 2,
      priority: 10,
      canPurge: true,
      tooltip: "受到了『恐惧』，内心被惊骇吞没，在time秒内会失去控制并四散逃跑。"
    },
};

export default 控制Buff表;
