import type { 剧情片段配置, 剧情步骤 } from "../00．剧情步骤类型";

const 沙漠入口调查步骤: 剧情步骤[] = [
  {
    type: "runAction",
    id: "desert_arrival_progress",
    名称: "抵达沙漠外缘",
    动作ID: "JLC沙漠_抵达沙漠外缘",
    参数: {
      触发进度: 5,
      触发区域: "gg_rct______________098",
      目标进度: 6,
      旧JASS功能清单: "IssueImmediateOrder / QuestSetDescription / QuestMessageBJ / CreateFogModifierRectBJ",
    },
  },
  {
    type: "dialog",
    id: "desert_player_arrival",
    名称: "玩家抵达沙漠",
    说话者: "玩家",
    文本: "前面就是沙漠了。这里的风向很乱，魔力源石的气息也被沙尘搅散了。",
    持续时间: 3,
  },
  {
    type: "runAction",
    id: "desert_arrival_quest",
    名称: "沙漠调查目标刷新",
    动作ID: "JLC沙漠_调查目标刷新",
    参数: {
      任务描述: "在沙漠中寻找熟悉地形的人，打听『魔力源石』的下落。",
      任务更新提示: "|cffffff00『主线目标』：|r在沙漠中寻找情报。",
    },
  },
];

const 沙漠居民线索步骤: 剧情步骤[] = [
  {
    type: "runAction",
    id: "desert_young_mercenary",
    名称: "询问沙漠年轻佣兵",
    动作ID: "JLC沙漠_年轻佣兵对话前置",
    参数: {
      触发进度: 6,
      NPC: "主线NPC.沙漠年轻佣兵",
      触发范围: 450,
      旧JASS功能清单: "SetUnitOwner(Player(6)) / IssueImmediateOrder / QuestMessageBJ",
    },
  },
  {
    type: "dialog",
    id: "desert_player_ask_mercenary",
    名称: "玩家询问佣兵",
    说话者: "玩家",
    文本: "我们在找一块带有强烈魔力反应的源石。你常年在沙漠行走，可曾听过类似的东西？",
    持续时间: 3,
  },
  {
    type: "dialog",
    id: "desert_mercenary_hint",
    名称: "佣兵提供方向",
    说话者: "沙漠年轻佣兵",
    文本: "源石？我只知道最近西边常有蛇人出没，连商队都绕着走。真要找线索，去问老一辈的人吧。",
    持续时间: 4,
  },
  {
    type: "runAction",
    id: "desert_elder_hint",
    名称: "询问沙漠年长者",
    动作ID: "JLC沙漠_年长者对话前置",
    参数: {
      触发进度: 6,
      NPC: "主线NPC.沙漠年长者",
      触发范围: 450,
      小地图X: -7139.3,
      小地图Y: -26096.7,
      旧JASS功能清单: "SetUnitOwner(Player(6)) / PingMinimap / CreateFogModifierRectBJ",
    },
  },
  {
    type: "dialog",
    id: "desert_player_ask_elder",
    名称: "玩家询问年长者",
    说话者: "玩家",
    文本: "老人家，我们想打听『魔力源石』。它可能和近期的异动有关。",
    持续时间: 3,
  },
  {
    type: "dialog",
    id: "desert_elder_snake_hint",
    名称: "年长者指向蛇人族",
    说话者: "沙漠年长者",
    文本: "若是旧沙海的宝物，多半绕不开『蛇人族』。他们的藏品管家见多识广，只是不会轻易开口。",
    持续时间: 5,
  },
];

const 情报商人与蛇人入口步骤: 剧情步骤[] = [
  {
    type: "runAction",
    id: "desert_intelligence_merchant",
    名称: "沙漠情报商人主线推进",
    动作ID: "JLC沙漠_情报商人对话前置",
    参数: {
      触发进度: 6,
      目标进度: 7,
      NPC: "主线NPC.沙漠情报商人",
      触发范围: 450,
      破坏物: "gg_dest_Dofw_15095",
      小地图X: 1455.7,
      小地图Y: -21980,
      旧JASS功能清单: "TransmissionFromUnitWithNameBJ / QuestSetDescription / QuestMessageBJ / RemoveDestructable",
    },
  },
  {
    type: "dialog",
    id: "desert_merchant_01",
    名称: "情报商人开价",
    说话者: "沙漠情报商人",
    文本: "想找『魔力源石』？这可不是普通情报。蛇人族的旧账、沙海里的禁忌，哪一样都不便宜。",
    持续时间: 5,
  },
  {
    type: "dialog",
    id: "desert_player_merchant_01",
    名称: "玩家追问",
    说话者: "玩家",
    文本: "我们没时间绕弯。告诉我们入口在哪里，价钱可以谈。",
    持续时间: 3,
  },
  {
    type: "dialog",
    id: "desert_merchant_02",
    名称: "商人指出蛇人领地",
    说话者: "沙漠情报商人",
    文本: "往西北走，越过风蚀岩柱，你们会看见蛇人族的边界。记住，别把他们当成普通盗匪。",
    持续时间: 6,
  },
  {
    type: "runAction",
    id: "snake_territory_entry",
    名称: "进入蛇人族领地",
    动作ID: "SRZ蛇人族_领地入口",
    参数: {
      触发进度: 7,
      目标进度: 8,
      触发区域: "gg_rct______________106",
      扣除金币: 233,
      解锁视野: "gg_rct______________108, gg_rct______________107",
      小地图X: -20880.7,
      小地图Y: 3186.4,
      旧JASS功能清单: "RemoveRect / PauseUnit / AdjustPlayerStateBJ / QuestMessageBJ",
    },
  },
  {
    type: "dialog",
    id: "snake_gate_guard_01",
    名称: "蛇人族边界警告",
    说话者: "蛇人守卫",
    文本: "外来者止步。这里是『蛇人族』的领地，再往前一步，便视作挑衅。",
    持续时间: 3,
  },
  {
    type: "dialog",
    id: "snake_gate_player_01",
    名称: "玩家说明目的",
    说话者: "玩家",
    文本: "我们只为寻找『魔力源石』而来，并不想和蛇人族为敌。",
    持续时间: 3,
  },
  {
    type: "dialog",
    id: "snake_gate_guard_02",
    名称: "守卫放行",
    说话者: "蛇人守卫",
    文本: "既然如此，就去见藏品管家吧。你们若敢乱闯，沙漠会替我们埋葬你们。",
    持续时间: 4,
  },
  {
    type: "runAction",
    id: "snake_keeper_first_meet",
    名称: "蛇人族藏品管家初见",
    动作ID: "SRZ蛇人族_藏品管家初见",
    参数: {
      触发进度: 8,
      目标进度: 9,
      NPC: "主线NPC.蛇人族藏品管家",
      触发范围: 400,
      商店新增物品: "I0D0",
      延迟提示: "|cffffff00『系统提示』：|r下次任务会开启|cffff0000『Boss战』|r，|cffffcc99实力不够则会团灭|r，请准备充分再来！",
      旧JASS功能清单: "AddItemToStockBJ / TimerStart(2秒提示) / QuestMessageBJ",
    },
  },
  {
    type: "dialog",
    id: "snake_keeper_01",
    名称: "管家试探",
    说话者: "蛇人族藏品管家",
    文本: "人类，精灵，佣兵……你们身上的气味很杂。说吧，想从蛇人族这里换走什么？",
    持续时间: 4,
  },
  {
    type: "dialog",
    id: "snake_keeper_task",
    名称: "管家提出交换",
    说话者: "蛇人族藏品管家",
    文本: "『魔力源石』的线索可以给你们，但先替我们处理沙漠深处那头失控的食人魔。拿回它身上的凭证，我再继续谈。",
    持续时间: 6,
  },
  {
    type: "runAction",
    id: "snake_keeper_quest",
    名称: "发布沙漠食人魔目标",
    动作ID: "SRZ蛇人族_食人魔任务刷新",
    参数: {
      任务描述: "前往沙漠深处击败『沙漠食人魔』，取得蛇人族需要的凭证。",
      任务更新提示: "|cffffff00『主线目标』：|r击败|cffff6600『沙漠食人魔』|r。",
    },
  },
];

export const 沙漠到蛇人族剧情片段: 剧情片段配置 = {
  片段ID: "jlc_desert_to_snake_territory",
  名称: "沙漠到蛇人族",
  可Esc整段跳过: true,
  默认倍速: 1,
  步骤列表: [...沙漠入口调查步骤, ...沙漠居民线索步骤, ...情报商人与蛇人入口步骤],
};

export default 沙漠到蛇人族剧情片段;
