/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";
import { 常规BuffID } from "../00．Buff登记";

export const 旧主动物品Buff表: Record<string, BuffData> = {
  [常规BuffID.狂暴树枝_狂暴]: {
    buffID: 常规BuffID.狂暴树枝_狂暴,
    buffName: "狂暴",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000122.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "受到「狂暴树枝」影响，time秒内攻击速度提高data%，但每秒受到data2点强化伤害。",
  },
  [常规BuffID.首领号角_王之号角]: {
    buffID: 常规BuffID.首领号角_王之号角,
    buffName: "王之号角",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000102.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "受到「首领号角」鼓舞，time秒内攻击力提高data，护甲提高data2。",
  },
  [常规BuffID.精灵号角_王之号角]: {
    buffID: 常规BuffID.精灵号角_王之号角,
    buffName: "王之号角",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000346.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "受到「精灵号角」鼓舞，time秒内攻击力提高data%；若为持有者，额外提高data2点攻击力。",
  },
  [常规BuffID.精灵号角_号角光环]: {
    buffID: 常规BuffID.精灵号角_号角光环,
    buffName: "精灵号角",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000346.blp",
    effect: "",
    type: "Aura:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "处于「精灵号角」光环中，攻击力提高data%，护甲提高data2。",
  },
  [常规BuffID.地狱火卡牌攻击_地狱火攻击]: {
    buffID: 常规BuffID.地狱火卡牌攻击_地狱火攻击,
    buffName: "地狱火攻击",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000190.blp",
    effect: "Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "受到「地狱火攻击」强化，time秒内攻击力提高data，攻击速度提高data2%。",
  },
  [常规BuffID.焰混能量体_混焰]: {
    buffID: 常规BuffID.焰混能量体_混焰,
    buffName: "混焰",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000191.blp",
    effect: "Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "释放「混焰」，time秒内攻击速度提高data%，剩余data2次普通攻击。",
  },
  [常规BuffID.恶斯胸甲_祭血攻击]: {
    buffID: 常规BuffID.恶斯胸甲_祭血攻击,
    buffName: "祭血攻击",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000326.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "释放「祭血攻击」，time秒内下一次超过data点的伤害提高100%，并追加基于消耗生命值的火属性伤害。",
  },
  [常规BuffID.恶斯胸甲_祭血灼烧]: {
    buffID: 常规BuffID.恶斯胸甲_祭血灼烧,
    buffName: "祭血灼烧",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000326.blp",
    effect: "Common\\Effect\\Element\\Fire\\fireball.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:equipment:dot",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "受到「祭血灼烧」影响，time秒内受到data点火属性持续伤害。",
  },
  [常规BuffID.女妖魔甲_完全免疫]: {
    buffID: 常规BuffID.女妖魔甲_完全免疫,
    buffName: "魔力获取",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000064.blp",
    effect: "Common\\Effect\\Element\\Dark\\blackhole.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "释放「魔力获取」，time秒内魔法伤害提高data%，结束后生命值和魔法值降为1点。",
  },
  [常规BuffID.嗜狱恶剑_嗜狱]: {
    buffID: 常规BuffID.嗜狱恶剑_嗜狱,
    buffName: "嗜狱",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000069.blp",
    effect: "Abilities\\Spells\\Items\\VampiricPotion\\VampPotionCaster.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "释放「嗜狱」，time秒内攻击力提高data，普通攻击必定暴击。",
  },
  [常规BuffID.斯尔能量之心_能量爆发]: {
    buffID: 常规BuffID.斯尔能量之心_能量爆发,
    buffName: "能量爆发",
    icon: "ReplaceableTextures\\CommandButtons\\BTN000055.blp",
    effect: "war3mapImported\\[AKE]war3AKE.com - 7111549081860231340610379.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "释放「能量爆发」，time秒内伤害提高data%。",
  },
};

export default 旧主动物品Buff表;
