/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";
import { 常规BuffID } from "../00．Buff登记";

export const 亚伦柯斯装备Buff表: Record<string, BuffData> = {
  [常规BuffID.最后阵地重铠_守阵]: {
    buffID: 常规BuffID.最后阵地重铠_守阵,
    buffName: "守阵",
    icon: "Equipment\\Icon\\Clothes\\aronkos_last_stand_heavy_armor.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 3,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data2属性名: "物理抗性",
    tooltip: "持续驻留时获得守阵：护甲提高data，物理抗性提高data2%，控制抗性提高20%；每层独立持续time秒，最多同时存在3层。",
  },
  [常规BuffID.亡者凝视面甲_亡者反击]: {
    buffID: 常规BuffID.亡者凝视面甲_亡者反击,
    buffName: "亡者反击",
    icon: "Equipment\\Icon\\Helmet\\aronkos_dead_gaze_faceplate.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    tooltip: "正面承受至少data2点减伤前伤害后获得强化；time秒内下一次纯普攻或单体技能伤害提高data%，触发后消耗。",
  },
  [常规BuffID.安魂守墓灯_安魂余光]: {
    buffID: 常规BuffID.安魂守墓灯_安魂余光,
    buffName: "安魂余光",
    icon: "Equipment\\Icon\\Item\\aronkos_soul_rest_grave_lantern.blp",
    effect: "",
    type: "Buff:equipment:heal",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: false,
    tooltip: "安魂观察中：若time秒内未受伤，恢复data%最大生命值和data2点魔法；若受伤则转为「安魂庇护」。",
  },
  [常规BuffID.安魂守墓灯_安魂庇护]: {
    buffID: 常规BuffID.安魂守墓灯_安魂庇护,
    buffName: "安魂庇护",
    icon: "Equipment\\Icon\\Item\\aronkos_soul_rest_grave_lantern.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "物理抗性",
    tooltip: "物理抗性和魔法抗性各提高data%，持续time秒。",
  },
  [常规BuffID.裂誓战躯重铠_残誓不退]: {
    buffID: 常规BuffID.裂誓战躯重铠_残誓不退,
    buffName: "残誓不退",
    icon: "Equipment\\Icon\\Clothes\\ancestral_twin_broken_oath_heavy_armor.blp",
    effect: "Common\\Effect\\Form\\Shield\\AlbedoDarkGoldBarrier.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.64,
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "物理抗性",
    data2属性名: "魔抗",
    tooltip: "物理抗性提高data%，魔抗提高data2%，控制抗性提高40%，移动速度降低25%，持续time秒。",
  },
};

export default 亚伦柯斯装备Buff表;
