/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";
import { 常规BuffID } from "../00．Buff登记";

export const 祖地双灵卫装备Buff表: Record<string, BuffData> = {
  [常规BuffID.赤誓断界剑_誓锋壁进]: {
    buffID: 常规BuffID.赤誓断界剑_誓锋壁进,
    buffName: "誓锋壁进",
    icon: "Equipment\\Icon\\MainWeapon\\Sword\\ancestral_twin_red_oath_boundary_sword.blp",
    effect: "",
    type: "Buff:equipment:attack-enhance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "普攻强化伤害",
    tooltip: "下一次纯普通攻击的伤害提高data%；命中时对攻击方向前方100°、360码内的其他敌人造成攻击力70%的物理伤害，并获得最大生命8%的护盾，持续4秒。强化剩余time秒。",
  },
  [常规BuffID.苍影校魂法典_灵识校准]: {
    buffID: 常规BuffID.苍影校魂法典_灵识校准,
    buffName: "灵识校准",
    icon: "Equipment\\Icon\\SubWeapon\\ancestral_twin_blue_shadow_soul_codex.blp",
    effect: "",
    type: "Debuff:equipment:attribute:magic",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 1,
    priority: 5,
    canPurge: true,
    tooltip: "受到灵识校准，魔法抗性降低data%，持续time秒。",
  },
  [常规BuffID.灵印折步靴_折步回身]: {
    buffID: 常规BuffID.灵印折步靴_折步回身,
    buffName: "折步回身",
    icon: "Equipment\\Icon\\Shoes\\ancestral_twin_spirit_step_boots.blp",
    effect: "",
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "物理抗性",
    data2属性名: "魔抗",
    tooltip: "物理抗性和魔抗分别提高data%和data2%，眩晕抗性提高30%，持续time秒。",
  },
  [常规BuffID.月白归静圣铃_净誓余辉]: {
    buffID: 常规BuffID.月白归静圣铃_净誓余辉,
    buffName: "净誓余辉",
    icon: "Equipment\\Icon\\Item\\ancestral_twin_moonwhite_rest_bell.blp",
    effect: "Common\\Effect\\Form\\Debuff\\SpiritGuardPurificationRecoil.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.2,
    effectHeight: 75,
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "物理抗性",
    data2属性名: "魔抗",
    tooltip: "物理抗性和魔抗分别提高data%和data2%，眩晕抗性提高30%，持续time秒。",
  },
};

export default 祖地双灵卫装备Buff表;
