/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";
import { 常规BuffID } from "../00．Buff登记";

export const 祖地秘境装备Buff表: Record<string, BuffData> = {
  [常规BuffID.金鳞守誓铠_重鳞]: {
    buffID: 常规BuffID.金鳞守誓铠_重鳞,
    buffName: "重鳞",
    icon: "ReplaceableTextures\\CommandButtons\\Equipment\\Icon\\Clothes\\BTNGoldenScaleOathArmor.blp",
    effect: "Abilities\\Spells\\Human\\InnerFire\\InnerFireTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.8,
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "护甲",
    tooltip: "金鳞层层竖起，护甲提高data点，持续time秒；6秒未受击后重鳞平复。",
  },
  [常规BuffID.鳞影裂波刃_裂波]: {
    buffID: 常规BuffID.鳞影裂波刃_裂波,
    buffName: "裂波",
    icon: "ReplaceableTextures\\CommandButtons\\Equipment\\Icon\\MainWeapon\\Dagger\\BTNScaleShadowRiftblade.blp",
    effect: "Common\\Effect\\Element\\Water\\WetShockMark.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.6,
    type: "Buff:equipment:attack-enhance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    tooltip: "潮势蓄于刃上，time秒内的下一次纯普通攻击必定暴击，触发或超时后消失。",
  },
  [常规BuffID.潮印祈福徽_祈福]: {
    buffID: 常规BuffID.潮印祈福徽_祈福,
    buffName: "祈福",
    icon: "ReplaceableTextures\\CommandButtons\\Equipment\\Icon\\Item\\BTNTideBlessingSeal.blp",
    effect: "Common\\Effect\\Element\\Light\\protectionaura.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.22,
    effectHeight: 75,
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "物理抗性",
    data2属性名: "魔抗",
    tooltip: "灵潮祈福环绕：物理抗性和魔抗分别提高data%和data2%，持续time秒，重复施法刷新。",
  },
  [常规BuffID.祖地战冠_战意]: {
    buffID: 常规BuffID.祖地战冠_战意,
    buffName: "战意",
    icon: "ReplaceableTextures\\CommandButtons\\Equipment\\Icon\\Helmet\\BTNAncestralWarCrown.blp",
    effect: "Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.8,
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "攻击力",
    tooltip: "先祖战意被唤起：攻击力提高data点，持续time秒；击杀敌方单位可叠加，最多3层。",
  },
  [常规BuffID.影潮轻披_影潮]: {
    buffID: 常规BuffID.影潮轻披_影潮,
    buffName: "影潮",
    icon: "ReplaceableTextures\\CommandButtons\\Equipment\\Icon\\Clothes\\BTNShadowTideCloak.blp",
    effect: "Common\\Effect\\Element\\Wind\\SmallWindBurst.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    effectScale: 0.5,
    type: "Buff:equipment:attribute",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 0,
    priority: 5,
    canPurge: true,
    data属性名: "移动速度",
    tooltip: "暗潮在脚下涌动：移动速度提高data%，持续time秒。",
  },
};

export default 祖地秘境装备Buff表;
