/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 米亚Buff表: Record<string, BuffData> = {
  BMI1: {
    buffID: "BMI1",
    buffName: "腐化感染",
    icon: "BuffIcon\\Boss\\Mia\\corruption_infection.blp",
    effect: "Units\\Undead\\PlagueCloud\\PlagueCloudtarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:poison",
    interval: 0,
    maxStack: 15,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 85,
    canPurge: false,
    tooltip: "最多15层。每层使你受到米亚及其召唤物造成的最终伤害提高2%，并使你所属玩家受到的治疗量降低4%；15层时分别为受到米亚伤害提高30%、受到治疗量降低60%。普通位置4秒后每2秒减少1层；未被污染且未超载的安全平台上2秒后每1秒减少1层。终极污染完成时会被设为15层并立即死亡。",
  },
  BMI2: {
    buffID: "BMI2",
    buffName: "污染标记",
    icon: "BuffIcon\\Boss\\Mia\\pollution_mark.blp",
    effect: "",
    effectAttachPoint: "origin",
    type: "Debuff:mark",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "仅P1生效；每1秒重新判定腐化感染层数最高的玩家，同层时优先选择仇恨值最高者。标记持续1.5秒并刷新；米亚的腐化爪击和污水喷吐对你造成的伤害提高20%。标记目标死亡时，米亚恢复自身最大生命值的10%。",
  },
  BMI3: {
    buffID: "BMI3",
    buffName: "平台超载",
    icon: "BuffIcon\\Boss\\Mia\\platform_overload.blp",
    effect: "",
    type: "Debuff:field",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 88,
    canPurge: false,
    tooltip: "仅P2/P3生效。1-2人模式平台容量为1人，3-4人模式平台容量为2人；人数超过容量后，每1秒增加1层腐化感染，并使米亚的腐化爪击、污水喷吐、污染脉冲和污水柱爆发对你造成的伤害提高30%。离开超载平台或人数恢复到容量内后移除。",
  },
  BMI4: {
    buffID: "BMI4",
    buffName: "腐化黏液涂层",
    icon: "BuffIcon\\Boss\\Mia\\corrupt_slime_coating.blp",
    effect: "",
    type: "Buff:boss",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 86,
    canPurge: false,
    tooltip: "P3米亚常驻状态。米亚受到的所有伤害提高20%；玩家使用近战普通攻击命中米亚时，每名玩家每5秒最多增加1层腐化感染。米亚每10秒使所有有效玩家增加1层腐化感染。",
  },
};

export default 米亚Buff表;
