/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 卡瑟拉BuffID = {
  触手缠绕: "BKS1",
  墨汁遮蔽: "BKS2",
  触手残片: "BKS3",
  触手精华: "BKS4",
  麻痹电流: "BKS5",
  绝缘庇护: "BKS6",
} as const;

export type 卡瑟拉BuffID类型 = typeof 卡瑟拉BuffID[keyof typeof 卡瑟拉BuffID];

export const 卡瑟拉Buff表: Record<string, BuffData> = {
  [卡瑟拉BuffID.触手缠绕]: {
    buffID: 卡瑟拉BuffID.触手缠绕,
    buffName: "触手缠绕",
    icon: "BuffIcon\\Boss\\Kasela\\tentacle_bind.blp",
    effect: "",
    type: "Debuff:control",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 72,
    canPurge: true,
    禁止位移: true,
    tooltip: "持续3秒。攻击速度降低40%、移动速度降低40%，并禁止使用冲锋、跳跃、闪烁等位移技能。",
  },
  [卡瑟拉BuffID.墨汁遮蔽]: {
    buffID: 卡瑟拉BuffID.墨汁遮蔽,
    buffName: "墨汁遮蔽",
    icon: "BuffIcon\\Boss\\Kasela\\ink_shroud.blp",
    effect: "",
    type: "Debuff:control:dot:magic",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 76,
    canPurge: true,
    tooltip: "每次命中刷新0.3秒：视野减少1200并沉默0.1秒；在墨汁区域内每秒受到Boss当前攻击力×55%的伤害。拥有35%或以上水属性抗性时，伤害降为Boss当前攻击力×19.25%/秒，沉默降为每次0.035秒。",
  },
  [卡瑟拉BuffID.触手残片]: {
    buffID: 卡瑟拉BuffID.触手残片,
    buffName: "触手残片",
    icon: "BuffIcon\\Boss\\Kasela\\tentacle_fragment.blp",
    effect: "",
    type: "Buff:stack",
    interval: 0,
    maxStack: 5,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "持有1~5层；每层增加7%水属性抗性。拾取后若总层数达到3层及以上，立即恢复20%已损失生命；共生电击结算时若不在安全区，消耗3层可完全抵消本次命中。",
  },
  [卡瑟拉BuffID.触手精华]: {
    buffID: 卡瑟拉BuffID.触手精华,
    buffName: "触手精华",
    icon: "BuffIcon\\Boss\\Kasela\\tentacle_essence.blp",
    effect: "",
    type: "Buff:boss:stack",
    interval: 0,
    maxStack: 99,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 88,
    canPurge: false,
    tooltip: "持续20秒；每层按卡瑟拉吸收瞬间的当前攻击力×3%换算为固定攻击力值并加入（不是基础攻击力或总攻击力百分比），每吸收1片额外恢复最大生命值2%；可叠加，最多显示99层。",
  },
  [卡瑟拉BuffID.麻痹电流]: {
    buffID: 卡瑟拉BuffID.麻痹电流,
    buffName: "麻痹电流",
    icon: "BuffIcon\\Boss\\Kasela\\paralyzing_current.blp",
    effect: "Common\\Effect\\Element\\Thunder\\ThunderParalyzeHit.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:control",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 86,
    canPurge: true,
    tooltip: "持续3秒，无法移动、攻击或施法。仅在未进入绝缘珊瑚300码安全半径且未消耗3层触手残片抵消时施加。",
  },
  [卡瑟拉BuffID.绝缘庇护]: {
    buffID: 卡瑟拉BuffID.绝缘庇护,
    buffName: "绝缘庇护",
    icon: "BuffIcon\\Boss\\Kasela\\insulated_shelter.blp",
    effect: "",
    type: "Buff:safe",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: false,
    tooltip: "持续3秒。共生电击结算瞬间位于绝缘珊瑚300码安全半径内时获得，完全免疫本次6500点电击伤害与3秒眩晕；离开安全区不会提前移除。",
  },
};

export default 卡瑟拉Buff表;
