/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 莫尔特斯BuffID = {
  腐败值: "BMO1",
  根须缠绕: "BMO2",
  荆棘寄生: "BMO3",
  腐败护盾: "BMO4",
  净化庇护: "BMO5",
  腐败虫尸净化: "BMO6",
} as const;

export type 莫尔特斯BuffID类型 = typeof 莫尔特斯BuffID[keyof typeof 莫尔特斯BuffID];

export const 莫尔特斯Buff表: Record<string, BuffData> = {
  [莫尔特斯BuffID.腐败值]: {
    buffID: 莫尔特斯BuffID.腐败值,
    buffName: "腐败值",
    icon: "BuffIcon\\Boss\\Moltes\\corruption_value.blp",
    effect: "",
    type: "Debuff:stack",
    interval: 0,
    maxStack: 100,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "腐败值持续累积。达到100时触发根须缠绕；可通过净化光斑、净化药剂或腐败虫尸清除。",
  },
  [莫尔特斯BuffID.根须缠绕]: {
    buffID: 莫尔特斯BuffID.根须缠绕,
    buffName: "根须缠绕",
    icon: "BuffIcon\\Boss\\Moltes\\root_bind.blp",
    effect: "Abilities\\Spells\\NightElf\\EntanglingRoots\\EntanglingRootsTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:control:dot",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 84,
    canPurge: true,
    禁止位移: true,
    tooltip: "腐败值满或特定技能命中后被根须缠绕，无法移动并持续受到伤害。",
  },
  [莫尔特斯BuffID.荆棘寄生]: {
    buffID: 莫尔特斯BuffID.荆棘寄生,
    buffName: "荆棘寄生",
    icon: "BuffIcon\\Boss\\Moltes\\thorn_parasite.blp",
    effect: "Common\\Effect\\Element\\Nature\\Thorn Slam.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot",
    interval: 3,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 76,
    canPurge: true,
    tooltip: "被扭曲荆棘寄生，每3秒受到伤害，持续12秒；可被驱散或站在净化光斑上移除。",
  },
  [莫尔特斯BuffID.腐败护盾]: {
    buffID: 莫尔特斯BuffID.腐败护盾,
    buffName: "腐败护盾",
    icon: "BuffIcon\\Boss\\Moltes\\corruption_shield.blp",
    effect: "Common\\Effect\\Form\\Shield\\Root Shield.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:shield",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 88,
    canPurge: false,
    tooltip: "莫尔特斯通过腐败传输获得护盾，护盾值基于转移的腐败值。",
  },
  [莫尔特斯BuffID.净化庇护]: {
    buffID: 莫尔特斯BuffID.净化庇护,
    buffName: "净化庇护",
    icon: "BuffIcon\\Boss\\Moltes\\cleansing_shelter.blp",
    effect: "Common\\Effect\\Form\\MagicCircle\\GaiaShield.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:cleanse",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: false,
    tooltip: "站在净化光斑内获得净化庇护，每秒清除腐败值，可作为安全/净化状态提示。",
  },
  [莫尔特斯BuffID.腐败虫尸净化]: {
    buffID: 莫尔特斯BuffID.腐败虫尸净化,
    buffName: "腐败虫尸净化",
    icon: "BuffIcon\\Boss\\Moltes\\corrupt_beetle_corpse.blp",
    effect: "",
    type: "Buff:cleanse",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 1,
    priority: 72,
    canPurge: true,
    tooltip: "使用腐败虫尸后获得短暂净化或一次性清除固定腐败值。",
  },
};

export default 莫尔特斯Buff表;
