/** @noSelfInFile */

import type { BuffData } from "../../../01．Buff表";

export const 影骨莫特斯BuffID = {
  背刺准备: "BSB1",
  暗影禁锢: "BSB2",
  幽灵形态: "BSB3",
  幽影视野压制: "BSB4",
  暗影强化: "BSB5",
  骸骨符咒: "BSB6",
  盗贼遗产: "BSB7",
  阴影陷阱眩晕: "BSB8",
  P3强化: "BSB9",
} as const;

export type 影骨莫特斯BuffID类型 = typeof 影骨莫特斯BuffID[keyof typeof 影骨莫特斯BuffID];

export const 影骨莫特斯Buff表: Record<string, BuffData> = {
  [影骨莫特斯BuffID.背刺准备]: {
    buffID: 影骨莫特斯BuffID.背刺准备,
    buffName: "背刺准备",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\backstab_ready.blp",
    effect: "",
    type: "Buff:boss:next-attack",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "持续12秒或触发1次后消失。下一次纯普通攻击造成原伤害2.5倍；玩家正面朝向莫特斯时，背刺最终伤害降低50%。",
  },
  [影骨莫特斯BuffID.暗影禁锢]: {
    buffID: 影骨莫特斯BuffID.暗影禁锢,
    buffName: "暗影禁锢",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\shadow_prison.blp",
    effect: "",
    type: "Debuff:control",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 84,
    canPurge: false,
    禁止位移: true,
    tooltip: "暗影法阵0.9秒预警后生效，半径320码；命中后禁锢4秒，无法移动或施法。队友摧毁法阵后，剩余禁锢时间缩短为1秒。",
  },
  [影骨莫特斯BuffID.幽灵形态]: {
    buffID: 影骨莫特斯BuffID.幽灵形态,
    buffName: "幽灵形态",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\ghost_form.blp",
    effect: "",
    type: "Buff:boss:stance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 88,
    canPurge: false,
    tooltip: "持续20秒。莫特斯受到物理伤害时只承受60%（降低40%），受到魔法伤害时承受140%（提高40%）。",
  },
  [影骨莫特斯BuffID.幽影视野压制]: {
    buffID: 影骨莫特斯BuffID.幽影视野压制,
    buffName: "幽影视野压制",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\shadow_vision.blp",
    effect: "",
    type: "Debuff:vision",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 80,
    canPurge: false,
    tooltip: "持续20秒，所有玩家视野减少1600；幽影爆发结束、莫特斯死亡或战斗重置时恢复。",
  },
  [影骨莫特斯BuffID.暗影强化]: {
    buffID: 影骨莫特斯BuffID.暗影强化,
    buffName: "暗影强化",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\shadow_summon_empower.blp",
    effect: "",
    type: "Buff:summon:damage",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 72,
    canPurge: false,
    tooltip: "幽影爆发期间持续20秒；新召唤的骷髅普通攻击转为暗属性伤害，幽影爆发结束后不再转换。",
  },
  [影骨莫特斯BuffID.骸骨符咒]: {
    buffID: 影骨莫特斯BuffID.骸骨符咒,
    buffName: "骸骨符咒",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\bone_charm.blp",
    effect: "",
    type: "Buff:defense",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 1,
    priority: 62,
    canPurge: true,
    tooltip: "拾取莫特斯召唤物掉落的符咒后，获得+15护甲和+20%魔法抗性，持续12秒。",
  },
  [影骨莫特斯BuffID.盗贼遗产]: {
    buffID: 影骨莫特斯BuffID.盗贼遗产,
    buffName: "盗贼遗产",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\thieves_legacy.blp",
    effect: "",
    type: "Buff:boss:stack",
    interval: 0,
    maxStack: 4,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 78,
    canPurge: false,
    tooltip: "每层对应1个已开启宝箱；每开1个宝箱，按开启前莫特斯当前攻击力的3%追加为固定攻击力，永久保留，最多4层。无其他攻击力变化时，连续开启4个相对初始当前攻击力累计提高12.550881%。",
  },
  [影骨莫特斯BuffID.阴影陷阱眩晕]: {
    buffID: 影骨莫特斯BuffID.阴影陷阱眩晕,
    buffName: "阴影陷阱眩晕",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\shadow_trap_stun.blp",
    effect: "",
    type: "Debuff:control",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 74,
    canPurge: false,
    tooltip: "触发盗贼宝箱10%陷阱时，开启者当前生命保留30%（损失当前生命70%，不致死），并眩晕1.5秒。",
  },
  [影骨莫特斯BuffID.P3强化]: {
    buffID: 影骨莫特斯BuffID.P3强化,
    buffName: "阴影主宰",
    icon: "BuffIcon\\Boss\\ShadowboneMortes\\shadow_summon_empower.blp",
    effect: "",
    type: "Buff:boss:phase",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "P3期间持续生效：进入P3时按当时莫特斯当前攻击力的30%追加固定攻击力（只应用1次）；幽影爆发最大冷却改为原始冷却的65%，基础40秒时为26秒。",
  },
};

export default 影骨莫特斯Buff表;
