--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports["莫尔特斯BuffID"] = {
    ["腐败值"] = "BMO1",
    ["根须缠绕"] = "BMO2",
    ["荆棘寄生"] = "BMO3",
    ["腐败护盾"] = "BMO4",
    ["净化庇护"] = "BMO5",
    ["腐败虫尸净化"] = "BMO6"
}
____exports["莫尔特斯Buff表"] = {
    [____exports["莫尔特斯BuffID"]["腐败值"]] = {
        buffID = ____exports["莫尔特斯BuffID"]["腐败值"],
        buffName = "腐败值",
        icon = "BuffIcon\\Boss\\Moltes\\corruption_value.blp",
        effect = "",
        type = "Debuff:stack",
        interval = 0,
        maxStack = 100,
        stackRule = "stack",
        stackRefresh = true,
        dispelLevel = 3,
        priority = 90,
        canPurge = false,
        tooltip = "最多100层；达到100层后触发根须缠绕。站在净化光斑内每秒清除10层，拾取腐败虫尸立即清除30层。"
    },
    [____exports["莫尔特斯BuffID"]["根须缠绕"]] = {
        buffID = ____exports["莫尔特斯BuffID"]["根须缠绕"],
        buffName = "根须缠绕",
        icon = "BuffIcon\\Boss\\Moltes\\root_bind.blp",
        effect = "Abilities\\Spells\\NightElf\\EntanglingRoots\\EntanglingRootsTarget.mdl",
        effectMode = "attach",
        effectAttachPoint = "origin",
        type = "Debuff:control:dot",
        interval = 1,
        maxStack = 1,
        stackRule = "highest",
        stackRefresh = true,
        dispelLevel = 2,
        priority = 84,
        canPurge = true,
        ["禁止位移"] = true,
        tooltip = "持续4秒并禁止移动；每1秒结算1次，共4次，每次造成目标已损失生命值的10%加上莫尔特斯当前攻击力的50%伤害。"
    },
    [____exports["莫尔特斯BuffID"]["荆棘寄生"]] = {
        buffID = ____exports["莫尔特斯BuffID"]["荆棘寄生"],
        buffName = "荆棘寄生",
        icon = "BuffIcon\\Boss\\Moltes\\thorn_parasite.blp",
        effect = "Common\\Effect\\Element\\Nature\\Thorn Slam.mdx",
        effectMode = "attach",
        effectAttachPoint = "origin",
        type = "Debuff:dot",
        interval = 3,
        maxStack = 1,
        stackRule = "highest",
        stackRefresh = true,
        dispelLevel = 2,
        priority = 76,
        canPurge = true,
        tooltip = "持续12秒，每3秒结算1次，共4次；每次造成莫尔特斯施加时攻击力的20%伤害。可被驱散或站在净化光斑内移除。"
    },
    [____exports["莫尔特斯BuffID"]["腐败护盾"]] = {
        buffID = ____exports["莫尔特斯BuffID"]["腐败护盾"],
        buffName = "腐败护盾",
        icon = "BuffIcon\\Boss\\Moltes\\corruption_shield.blp",
        effect = "Common\\Effect\\Form\\Shield\\Root Shield.mdx",
        effectMode = "attach",
        effectAttachPoint = "origin",
        type = "Buff:boss:shield",
        interval = 0,
        maxStack = 1,
        stackRule = "highest",
        stackRefresh = true,
        dispelLevel = 3,
        priority = 88,
        canPurge = false,
        tooltip = "莫尔特斯每损失5%生命值触发一次腐败传输：随机目标增加10点腐败值，莫尔特斯获得按被传输目标已损失生命值50%计算的真实护盾，最低1000点，持续10秒；再次触发时按新目标损失生命值追加并刷新10秒持续时间。"
    },
    [____exports["莫尔特斯BuffID"]["净化庇护"]] = {
        buffID = ____exports["莫尔特斯BuffID"]["净化庇护"],
        buffName = "净化庇护",
        icon = "BuffIcon\\Boss\\Moltes\\cleansing_shelter.blp",
        effect = "Common\\Effect\\Form\\MagicCircle\\GaiaShield.mdx",
        effectMode = "attach",
        effectAttachPoint = "origin",
        type = "Buff:cleanse",
        interval = 1,
        maxStack = 1,
        stackRule = "highest",
        stackRefresh = true,
        dispelLevel = 3,
        priority = 70,
        canPurge = false,
        tooltip = "站在净化光斑内时获得此状态，每秒清除10点腐败值。"
    },
    [____exports["莫尔特斯BuffID"]["腐败虫尸净化"]] = {
        buffID = ____exports["莫尔特斯BuffID"]["腐败虫尸净化"],
        buffName = "腐败虫尸净化",
        icon = "BuffIcon\\Boss\\Moltes\\corrupt_beetle_corpse.blp",
        effect = "",
        type = "Buff:cleanse",
        interval = 1,
        maxStack = 1,
        stackRule = "highest",
        stackRefresh = true,
        dispelLevel = 1,
        priority = 72,
        canPurge = true,
        tooltip = "拾取腐败虫尸后立即清除30点腐败值，并获得3秒净化状态。"
    }
}
____exports.default = ____exports["莫尔特斯Buff表"]
return ____exports
