-- Boss common unit templates.

function createBossHeroUnit(id, name, options)
  options = options or {}

  local unit = HeroDefinition:new(id, options.baseId or 'Nbrn')
  unit:setName(name)
  unit:setNameEditorSuffix(options.editorSuffix or '')
  unit:setProperNames(options.properNames or name)
  unit:setProperNamesUsed(options.properNamesUsed or 1)
  unit:setTooltipBasic(options.tooltipBasic or name)
  unit:setTooltipExtended(options.tooltipExtended or name)
  unit:setDescription(options.description or name)
  unit:setRequirements(options.requirements or '')
  unit:setModelFile(options.modelFile or '.mdl')
  unit:setModelFileExtraVersions(tostring(options.modelFileExtraVersions or 0))
  unit:setIconGameInterface(options.icon or 'ReplaceableTextures\\CommandButtons\\BTNHeroDarkRanger.blp')
  unit:setRace(options.race or Race.Demon)
  unit:setDisplayasNeutralHostile(options.displayAsNeutralHostile ~= false)
  unit:setUseClickHelper(options.useClickHelper or false)
  unit:setHasTilesetSpecificData(options.tilesetSpecific or false)
  unit:setNormalAbilities(options.abilities or 'AInv')
  unit:setHeroAbilities(options.heroAbilities or '')
  unit:setDefaultActiveAbility(options.defaultActiveAbility or '')
  unit:setUpgradesUsed(options.upgrades or 'R001,R002')
  unit:setUnitSoundSet(options.soundSet or '')
  unit:setUnitClassification(options.classification or 'undead')
  unit:setLevel(options.level or 10)
  unit:setHitPointsMaximumBase(options.hp or 500)
  unit:setHitPointsRegenerationType(options.regenType or 'always')
  unit:setHitPointsRegenerationRate(options.hpRegen or 0.0)
  unit:setManaMaximum(options.mana or 1000)
  unit:setManaInitialAmount(options.initialMana or 99999)
  unit:setManaRegeneration(options.manaRegen or 10.0)
  unit:setSpeedBase(options.speed or 322)
  unit:setSpeedMinimum(options.speedMinimum or 0)
  unit:setSpeedMaximum(options.speedMaximum or 522)
  unit:setMovementType(options.movementType or MovementType.Foot)
  unit:setTurnRate(options.turnRate or 0.6)
  unit:setPropulsionWindowdegrees(options.propulsionWindow or 60.0)
  unit:setTransportedSize(options.cargoSize or 1)
  unit:setCollisionSize(options.collision or 32.0)
  unit:setScalingValue(options.scale or 2.0)
  unit:setSightRadiusDay(options.sightDay or 1800)
  unit:setSightRadiusNight(options.sightNight or 1400)
  unit:setAcquisitionRange(options.acquire or 1200.0)
  unit:setCanFlee(options.canFlee or false)
  unit:setSleeps(options.canSleep or false)
  unit:hideHeroMinimapDisplay(options.hideHeroMinimap or false)
  unit:hideHeroInterfaceIcon(options.hideHeroIcon or false)
  unit:hideHeroDeathMsg(options.hideHeroDeathMsg or false)
  unit:setPrimaryAttribute(options.primaryAttribute or 'AGI')
  unit:setStartingStrength(options.strength or 18)
  unit:setStartingAgility(options.agility or 19)
  unit:setStartingIntelligence(options.intelligence or 15)
  unit:setStrengthPerLevel(options.strengthPerLevel or 1.90)
  unit:setAgilityPerLevel(options.agilityPerLevel or 1.50)
  unit:setIntelligencePerLevel(options.intelligencePerLevel or 2.60)
  unit:setAttacksEnabled(options.attacksEnabled or AttacksEnabled.AttackOneOnly)
  unit:setAttack1AttackType(options.attackType or AttackType.Magic)
  unit:setAttack1DamageBase(options.damageBase or 100)
  unit:setAttack1DamageNumberofDice(options.damageDice or 1)
  unit:setAttack1DamageSidesperDie(options.damageSides or 1)
  unit:setAttack1CooldownTime(options.attackCooldown or 2.0)
  unit:setAttack1Range(options.attackRange or 600)
  unit:setAttack1TargetsAllowed(options.attackTargets or 'ground,air,enemy,neutral')
  unit:setAttack1WeaponType(options.weaponType or WeaponType.Missile)
  unit:setAttack1ProjectileSpeed(options.projectileSpeed or 900)
  unit:setAttack1ProjectileArt(options.projectileArt or '')
  unit:setArmorType(options.armorType or ArmorType.Hero)
  unit:setDefenseBase(options.defense or 0)
  unit:setDefenseUpgradeBonus(options.defenseUpgradeBonus or 0)
  unit:setPointValue(options.pointValue or 100)
  unit:setPriority(options.priority or 9)
  unit:setFormationRank(options.formation or 2)
  unit:setGoldBountyAwardedBase(options.goldBountyBase or 500)
  unit:setGoldBountyAwardedNumberofDice(options.goldBountyDice or 1)
  unit:setGoldBountyAwardedSidesperDie(options.goldBountySides or 1)
  unit:setLumberBountyAwardedBase(0)
  unit:setLumberBountyAwardedNumberofDice(0)
  unit:setLumberBountyAwardedSidesperDie(0)
  unit:setFoodCost(0)
  unit:setFoodProduced(0)
  unit:setGoldCost(0)
  unit:setLumberCost(0)
  unit:setBuildTime(0)
  unit:setRepairTime(0)
  unit:setRepairGoldCost(0)
  unit:setRepairLumberCost(0)
  unit:setStockMaximum(0)
  unit:setStockStartDelay(0)
  unit:setStockReplenishInterval(0)
  unit:setItemsSold('')
  unit:setUnitsSold('')
  unit:setStructuresBuilt('')
  unit:setCanDropItemsOnDeath(options.dropItems ~= false)

  return unit
end

function createMeleeBossHeroUnit(id, name, options)
  options = options or {}
  options.baseId = options.baseId or 'Npbm'
  options.attackRange = options.attackRange or 128
  options.weaponType = options.weaponType or WeaponType.Instant
  options.projectileSpeed = options.projectileSpeed or 0
  options.projectileArt = options.projectileArt or ''
  return createBossHeroUnit(id, name, options)
end

function createRangedBossHeroUnit(id, name, options)
  options = options or {}
  options.baseId = options.baseId or 'Nbrn'
  options.attackRange = options.attackRange or 600
  options.weaponType = options.weaponType or WeaponType.Missile
  return createBossHeroUnit(id, name, options)
end
