/** @noSelfInFile */

export const 里科特单位技能配置 = {
  单位ID: "N05U",
  单位名称: "里科特",
  Boss单位ID: "N05U",
  技能壳: {
    四重风刃: "AT04",
    追击风刃: "AT09",
    神风护体: "AN00",
    湮灭之炮: "AN01",
    湮灭之风: "AN02",
    破魔反击: "AN03",
  },
  主动技能提示: [
    { 技能ID: "AT04", 提示: "精灵魔法·四重风刃", 扩展提示: "前摇0.8秒，半径300码区域先受当前攻击力×200%并被减速40%持续1秒；1秒后发射4道龙卷，每道当前攻击力×400%。P2回转里科特，P3追踪随机玩家。（离开区域预警，随后避开龙卷路径。）" },
    { 技能ID: "AT09", 提示: "精灵魔法·追击风刃", 扩展提示: "前摇0.55秒，宽240、长1250码直线造成当前攻击力×300%；P2在1秒后回转里科特，P3在1秒后追踪随机玩家。（离开矩形预警并横向避让。）" },
    { 技能ID: "AN00", 提示: "精灵魔法·神风护体", 扩展提示: "持续4秒、初始7层；每次受击消耗1层并使本次伤害降低50%，同时让攻击者获得1层神风印记，结束时按印记结算粉碎。（护盾期间停止连续攻击，等待护体结束。）" },
    { 技能ID: "AN01", 提示: "精灵魔法·湮灭之炮", 扩展提示: "每名有效玩家身后300码生成投影；P1延迟3秒、P2/P3延迟2秒后锁定3秒，每0.1秒沿1200码直线炮击。P3每个投影另有0~2秒随机落点预警，1秒后半径250码范围眩晕1秒。（看到投影和炮线预警立即离开直线；P3离开圆形落点。）" },
    { 技能ID: "AN02", 提示: "精灵魔法·湮灭之风", 扩展提示: "持续8秒、半径1200码，每0.5秒造成当前攻击力×200%并沉默1.5秒；每跳随机追加眩晕1秒、沉默2秒或减速30%持续4秒。（离开风场覆盖区，避免持续受击。）" },
    { 技能ID: "AN03", 提示: "克林姆德格斗术·破魔反击", 扩展提示: "预备1~5秒后进入2秒反击窗口；受击时，距里科特≤300码移除攻击者当前生命70%，超过300码移除99%，并眩晕0.8秒。（看到反击状态立即停手，等窗口结束。）" },
  ],
  广播持续时间Ms: 4200,
  配音裁断距离: 4000,
  配音生成配置: {
    显示台词字段: "台词",
    配音台词字段: "配音台词",
    声线名称: "Blackwood - Sinister, Posh and British",
    声线ID: "agL69Vji082CshT65Tcy",
    模型ID: "eleven_v3",
    语言: "en",
    整体提示词: "A young exiled elven prince of royal blood who has betrayed his homeland for forbidden power. Refined British aristocratic diction, quiet superiority, sardonic amusement, and effortless magical confidence. In ordinary combat he treats the heroes as an interruption and rarely needs to shout. For annihilation magic and the power of Death, let restraint fracture into intoxicating triumph while preserving the same elegant identity. Clear Warcraft-style combat pacing; not a military commander, not a theatrical narrator, and not a mindless demon.",
    说明: "里科特全阶段使用 Blackwood 保持同一位背叛王子的身份连续。常态强调王族教养、讥讽与居高临下；湮灭之风和挑战结束通过更低稳定度、更高表演强度表现为对死神力量的陶醉，但不切换成纯恶魔声线。",
  },
  台词: {
    开场: ["既然你们执意挡路，我便陪你们稍稍玩一会。（战斗开始，留意技能预警并及时走位。）"],
    四重风刃: ["王族之风，撕碎他们。（先离开斩击区域，再避开随后展开的四道龙卷。）"],
    追击风刃: ["逃吧。风会替我追上你们。（离开矩形预警，注意1秒后的回转或追踪。）"],
    神风护体: ["王族之风，岂会容许你们触及我。（护盾有7层，连续攻击会叠加神风印记。）"],
    粉碎: ["攻击我，是你们犯下的最后一个错误。（神风印记正在清算，停止攻击并远离里科特。）"],
    湮灭之炮: ["看清楚了，这就是你们永远无法企及的魔法。（看到身后投影和炮线预警，立即离开直线。）"],
    湮灭之风: ["感受吧！死神之力与克林姆德血脉结合后的强大！（持续风场覆盖1200码，离开范围规避连续命中。）"],
    破魔反击: ["你们的每一步，都在我的预料之中。（反击窗口开启，立即停手，等待2秒结束。）"],
    死亡: ["还有两下子。那么，就让你们见识一下死神的力量吧！（战斗阶段结束，准备应对后续剧情演出。）"],
  },
  配音台词: {
    开场: ["[amused superiority] If you insist on standing in my way... [dismissive] then I shall indulge you for a moment."],
    四重风刃: ["[aristocratic command] Royal winds... tear them apart!"],
    追击风刃: ["[mocking] Run. [predatory command] The wind will hunt you down for me."],
    神风护体: ["[cold arrogance] The royal wind will not permit your touch."],
    粉碎: ["[merciless punishment] Striking me was your final mistake."],
    湮灭之炮: ["[contemptuous warning] Behold the magic forever beyond your reach. [cold execution] Be erased."],
    湮灭之风: ["[exultant power] Feel it! [dark triumph] The power of Death itself, bound to royal blood!"],
    破魔反击: ["[coldly amused] Every move you make... was foreseen."],
    死亡: ["[surprised amusement] Impressive. [rising dark power] Now witness the power of Death itself!"],
  },
  配音资源: {
    开场: ["Sound\\Boss\\Ricote\\Voice\\ricote_opening_indulge_you_blackwood_01_v3.mp3"],
    四重风刃: ["Sound\\Boss\\Ricote\\Voice\\ricote_quad_windblades_royal_winds_blackwood_01_v3.mp3"],
    追击风刃: ["Sound\\Boss\\Ricote\\Voice\\ricote_chasing_windblade_hunt_you_blackwood_01_v3.mp3"],
    神风护体: ["Sound\\Boss\\Ricote\\Voice\\ricote_divine_wind_guard_no_touch_blackwood_01_v3.mp3"],
    粉碎: ["Sound\\Boss\\Ricote\\Voice\\ricote_mark_shatter_final_mistake_blackwood_01_v3.mp3"],
    湮灭之炮: ["Sound\\Boss\\Ricote\\Voice\\ricote_annihilation_cannon_beyond_reach_blackwood_01_v3.mp3"],
    湮灭之风: ["Sound\\Boss\\Ricote\\Voice\\ricote_annihilation_wind_royal_death_power_blackwood_01_v3.mp3"],
    破魔反击: ["Sound\\Boss\\Ricote\\Voice\\ricote_counter_every_move_foreseen_blackwood_01_v3.mp3"],
    死亡: ["Sound\\Boss\\Ricote\\Voice\\ricote_challenge_end_death_power_blackwood_01_v3.mp3"],
  },
} as const;

export type 里科特台词类型 = keyof typeof 里科特单位技能配置.台词;
