/** @noSelfInFile */

export const 里科特模型动画配置 = {
  模型路径: "Boss\\Ricote\\Ricote.mdx",
  序列表: [
    { 编号: 0, 名称: "Base", 原始时长秒: 0.034, 循环: true, 语义: "模型基础序列，不作为战斗待机" },
    { 编号: 1, 名称: "Stand - 1", 原始时长秒: 3.334, 循环: true, 语义: "待机 1" },
    { 编号: 2, 名称: "Stand - 2", 原始时长秒: 6.667, 循环: true, 语义: "待机 2" },
    { 编号: 3, 名称: "Stand Ready", 原始时长秒: 1, 循环: true, 语义: "战斗准备" },
    { 编号: 4, 名称: "Attack - 1", 原始时长秒: 1, 循环: false, 语义: "横劈" },
    { 编号: 5, 名称: "Attack - 2", 原始时长秒: 1.166, 循环: false, 语义: "上下劈" },
    { 编号: 6, 名称: "Death", 原始时长秒: 1.5, 循环: false, 语义: "死亡" },
    { 编号: 7, 名称: "Stand Victory", 原始时长秒: 2.666, 循环: true, 语义: "举剑胜利" },
    { 编号: 8, 名称: "Spell", 原始时长秒: 2.167, 循环: false, 语义: "举起右手剑施法" },
    { 编号: 9, 名称: "Stand Channel", 原始时长秒: 1.667, 循环: true, 语义: "维持 8 号举剑姿势" },
    { 编号: 10, 名称: "Dissipate", 原始时长秒: 2, 循环: false, 语义: "消散" },
    { 编号: 11, 名称: "Walk", 原始时长秒: 0.766, 循环: true, 语义: "行走" },
    { 编号: 12, 名称: "Stand Fifth", 原始时长秒: 6.667, 循环: false, 语义: "仰头后低头鉴赏自己的剑" },
    { 编号: 13, 名称: "Stand Fourth", 原始时长秒: 3.334, 循环: true, 语义: "待机变化 4" },
  ],
  战斗待机编号: 3,
  施法起手编号: 8,
  施法维持编号: 9,
} as const;

export const 里科特数值与表现配置 = {
  阶段阈值: { P2生命比例: 0.65, P3生命比例: 0.3 },
  被动: {
    每秒回血比例: 0.01,
    控制最大持续秒: 1,
    单次最大生命伤害比例: 0.19,
    普攻必中: true,
  },
  四重风刃: {
    施法距离: 800,
    冷却秒: 13,
    技能槽位: "AT04",
    前摇秒: 0.8,
    动画编号: 5,
    动画速度: 1.0,
    动作原始时长秒: 1.166,
    恢复动画编号: 3,
    吟唱条颜色ID: 2,
    吟唱条标题文本: "精灵魔法·四重风刃",
    吟唱条提示文本: "斩击目标区域后释放四道风刃",
    跳劈半径: 300,
    跳劈Boss攻击力比例: 2.0,
    跳劈减速比例: 0.4,
    跳劈减速秒: 1,
    龙卷风数量: 4,
    龙卷风延迟秒: 1,
    龙卷风速度: 900,
    龙卷风射程: 1200,
    龙卷风命中半径: 130,
    龙卷风Boss攻击力比例: 4.0,
    龙卷风模型路径: "war3mapImported\\xuanfeng4.mdx",
    龙卷风缩放: 1.0,
    龙卷风飞行高度: 80,
    P2回转延迟秒: 1,
    P3追踪延迟秒: 1,
    阶段改向最大距离倍率: 2,
  },
  追击风刃: {
    施法距离: 1250,
    冷却秒: 13,
    技能槽位: "AT09",
    前摇秒: 0.55,
    动画编号: 4,
    动画速度: 1.0,
    动作原始时长秒: 1.0,
    恢复动画编号: 3,
    吟唱条颜色ID: 2,
    吟唱条标题文本: "精灵魔法·追击风刃",
    射程: 1250,
    速度: 1250,
    命中半径: 120,
    Boss攻击力比例: 3.0,
    模型路径: "Common\\Effect\\Form\\Charge\\getsugabluenew.mdx",
    缩放: 1.0,
    飞行高度: 70,
    P2回转延迟秒: 1,
    P3追踪延迟秒: 1,
    阶段改向最大距离倍率: 2,
  },
  神风护体: {
    持续秒: 4,
    施法硬直秒: 0,
    技能槽位: "AN00",
    基础层数: 7,
    受击减伤比例: 0.5,
    粉碎基础眩晕秒: 0.4,
    粉碎每层眩晕秒: 0.2,
    粉碎每层最大生命比例: 0.2,
    动画速度: 1.0,
    施法动作原始时长秒: 2.167,
    维持动作原始时长秒: 1.667,
    粉碎动画编号: 5,
    粉碎动画原始时长秒: 1.166,
    护体特效路径: "Common\\Effect\\Form\\Shield\\BlessingOfAzeroth.mdx",
    粉碎特效路径: "Abilities\\Spells\\Other\\Monsoon\\MonsoonBoltTarget.mdl",
    粉碎伤害特效路径: "Common\\Effect\\Form\\Shield\\RicoteWindShieldDamageImpact.mdx",
    粉碎伤害特效持续秒: 1,
  },
  湮灭之炮: {
    技能槽位: "AN01",
    锁定前延迟秒: 3,
    P2锁定前延迟秒: 2,
    锁定持续秒: 3,
    tick秒: 0.1,
    射程: 1200,
    投影距离: 300,
    投影单位类型: "hfoo",
    投影模型路径: "Boss\\Ricote\\Ricote.mdx",
    投影缩放: 1.35,
    投影透明度: 135,
    出现特效路径: "Common\\Effect\\Form\\Illusion\\MirrorImageIllusion.mdx",
    出现特效持续秒: 1,
    射线特效路径: "Common\\Effect\\Form\\Line\\AnnihilationBeam.mdx",
    射线朝向偏移角度: -90,
    射线持续秒: 0.18,
    每跳Boss攻击力比例: 0.1,
    P3眩晕炮随机延迟最大秒: 2,
    P3眩晕炮延迟秒: 1,
    P3眩晕炮半径: 250,
    P3眩晕秒: 1,
    施法硬直秒: 0,
    动画速度: 1.0,
    施法动作原始时长秒: 2.167,
    维持动作原始时长秒: 1.667,
  },
  湮灭之风: {
    技能槽位: "AN02",
    持续秒: 8,
    沉默秒: 1.5,
    冷却秒: 60,
    tick秒: 0.5,
    半径: 1200,
    Boss攻击力比例: 2.0,
    风场特效路径: "Common\\Effect\\Element\\Wind\\AnnihilationWindField.mdx",
    风场缩放: 2.8,
    风场特效持续秒: 8,
    扩散特效路径: "Common\\Effect\\Form\\Explosion\\WhiteWindExpansion.mdx",
    扩散特效持续秒: 1.2,
    随机控制持续秒: 2,
    随机眩晕秒: 1,
    随机减速比例: 0.3,
    随机减速秒: 4,
    施法硬直秒: 0,
    动画速度: 1.0,
    施法动作原始时长秒: 2.167,
    维持动作原始时长秒: 1.667,
  },
  破魔反击: {
    技能槽位: "AN03",
    预备最小秒: 1,
    预备最大秒: 5,
    反击窗口秒: 2,
    施法硬直秒: 0,
    冷却秒: 40,
    近距离阈值: 300,
    近距离当前生命移除比例: 0.7,
    远距离当前生命移除比例: 0.99,
    眩晕秒: 0.8,
    动画速度: 1.2,
    施法动作原始时长秒: 2.167,
    维持动作原始时长秒: 1.667,
    触发动画编号: 4,
    触发动画原始时长秒: 1.0,
    反击特效路径: "Common\\Effect\\Form\\Shield\\CounterShieldImpact.mdx",
    反击特效持续秒: 0.8,
  },
} as const;

export const 里科特音效配置 = {
  默认裁断距离: 2800,
  四重风刃: {
    跳劈身法掠风: "Sound\\Boss\\Ricote\\SFX\\ricote_quad_windblade_leap_impact_07.mp3",
    四龙卷发射: "Sound\\Boss\\Ricote\\SFX\\ricote_quad_windblade_tornado_x_release_03.mp3",
  },
  追击风刃: {
    发射: "Sound\\Boss\\Ricote\\SFX\\ricote_chasing_windblade_release_01.mp3",
  },
  神风护体: {
    展开: "Sound\\Boss\\Ricote\\SFX\\ricote_divine_wind_shield_open_01.mp3",
    粉碎清算: "Sound\\Boss\\Ricote\\SFX\\ricote_divine_wind_mark_shatter_resolve_02.mp3",
  },
  湮灭之炮: {
    投影锁定: "Sound\\Boss\\Ricote\\SFX\\ricote_annihilation_cannon_projection_lock_02.mp3",
    射线开火: "Sound\\Boss\\Ricote\\SFX\\ricote_annihilation_cannon_beam_fire_01.mp3",
  },
  湮灭之风: {
    风场展开: "Sound\\Boss\\Ricote\\SFX\\ricote_annihilation_wind_field_open_02.mp3",
  },
  破魔反击: {
    窗口开启: "Sound\\Boss\\Ricote\\SFX\\ricote_counter_window_open_04.mp3",
    触发剥离: "Sound\\Boss\\Ricote\\SFX\\ricote_counter_trigger_life_strip_01.mp3",
  },
} as const;
