--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
---
-- @noSelfInFile
____exports["卡瑟拉模型动画配置"] = {
    ["触手攻击"] = {["动画编号"] = 0, ["原始时长秒"] = 2.083, ["循环"] = true},
    ["战斗待机"] = {["动画编号"] = 1, ["原始时长秒"] = 2.223, ["循环"] = true},
    ["行走"] = {["动画编号"] = 2, ["原始时长秒"] = 1.041, ["循环"] = true},
    ["行走变体二"] = {["动画编号"] = 3, ["原始时长秒"] = 1.041, ["循环"] = true},
    ["触手攻击变体二"] = {["动画编号"] = 4, ["原始时长秒"] = 1.943, ["循环"] = true},
    ["待机"] = {["动画编号"] = 5, ["原始时长秒"] = 7.291, ["循环"] = true},
    ["待机变体二"] = {["动画编号"] = 6, ["原始时长秒"] = 7.291, ["循环"] = true},
    ["稳定缓行"] = {["动画编号"] = 7, ["原始时长秒"] = 2.083, ["循环"] = true},
    ["持续施法"] = {["动画编号"] = 8, ["原始时长秒"] = 2.223, ["循环"] = true},
    ["触手内翻蓄力"] = {["动画编号"] = 9, ["原始时长秒"] = 1.388, ["循环"] = true},
    ["触手攻击变体三"] = {["动画编号"] = 10, ["原始时长秒"] = 2.5, ["循环"] = true}
}
____exports["卡瑟拉数值与表现配置"] = {
    ["运行时"] = {["推进间隔毫秒"] = 1000},
    ["阶段阈值"] = {["P2生命比例"] = 0.7, ["P3生命比例"] = 0.5},
    ["深海涡流"] = {
        ["技能槽位"] = "AN00",
        ["动画编号"] = 8,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 2.223,
        ["冷却秒"] = 30,
        ["爆发延迟秒"] = 3,
        ["最大半径"] = 720,
        ["拉力速度"] = 520,
        ["抵抗夹角"] = 55,
        ["抵抗后拉力倍率"] = 0.25,
        ["基础水伤害"] = 4500,
        ["最近伤害系数"] = 1,
        ["最远伤害系数"] = 0.3,
        ["眩晕秒"] = 1,
        ["涡流模型路径"] = "war3mapImported\\WaterTornado.mdx",
        ["涡流特效持续秒"] = 3.2
    },
    ["触手鞭笞"] = {
        ["动画编号"] = 0,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 2.083,
        ["技能槽位"] = "AN01",
        ["冷却秒"] = 20,
        ["延迟秒"] = 2,
        ["触手数量"] = 3,
        ["触手半径"] = 260,
        ["触手持续秒"] = 8,
        ["触手生命值"] = 3000,
        ["触手攻击间隔秒"] = 0.7,
        ["触手攻击半径"] = 220,
        ["触手Boss攻击力比例"] = 0.7,
        ["缠绕减速比例"] = 0.4,
        ["缠绕持续秒"] = 3,
        ["触手模型路径"] = "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
        ["触手缩放"] = 1.4,
        ["触手残片掉落概率"] = 0.45
    },
    ["墨汁喷吐"] = {
        ["动画编号"] = 8,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 2.223,
        ["技能槽位"] = "AT08",
        ["持续秒"] = 6,
        ["残留秒"] = 20,
        ["tick秒"] = 1,
        ["视野降低"] = 1200,
        ["水抗门槛"] = 0.35,
        ["达标效果倍率"] = 0.35,
        ["扇形半径"] = 900,
        ["扇形角度"] = 70,
        ["每秒Boss攻击力比例"] = 0.55,
        ["墨汁残留模型路径"] = "Common\\Effect\\Element\\Water\\InkGroundPoolAnimated.mdx",
        ["墨汁抛射模型路径"] = "Common\\Effect\\Projectile\\Ink Missile.mdx"
    },
    ["深渊召唤"] = {
        ["动画编号"] = 9,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1.388,
        ["触发间隔秒"] = 45,
        ["幼鱿数量"] = 3,
        ["吞噬等待秒"] = 30,
        ["吞噬回血比例"] = 0.1,
        ["幼鱿单位类型"] = "hfoo",
        ["幼鱿模型路径"] = "war3mapImported\\Kraken.mdl",
        ["幼鱿生命值"] = 3500,
        ["幼鱿攻击力"] = 450,
        ["幼鱿缩放"] = 2
    },
    ["高压水炮"] = {
        ["动画编号"] = 9,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1.388,
        ["技能槽位"] = "CT16",
        ["前摇秒"] = 1,
        ["距离"] = 2400,
        ["宽度"] = 200,
        ["Boss攻击力比例"] = 4.5,
        ["路径水花间隔"] = 180,
        ["路径水花模型路径"] = "Objects\\Spawnmodels\\Naga\\NagaDeath\\NagaDeath.mdl",
        ["水抗门槛"] = 0.35,
        ["击退到边缘眩晕秒"] = 1
    },
    ["触手解放"] = {
        ["动画编号"] = 9,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1.388,
        ["触发生命比例"] = 0.5,
        ["触手数量"] = 4,
        ["限时秒"] = 30,
        ["失败回血比例"] = 0.25,
        ["每条破甲比例"] = 0.05,
        ["巨型触手生命值"] = 8000,
        ["巨型触手模型路径"] = "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
        ["巨型触手缩放"] = 2.6,
        ["潜入特效路径"] = "war3mapImported\\WaterTornado.mdx"
    },
    ["共生电击"] = {
        ["动画编号"] = 8,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 2.223,
        ["间隔秒"] = 20,
        ["预警秒"] = 3,
        ["雷伤害"] = 6500,
        ["麻痹秒"] = 3,
        ["安全半径"] = 300,
        ["珊瑚数量"] = 3,
        ["珊瑚距离"] = 620,
        ["珊瑚装饰物ID"] = "YOtf",
        ["珊瑚模型路径"] = "Doodads\\Ruins\\Water\\Coral\\Coral0.mdl",
        ["珊瑚缩放"] = 1.15,
        ["抵消残片数"] = 3,
        ["蓄力特效路径"] = "Common\\Effect\\Element\\Thunder\\ThunderChargeField.mdx",
        ["全屏命中特效路径"] = "Common\\Effect\\Element\\Thunder\\ThunderScreenBurst.mdx",
        ["麻痹命中特效路径"] = "Common\\Effect\\Element\\Thunder\\ThunderParalyzeHit.mdx"
    },
    ["触手残片"] = {
        ["玩家持有上限"] = 5,
        ["水抗加成"] = 0.07,
        ["大于数量时恢复已损生命"] = 2,
        ["已损生命恢复比例"] = 0.2,
        ["Boss吸收间隔秒"] = 30,
        ["Boss每片回血比例"] = 0.02,
        ["精华每层攻击加成"] = 0.03,
        ["精华持续秒"] = 20,
        ["地面模型路径"] = "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
        ["地面模型缩放"] = 0.45,
        ["吸引间隔秒"] = 3,
        ["吸引距离"] = 200,
        ["再生触手生命值"] = 4200,
        ["再生触手攻击间隔秒"] = 1,
        ["再生触手攻击半径"] = 260,
        ["再生触手Boss攻击力比例"] = 0.45,
        ["再生触手吸血比例"] = 0.5,
        ["再生触手持续秒"] = 18
    }
}
____exports["卡瑟拉音效配置"] = {
    ["默认裁断距离"] = 2800,
    ["怪物拟声"] = {
        ["标识"] = "KaselaCreature",
        ["音效路径列表"] = {"Sound\\Boss\\Kasela\\SFX\\kasela_deep_creature_groan_01_80k.mp3", "Sound\\Boss\\Kasela\\SFX\\kasela_deep_creature_groan_02_80k.mp3", "Sound\\Boss\\Kasela\\SFX\\kasela_deep_creature_groan_03_80k.mp3", "Sound\\Boss\\Kasela\\SFX\\kasela_deep_creature_groan_04_80k.mp3"},
        ["冷却Ms"] = 9000,
        ["关键机制触发概率百分比"] = 55,
        ["转阶段触发概率百分比"] = 100
    },
    ["深海涡流"] = {["形成牵引"] = "Sound\\Boss\\Kasela\\SFX\\kasela_deep_vortex_form_pull_02.mp3", ["爆发"] = "Sound\\Boss\\Kasela\\SFX\\kasela_deep_vortex_pressure_blast_02.mp3"},
    ["触手鞭笞"] = {["小触手出现"] = "Sound\\Boss\\Kasela\\SFX\\kasela_tentacle_lash_minions_emerge_02.mp3"},
    ["墨汁喷吐"] = {["主段"] = "Sound\\Boss\\Kasela\\SFX\\kasela_ink_breath_stream_obscure_02.mp3"},
    ["深渊召唤"] = {["幼鱿入场"] = "Sound\\Boss\\Kasela\\SFX\\kasela_abyss_spawn_young_squid_combo_06.mp3"},
    ["高压水炮"] = {["发射"] = "Sound\\Boss\\Kasela\\SFX\\kasela_high_pressure_water_cannon_fire_01.mp3"},
    ["触手解放"] = {["Boss下潜"] = "Sound\\Boss\\Kasela\\SFX\\kasela_tentacle_release_boss_dive_01.mp3", ["巨型触手出水"] = "Sound\\Boss\\Kasela\\SFX\\kasela_giant_tentacles_emerge_phase_start_02.mp3", ["成功破甲"] = "Sound\\Boss\\Kasela\\SFX\\kasela_tentacle_release_success_armor_break_01.mp3", ["失败回血"] = "Sound\\Boss\\Kasela\\SFX\\kasela_tentacle_release_fail_heal_return_02.mp3"},
    ["共生电击"] = {["预警"] = "Sound\\Boss\\Kasela\\SFX\\kasela_symbiotic_shock_charge_warning_05.mp3", ["爆发"] = "Sound\\Boss\\Kasela\\SFX\\kasela_symbiotic_shock_fullscreen_blast_combo_04.mp3"}
}
return ____exports
