/** Global declarations for TSTL / Lua environment */
declare function require(mod: string): any;
declare const pcall: <T>(f: () => T) => [boolean, T | string];
declare const tostring: (v: any) => string;
declare const string: { char: (...codes: number[]) => string; byte: (s: string, i?: number) => number };

interface JassCommon {
  CreateItem: (itemId: number, x: number, y: number) => any;
  UnitAddItemById: (unit: any, itemId: number) => any;
  UnitAddItem: (unit: any, item: any) => boolean;
  CreateGroup: () => any;
  GroupEnumUnitsOfPlayer: (group: any, player: any, filter: any) => void;
  FirstOfGroup: (group: any) => any;
  DestroyGroup: (group: any) => void;
  Filter: (fn: () => boolean) => any;
  GetFilterUnit: () => any;
  IsUnitType: (unit: any, t: number) => boolean;
  UNIT_TYPE_HERO: number;
  TimerGetElapsed: (timer: any) => number;
  IssueTargetOrder: (unit: any, order: string, target: any) => boolean;
  IssueNeutralTargetOrder: (player: any, unit: any, order: string, target: any) => boolean;
  TriggerRegisterTimerEvent: (trig: any, timeout: number, periodic: boolean) => any;
  CreateTimer: () => any;
  TimerStart: (timer: any, timeout: number, periodic: boolean, callback: () => void) => void;
  CreateTrigger: () => any;
  TriggerRegisterPlayerUnitEvent: (trig: any, player: any, event: number, filter: any) => void;
  TriggerRegisterPlayerChatEvent: (trig: any, player: any, msg: string, exact: boolean) => void;
  TriggerAddAction: (trig: any, fn: () => void) => void;
  STES_Register: (trg: any, eventName: string) => void;
  STES_Trigger: (eventName: string) => void;
  GetTriggerPlayer: () => any;
  GetManipulatedItem: () => any;
  GetManipulatingUnit: () => any;
  GetTriggerUnit: () => any;
  GetSelectedUnit: () => any;
  GetOwningPlayer: (unit: any) => any;
  GetItemTypeId: (item: any) => number;
  GetItemCharges: (item: any) => number;
  GetTriggerEventId: () => number;
  ExecuteFunc: (name: string) => void;
  DisplayTimedTextToPlayer: (player: any, x: number, y: number, duration: number, msg: string) => void;
  GetPlayerName: (player: any) => string;
  Player: (index: number) => any;
  QuestMessageBJ: (force: any, messageType: number, msg: string) => void;
  GetPlayersAll: () => any;
  R2S: (r: number) => string;
  bj_QUESTMESSAGE_UPDATED: number;
  EVENT_PLAYER_UNIT_PICKUP_ITEM: number;
  EVENT_PLAYER_UNIT_DROP_ITEM: number;
  EVENT_PLAYER_UNIT_SELECTED: number;
  EVENT_PLAYER_UNIT_DAMAGED: number;
  GetEventDamage: () => number;
  GetEventDamageSource: () => any;
  BlzGetEventDamageTarget: () => any;
  BlzSetEventDamage: (damage: number) => void;
  YDWESyStemAnyUnitDamagedRegistTrigger?: (trg: any) => void;
  YDWEOperatorString3?: (a: string, b: string, c: string) => string;
  YDUserDataGet2?: (type: any, handle: any, name: string, kind: any) => any;
  YDUserDataSet2?: (type: any, handle: any, name: string, kind: any, value: any) => void;
  YDUserDataGet?: (type: string, handle: any, name: string, kind: string) => any;
  YDUserDataHas?: (type: string, handle: any, name: string, kind: string) => boolean;
  OperatorRealAdd?: (a: number, b: number) => number;
  OperatorRealSubtract?: (a: number, b: number) => number;
  OperatorRealMultiply?: (a: number, b: number) => number;
  OperatorRealDivide?: (a: number, b: number) => number;
  YDLocal1Set?: (ty: string, key: string, val: any) => void;
  YDLocal1Get?: (ty: string, key: string) => any;
  YDLocal1Release?: () => void;
  YDLocal2Set?: (ty: string, key: string, val: any) => void;
  YDLocal2Get?: (ty: string, key: string) => any;
  YDLocalInitialize?: () => void;
  YDWEIsEventDamageType?: (t: number) => boolean;
  YDWEIsEventAttackType?: (t: number) => boolean;
  YDWEIsEventAttackDamage?: () => boolean;
  YDWEIsEventPhysicalDamage?: () => boolean;
  YDWESetEventDamage?: (dmg: number) => void;
  YDWETimerDestroyTextTag?: (dur: number, tt: any) => void;
  YDWETimerDestroyEffect?: (dur: number, e: any) => void;
  MNAnyUnitDamaged?: (trg: any, interval: number) => void;
  Condition?: (fn: () => boolean) => any;
  TriggerAddCondition?: (trg: any, cond: any) => void;
  ConvertUnitState?: (i: number) => number;
  CreateTextTagLocBJ?: (s: string, loc: any, size: number, red: number, green: number, blue: number, trans: number) => any;
  SetTextTagVelocity?: (tt: any, speed: number, angle: number) => void;
  GetUnitLoc?: (u: any) => any;
  RemoveLocation?: (loc: any) => void;
  SetUnitLifeBJ?: (u: any, hp: number) => void;
  ForGroupBJ?: (g: any, fn: () => void) => void;
  GetEnumUnit?: () => any;
  UnitHasItemOfTypeBJ?: (u: any, itemId: number) => boolean;
  AddSpecialEffectTarget?: (model: string, u: any, attach: string) => any;
  IsUnitInGroup?: (u: any, g: any) => boolean;
  IsPlayerInForce?: (p: any, f: any) => boolean;
  IsUnitRace?: (u: any, r: number) => boolean;
  GetUnitState?: (u: any, state: number) => number;
  SetUnitState?: (u: any, state: number, val: number) => void;
  RACE_DEMON: number;
  UNIT_TYPE_SUMMONED: number;
  UNIT_TYPE_ANCIENT: number;
  UNIT_STATE_LIFE: number;
  UNIT_STATE_MANA: number;
  DAMAGE_TYPE_MIND: number;
  DAMAGE_TYPE_NORMAL: number;
  DAMAGE_TYPE_ENHANCED: number;
  DAMAGE_TYPE_SLOW_POISON: number;
  DAMAGE_TYPE_POISON: number;
  DAMAGE_TYPE_ACID: number;
  DAMAGE_TYPE_PLANT: number;
  DAMAGE_TYPE_COLD: number;
  DAMAGE_TYPE_FIRE: number;
  DAMAGE_TYPE_LIGHTNING: number;
  DAMAGE_TYPE_DIVINE: number;
  DAMAGE_TYPE_SHADOW_STRIKE: number;
  ATTACK_TYPE_NORMAL: number;
  WEAPON_TYPE_WHOKNOWS: number;
  PLAYER_NEUTRAL_AGGRESSIVE: number;
  Cya_Attribute_SetState?: (unit: any, id: number, i: number, v: number) => void;
  GetUnitName: (unit: any) => string;
}

/** blizzard.j 封装接口（jass.blizzard 模块） */
interface BlizzardJass {
  TriggerRegisterTimerEventSingle: (trig: any, timeout: number) => any;
  TriggerRegisterTimerEventPeriodic: (trig: any, timeout: number) => any;
  jass: JassCommon;
}

/** Lua global print - variadic */
declare var print: (...args: any[]) => void;

/** Lua math / os */
declare const math: { random: () => number; randomseed: (seed: number) => void; floor: (n: number) => number };
declare const os: { clock: () => number };
