-- Elite sludge creature on the polluted-water route.

local sludgeBerserker = UnitDefinition:new('n07D', 'n04X')
sludgeBerserker:setName('腐淤狂战士')
sludgeBerserker:setTooltipBasic('腐淤狂战士')
sludgeBerserker:setTooltipExtended('吞噬树魔狂战士残骸后形成的污染精英，基础强度提高15%。')
sludgeBerserker:setDescription('吞噬树魔狂战士残骸后形成的污染精英，基础强度提高15%。')
sludgeBerserker:setIconGameInterface('Unit\\Elite\\Icon\\mia_sludge_berserker.blp')
sludgeBerserker:setModelFile('units\\creeps\\SludgeMonster\\SludgeMonster.mdl')
sludgeBerserker:setModelFileExtraVersions('0')
sludgeBerserker:setScalingValue(2.0)
sludgeBerserker:setLevel(29)
sludgeBerserker:setHitPointsMaximumBase(19320)
sludgeBerserker:setHitPointsRegenerationType('always')
sludgeBerserker:setHitPointsRegenerationRate(154.56)
sludgeBerserker:setDefenseBase(40)
sludgeBerserker:setAttack1DamageBase(3795)
sludgeBerserker:setGoldBountyAwardedBase(1667)
sludgeBerserker:setUpgradesUsed('R001,R002')
sludgeBerserker:setCanFlee(false)
sludgeBerserker:setDisplayasNeutralHostile(true)
sludgeBerserker:setCanDropItemsOnDeath(true)
