-- Elite wave units for the seal defense encounter.

local function createSealGuardElite(id, name, options)
  options.name = name
  options.upgrades = 'R001,R002'
  options.defense = 35
  options.classification = ''
  return createSealGuardUnit(id, options.parentId, options)
end

createSealGuardElite('n069', '黑暗残响', {
  parentId = 'nban',
  description = '在守卫战后方骚扰玩家并压制封印核心的暗影核心。',
  level = 30,
  modelFile = 'Unit\\Elite\\DarkEcho\\VoidWalker.mdx',
  icon = 'Unit\\Elite\\Icon\\DarkEcho.blp',
  scale = 2.50,
  hp = 9000,
  hpRegen = 90.0,
  mana = 1000,
  manaRegen = 10.0,
  speed = 300,
  collision = 24.0,
  acquire = 1100.0,
  pointValue = 220,
  bounty = 0,
  damage = 1500,
  attackCooldown = 2.30,
  attackRange = 900,
  rangeBuffer = 300.0,
  attackTargets = 'ground,air,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Magic,
  weaponType = WeaponType.Missile,
  weaponSound = WeaponSound.Nothing,
  projectileArt = 'Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl',
  projectileSpeed = 1000,
  projectileArc = 0.12,
  projectileHoming = true,
  projectileLaunchZ = 120.0,
  projectileImpactZ = 60.0,
  attackBackswing = 0.60,
  attackDamagePoint = 0.50,
})

createSealGuardElite('n06E', '裂誓重卫', {
  parentId = 'nban',
  description = '以厚重残铠保护后排并向封印核心推进的裂誓重卫。',
  level = 30,
  modelFile = 'Unit\\Elite\\OathRivenBulwark\\Hero_Garithos.mdx',
  icon = 'Unit\\Elite\\Icon\\OathRivenBulwark.blp',
  scale = 1.80,
  hp = 14500,
  hpRegen = 145.0,
  speed = 280,
  collision = 40.0,
  acquire = 850.0,
  pointValue = 260,
  bounty = 0,
  damage = 1800,
  attackCooldown = 2.50,
  attackRange = 150,
  rangeBuffer = 250.0,
  attackTargets = 'ground,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Normal,
  weaponType = WeaponType.Normal,
  weaponSound = WeaponSound.MetalHeavyChop,
  attackBackswing = 0.55,
  attackDamagePoint = 0.45,
})

createSealGuardElite('n06F', '失律号令者', {
  parentId = 'nw2w',
  description = '在后排释放号令脉冲、强化附近守卫战单位的失律号令者。',
  level = 30,
  modelFile = 'Unit\\Elite\\DiscordHerald\\BrokenMale.mdx',
  icon = 'Unit\\Elite\\Icon\\DiscordHerald.blp',
  scale = 2.30,
  hp = 8500,
  hpRegen = 85.0,
  mana = 1200,
  manaRegen = 12.0,
  speed = 300,
  collision = 24.0,
  acquire = 900.0,
  pointValue = 240,
  bounty = 0,
  damage = 1100,
  attackCooldown = 2.20,
  attackRange = 700,
  rangeBuffer = 250.0,
  attackTargets = 'ground,air,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Magic,
  weaponType = WeaponType.Missile,
  weaponSound = WeaponSound.Nothing,
  projectileArt = 'Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl',
  projectileSpeed = 900,
  projectileArc = 0.15,
  projectileHoming = true,
  projectileLaunchZ = 100.0,
  projectileImpactZ = 60.0,
  attackBackswing = 0.60,
  attackDamagePoint = 0.50,
})
