-- Chapter 3 main boss: Balzaroth.
-- Reuses the historical Lava Demon King raw id N03G.

createMeleeBossHeroUnit('N03G', '熔岩恶魔王·巴尔扎罗斯', {
  modelFile = 'Boss\\Balzaroth\\Balzaroth.mdx',
  icon = 'Boss\\Balzaroth\\Balzaroth.blp',
  properNames = '熔岩恶魔王·巴尔扎罗斯',
  tooltipBasic = '熔岩恶魔王·巴尔扎罗斯',
  tooltipExtended = '熔岩恶魔王·巴尔扎罗斯',
  description = '熔岩恶魔王·巴尔扎罗斯',

  level = 40,
  hp = 42000,
  mana = 2000,
  initialMana = 2000,
  manaRegen = 25.0,
  speed = 400,
  turnRate = 0.6,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 2000,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 1.0,
  attackType = AttackType.Chaos,
  weaponType = WeaponType.Instant,
  defense = 25,
  hpRegen = 336.0,
  scale = 5.0,
  collision = 64.0,
  soundSet = 'Infernal',
  classification = 'undead',
  abilities = 'AInv,A0C9,A0CC,A0CA,A0CB',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 4000,
  lumberBountyBase = 3,
  pointValue = 400,
})
