-- Mechanic units for Phoenixel.

local function createPhoenixelMechanicUnit(id, name, modelFile, icon, hp, scale, height, selectionScale)
  local unit = UnitDefinition:new(id, 'ewsp')
  unit:setName(name)
  unit:setTooltipBasic(name)
  unit:setTooltipExtended(name)
  unit:setDescription(name)
  unit:setModelFile(modelFile)
  unit:setModelFileExtraVersions('0')
  unit:setIconGameInterface(icon or 'ReplaceableTextures\\CommandButtons\\BTNOrbOfFire.blp')
  unit:setNormalAbilities('')
  unit:setUnitClassification('')
  unit:setMovementType(MovementType.Foot)
  unit:setMovementHeightMinimum(0.0)
  unit:setMovementHeight(height or 0.0)
  unit:setSpeedBase(1)
  unit:setSpeedMinimum(0)
  unit:setSpeedMaximum(0)
  unit:setCollisionSize(32.0)
  unit:setSelectionScale(selectionScale or 1.2)
  unit:setSightRadiusDay(900)
  unit:setSightRadiusNight(900)
  unit:setHitPointsMaximumBase(hp or 1000)
  unit:setHitPointsRegenerationType('always')
  unit:setHitPointsRegenerationRate(0.0)
  unit:setManaMaximum(0)
  unit:setManaInitialAmount(0)
  unit:setManaRegeneration(0.0)
  unit:setAttacksEnabled(AttacksEnabled.AttackOneOnly)
  unit:setAttack1TargetsAllowed('')
  unit:setAttack1DamageBase(0)
  unit:setAttack1DamageNumberofDice(1)
  unit:setAttack1DamageSidesperDie(0)
  unit:setAttack1CooldownTime(99.0)
  unit:setAttack1Range(0)
  unit:setDefenseBase(10)
  unit:setArmorType(ArmorType.Normal)
  unit:setCanFlee(false)
  unit:setScalingValue(scale or 1.0)
  unit:setFoodCost(0)
  unit:setFoodProduced(0)
  unit:setGoldCost(0)
  unit:setLumberCost(0)
  unit:setGoldBountyAwardedBase(0)
  unit:setGoldBountyAwardedNumberofDice(0)
  unit:setGoldBountyAwardedSidesperDie(0)
  unit:setLumberBountyAwardedBase(0)
  unit:setLumberBountyAwardedNumberofDice(0)
  unit:setLumberBountyAwardedSidesperDie(0)
  return unit
end

createPhoenixelMechanicUnit('N0P0', '永恒冰核', 'Common\\Effect\\Element\\Ice\\Ice_egg.mdx', 'ReplaceableTextures\\CommandButtons\\BTNFrost.blp', 99999, 1.6, 80.0, 1.6)
createPhoenixelMechanicUnit('N0P1', '能量导管', 'Common\\Effect\\Element\\Ice\\FrozenMana.mdx', 'ReplaceableTextures\\CommandButtons\\BTNCrystalBall.blp', 5000, 1.1, 60.0, 1.3)
createPhoenixelMechanicUnit('N0P2', '怨火核心', 'Common\\Effect\\Element\\Fire\\Burning Core.mdx', 'ReplaceableTextures\\CommandButtons\\BTNOrbOfFire.blp', 7000, 1.2, 120.0, 1.5)
createPhoenixelMechanicUnit('N0P3', '凤凰之卵', 'Boss\\Phoenixel\\HolyPhoenix.mdx', 'Boss\\Phoenixel\\Phoenixel.blp', 3000, 1.0, 80.0, 1.4)
