-- Chapter 2 main boss 1: Tree Lord.

createMeleeBossHeroUnit('N05S', '树魔首领', {
  modelFile = 'Boss\\TreeLord\\TreeLord.mdx',
  icon = 'Boss\\TreeLord\\TreeLord.blp',
  properNames = '凯金',
  tooltipBasic = '树魔首领',
  tooltipExtended = '树魔首领',
  description = '树魔首领',

  level = 30,
  hp = 36000,
  mana = 1000,
  initialMana = 1000,
  manaRegen = 5.0,
  speed = 372,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 1500,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 1.35,
  attackType = AttackType.Chaos,
  weaponType = WeaponType.Instant,
  defense = 25,
  hpRegen = 270.0,
  scale = 2.5,
  soundSet = 'ForestTroll',
  classification = 'undead',
  abilities = 'AInv,A0LL,A0LN,A0LM,AN00',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 2500,
  lumberBountyBase = 1,
  pointValue = 300,
})
