-- Chapter 2 main boss 2: Felice.

createMeleeBossHeroUnit('N05T', '菲利斯', {
  modelFile = 'Boss\\Felice\\Felice.mdx',
  icon = 'Boss\\Felice\\Felice.blp',
  properNames = '分离军团长',
  tooltipBasic = '菲利斯',
  tooltipExtended = '菲利斯',
  description = '菲利斯',

  level = 30,
  hp = 20800,
  mana = 10000,
  initialMana = 99999,
  manaRegen = 5.0,
  speed = 400,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 1120,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 1.1,
  attackType = AttackType.Normal,
  weaponType = WeaponType.Instant,
  defense = 25,
  hpRegen = 208.0,
  scale = 2.65,
  soundSet = 'Arthas',
  classification = 'undead',
  abilities = 'AInv,AT15,BT15,CT15',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 3000,
  lumberBountyBase = 1,
  pointValue = 330,
})
