-- Chapter 2 main boss 3: Ricote.

createMeleeBossHeroUnit('N05U', '里科特', {
  modelFile = 'Boss\\Ricote\\Ricote.mdx',
  icon = 'Boss\\Ricote\\Ricote.blp',
  properNames = '原精灵王子',
  tooltipBasic = '里科特',
  tooltipExtended = '里科特',
  description = '里科特',

  level = 30,
  hp = 48000,
  mana = 1000,
  initialMana = 99999,
  manaRegen = 5.0,
  speed = 400,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 1900,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 1.15,
  attackType = AttackType.Normal,
  weaponType = WeaponType.Instant,
  defense = 25,
  hpRegen = 360.0,
  scale = 2.0,
  soundSet = 'Arthas',
  classification = 'undead',
  abilities = 'AInv,AT04,AT09,AN00,AN01,AN02,AN03',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 3500,
  lumberBountyBase = 1,
  pointValue = 360,
})
