-- Chapter 4 mainline boss: Masked Man stances.

local maskedManScholar = createRangedBossHeroUnit('N05M', '|cffcc99ff蒙面人|r', {
  modelFile = 'Boss\\MaskedMan\\Teron.mdx',
  icon = 'ReplaceableTextures\\CommandButtons\\BTNAcolyte.blp',
  editorSuffix = '学者姿态',
  properNames = '教派学者',
  tooltipBasic = '|cffcc99ff蒙面人|r',
  tooltipExtended = '|cffcc99ff蒙面人|r',
  description = '|cffcc99ff蒙面人|r',

  level = 30,
  hp = 12000,
  mana = 300,
  initialMana = 300,
  manaRegen = 5.0,
  speed = 362,
  strength = 1,
  agility = 1,
  intelligence = 1,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 800,
  attackCooldown = 4.0,
  attackType = AttackType.Magic,
  weaponType = WeaponType.Instant,
  projectileArt = '.mdl',
  projectileSpeed = 2000,
  defense = 25,
  hpRegen = 96.0,
  scale = 2.5,
  regenType = 'always',
  abilities = 'AT08,AN00,AN01,AN02,AInv',
  upgrades = 'R001,R002',
  acquire = 1000.0,
  sightNight = 1400,
  goldBountyBase = 500,
})
maskedManScholar:setIconScoreScreen('ReplaceableTextures\\CommandButtons\\BTNAcolyte.blp')

local maskedManSwordsman = createMeleeBossHeroUnit('N05N', '|cffcc99ff蒙面人|r', {
  modelFile = 'Boss\\MaskedMan\\HeroUndeadMaster.mdx',
  icon = 'Boss\\MaskedMan\\Icon\\MaskedMan_Swordsman.blp',
  editorSuffix = '剑士姿态',
  properNames = '教派剑士',
  tooltipBasic = '|cffcc99ff蒙面人|r',
  tooltipExtended = '|cffcc99ff蒙面人|r',
  description = '|cffcc99ff蒙面人|r',

  level = 30,
  hp = 14000,
  mana = 100,
  initialMana = 0,
  manaRegen = 2.0,
  speed = 382,
  strength = 1,
  agility = 1,
  intelligence = 1,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 750,
  attackCooldown = 1.5,
  attackType = AttackType.Normal,
  defense = 25,
  hpRegen = 112.0,
  scale = 2.6,
  abilities = 'A0L7,A0L6,A0L8,A0L5,AInv',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 500,
})
maskedManSwordsman:setIconScoreScreen('Boss\\MaskedMan\\Icon\\MaskedMan_Swordsman.blp')
maskedManSwordsman:setAttack1WeaponSound(WeaponSound.MetalHeavySlice)
maskedManSwordsman:setLumberBountyAwardedBase(1)
