-- Mainline Boss object data entry.

dofile('Boss/HeroBoss/01-MainlineBoss/01-Thranduil.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/03-BalzarothAbilities.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/03-Balzaroth.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/03-BalzarothMechanicUnits.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/04-PhoenixelAbilities.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/04-Phoenixel.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/04-PhoenixelMechanicUnits.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/05-TreeLord.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/06-Felice.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/07-Ricote.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/11-SleepingHeroAronkos.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/12-Ogre.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/13-LirBert.lua')
dofile('Boss/HeroBoss/01-MainlineBoss/14-MaskedMan.lua')
