--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
---
-- @noSelfInFile
____exports["菲尼克斯尔数值与表现配置"] = {
    ["基础属性"] = {["生命值"] = 55000, ["攻击力"] = 2500, ["护甲"] = 30, ["移动速度"] = 322},
    ["动画"] = {["第一形态"] = {
        ["待机"] = {["编号"] = 0, ["倍速"] = 1},
        ["普攻"] = {["编号"] = 5, ["倍速"] = 1},
        ["振翅"] = {["编号"] = 6, ["倍速"] = 1},
        ["蓄力张口"] = {["编号"] = 7, ["倍速"] = 1, ["出手时点秒"] = 0.45},
        ["漩涡施法"] = {["编号"] = 8, ["倍速"] = 1},
        ["重生死亡"] = {["编号"] = 9, ["倍速"] = 1}
    }, ["第二形态"] = {
        ["待机"] = {["编号"] = 0, ["倍速"] = 1},
        ["弹幕解体"] = {["编号"] = 6, ["倍速"] = 1},
        ["哀鸣引导"] = {["编号"] = 5, ["倍速"] = 1},
        ["常规施法"] = {["编号"] = 3, ["倍速"] = 1},
        ["轮回死亡"] = {["编号"] = 6, ["倍速"] = 1},
        ["凤凰蛋"] = {["编号"] = 11, ["倍速"] = 1, ["附加动画属性"] = "alternate", ["守护间隔秒"] = 0.5}
    }},
    ["机制"] = {
        ["导管数量"] = 4,
        ["导管生命Boss最大生命比例"] = 0.07,
        ["每根导管承伤提高"] = 0.08,
        ["每根导管技能强度提高"] = 0.06,
        ["怨火核心生命Boss最大生命比例"] = 0.1,
        ["怨火核心周期暴露秒"] = 28,
        ["怨火核心暴露持续秒"] = 8,
        ["怨火核心暴露承伤提高"] = 2,
        ["怨火核心摧毁Boss最大生命伤害比例"] = 0.08,
        ["元素层数上限"] = 6,
        ["元素脱离衰减等待秒"] = 5,
        ["永恒轮回触发生命比例"] = 0.05,
        ["永恒轮回引导秒"] = 15,
        ["凤凰蛋生命Boss最大生命比例"] = 0.05,
        ["每枚存活凤凰蛋回血Boss最大生命比例"] = 0.12,
        ["轮回失败全场伤害目标最大生命比例"] = 0.2,
        ["轮回失败全场伤害Boss攻击力比例"] = 1.5
    },
    ["炽羽散射"] = {
        ["读条秒"] = 0.7,
        ["羽毛数量"] = 14,
        ["扩散半径"] = 520,
        ["落点半径"] = 150,
        ["燃烧区半径"] = 180,
        ["燃烧区持续秒"] = 5,
        ["燃烧Tick秒"] = 1,
        ["羽毛伤害Boss攻击力比例"] = 0.95,
        ["羽毛伤害目标最大生命比例"] = 0.02,
        ["燃烧Tick目标最大生命比例"] = 0.008,
        ["火印层数"] = 1,
        ["吟唱条颜色ID"] = 1,
        ["吟唱条标题文本"] = "菲尼克斯尔正在散射炽焰羽毛！",
        ["吟唱条提示文本"] = "离开羽毛落点和燃烧区"
    },
    ["熔岩吐息"] = {
        ["预警秒"] = 0.45,
        ["持续秒"] = 2.5,
        ["Tick秒"] = 0.5,
        ["转向间隔秒"] = 0.2,
        ["半径"] = 720,
        ["角度"] = 70,
        ["伤害Boss攻击力比例"] = 0.45,
        ["伤害目标最大生命比例"] = 0.012,
        ["火印层数"] = 1,
        ["减速命中次数"] = 3,
        ["减速比例"] = 0.25,
        ["减速持续秒"] = 2,
        ["吟唱条颜色ID"] = 1,
        ["吟唱条标题文本"] = "菲尼克斯尔正在蓄力熔岩吐息！",
        ["吟唱条提示文本"] = "离开正面扇形"
    },
    ["凤凰漩涡"] = {
        ["预警秒"] = 2,
        ["持续秒"] = 4,
        ["Tick秒"] = 0.5,
        ["半径"] = 420,
        ["中心半径"] = 140,
        ["牵引Tick毫秒"] = 100,
        ["牵引距离"] = 18,
        ["伤害Boss攻击力比例"] = 0.35,
        ["伤害目标已损失生命比例"] = 0.04,
        ["火印层数"] = 1,
        ["吟唱条颜色ID"] = 1,
        ["吟唱条标题文本"] = "凤凰漩涡正在形成！",
        ["吟唱条提示文本"] = "离开锁定位置"
    },
    ["骸骨弹幕"] = {
        ["读条秒"] = 1,
        ["波次数"] = 3,
        ["每波数量"] = 14,
        ["波次间隔秒"] = 0.8,
        ["半径"] = 950,
        ["伤害Boss攻击力比例"] = 1.1,
        ["伤害目标最大生命比例"] = 0.03,
        ["怨火层数"] = 1,
        ["吟唱条颜色ID"] = 3,
        ["吟唱条标题文本"] = "骸骨烈焰即将齐射！",
        ["吟唱条提示文本"] = "观察弹幕空隙移动"
    },
    ["怨火链接"] = {
        ["预警秒"] = 0.8,
        ["持续秒"] = 8,
        ["断链距离"] = 850,
        ["线宽"] = 90,
        ["Tick秒"] = 0.5,
        ["穿线伤害Boss攻击力比例"] = 0.4,
        ["穿线伤害目标最大生命比例"] = 0.015,
        ["断链伤害目标已损失生命比例"] = 0.18,
        ["断链伤害Boss攻击力比例"] = 1.2,
        ["怨火层数"] = 1,
        ["吟唱条颜色ID"] = 1,
        ["吟唱条标题文本"] = "怨火正在连接目标！",
        ["吟唱条提示文本"] = "注意连线，不要穿线"
    },
    ["凤凰挽歌"] = {
        ["引导秒"] = 6,
        ["Tick秒"] = 1,
        ["安全区半径"] = 260,
        ["当前生命损失比例"] = 0.1,
        ["规避叠层"] = 1,
        ["吟唱条颜色ID"] = 3,
        ["吟唱条标题文本"] = "菲尼克斯尔正在唱响凤凰挽歌！",
        ["吟唱条提示文本"] = "进入安全法阵规避本跳伤害"
    },
    ["元素爆发"] = {
        ["周期秒"] = 18,
        ["火伤害Boss攻击力比例"] = 1.2,
        ["火伤害目标最大生命比例"] = 0.05,
        ["冰伤害Boss攻击力比例"] = 0.8,
        ["冰伤害目标最大生命比例"] = 0.03,
        ["毒伤害目标已损失生命比例"] = 0.2,
        ["暗伤害Boss攻击力比例"] = 1.5,
        ["暗伤害目标最大生命比例"] = 0.04,
        ["结算后最高层降低"] = 2,
        ["吟唱条颜色ID"] = 2,
        ["吟唱条标题文本"] = "元素爆发即将触发！",
        ["吟唱条提示文本"] = "最高层元素决定惩罚"
    },
    ["特效"] = {
        ["导管死亡"] = "Common\\Effect\\Element\\Ice\\FrostNova (2).mdx",
        ["冰核破碎A"] = "Common\\Effect\\Element\\Ice\\dead spirit by deckai.mdx",
        ["冰核破碎B"] = "Common\\Effect\\Element\\Ice\\FrostNova (2).mdx",
        ["形态转换"] = "Common\\Effect\\Element\\Fire\\file_002469.mdx",
        ["羽毛弹体"] = "Common\\Effect\\Projectile\\FireArrow.mdx",
        ["燃烧区"] = "Common\\Effect\\Element\\Fire\\Fire2.mdx",
        ["吐息"] = "Abilities\\Spells\\Other\\BreathOfFire\\BreathOfFireMissile.mdl",
        ["漩涡"] = "war3mapImported\\xuanwo.mdx",
        ["骨羽"] = "Abilities\\Weapons\\SerpentWardMissile\\SerpentWardMissile.mdl",
        ["凤凰挽歌主体"] = "Common\\Effect\\Form\\MagicCircle\\Channeling (2).mdx",
        ["凤凰挽歌叠加"] = "Common\\Effect\\Element\\Fantasy\\file_002480.mdx",
        ["凤凰挽歌安全区"] = "Common\\Effect\\Form\\MagicCircle\\Aura.mdx",
        ["元素爆发火"] = "Common\\Effect\\Element\\Fire\\file_002462.mdx",
        ["元素爆发冰"] = "Common\\Effect\\Element\\Ice\\Shiva'sWrath.mdx",
        ["元素爆发毒"] = "Common\\Effect\\Element\\poison\\ForestBolt.mdx",
        ["元素爆发暗"] = "Common\\Effect\\Element\\Dark\\dark001.mdx",
        ["核心暴露"] = "Common\\Effect\\Element\\Fantasy\\file_002461.mdx",
        ["永恒轮回收拢"] = "Common\\Effect\\Element\\Fantasy\\file_002391.mdx",
        ["永恒轮回能量上升"] = "Common\\Effect\\Element\\Fantasy\\file_002409.mdx",
        ["永恒轮回星屑残留"] = "Common\\Effect\\Element\\Fantasy\\file_002501.mdx"
    },
    ["闪电"] = {["冰核导管推荐效果代码"] = "BLSB"}
}
____exports["菲尼克斯尔音效配置"] = {
    ["默认裁断距离"] = 2800,
    ["转第二形态"] = {["冰核破碎重生"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_phase2_ice_core_shatter_rebirth_02.mp3"},
    ["导管死亡"] = {["小封印破口"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_conduit_seal_break_01.mp3"},
    ["熔岩吐息"] = {["张口蓄力"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_lava_breath_charge_start_01.mp3", ["持续喷吐"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_lava_breath_stream_02.mp3", ["持续喷吐延迟Ms"] = 450},
    ["凤凰漩涡"] = {["形成牵引"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_phoenix_vortex_form_02_80k.mp3"},
    ["骸骨弹幕"] = {["起手层"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_bonefire_barrage_start_02.mp3", ["飞射层"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_bonefire_barrage_start_05.mp3", ["飞射层延迟Ms"] = 300},
    ["怨火链接"] = {["链接生成"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_resentfire_link_bind_02.mp3"},
    ["凤凰挽歌"] = {["引导开始"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_phoenix_lament_channel_combo_05.mp3"},
    ["怨火核心"] = {["暴露"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_resentfire_core_expose_01.mp3"},
    ["永恒轮回"] = {["开始"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_eternal_cycle_start_eggs_02_64k.mp3", ["凤凰蛋摧毁"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_eternal_cycle_egg_break_combo_12.mp3", ["失败结算"] = "Sound\\Boss\\Phoenixel\\SFX\\phoenixel_eternal_cycle_fail_rebirth_blast_02.mp3"}
}
return ____exports
