-- Quest-only story items. These are not regular equipment rewards.

createEquipmentItem('I0ES', '残缺的魔法信件', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\QuestItem\\broken_magic_letter.blp',
  model = 'Objects\\InventoryItems\\tome\\tome.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n树魔首领死亡后凝成的残缺魔法信件。|n|cFF808080信纸上残留着分离教派的加密术式，必须带回王城交给克林姆德王确认。|r',
  description = '|cffffffcc[任务物品]|r|n树魔首领死亡后凝成的残缺魔法信件。|n|cFF808080信纸上残留着分离教派的加密术式，必须带回王城交给克林姆德王确认。|r',
})

createEquipmentItem('I0G9', '火灵核心', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\Item\\vengeful_fire_core_shard.blp',
  model = 'Objects\\InventoryItems\\CrystalShard\\CrystalShard.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n击败熔岩恶魔后凝结的火灵核心。|n|cFF808080嵌入古老熔核封印后会燃尽自身，暂时压制熔岩恶魔王的再生。|r',
  description = '|cffffffcc[任务物品]|r|n击败熔岩恶魔后凝结的火灵核心。|n|cFF808080嵌入古老熔核封印后会燃尽自身，暂时压制熔岩恶魔王的再生。|r',
})

createEquipmentItem('I0JX', '迟到的熔火酒', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\QuestItem\\late_molten_wine.blp',
  model = 'Equipment\\Model\\QuestItem\\BrownCup.mdx',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n酒窖管事托付的一壶熔火酒。|n|cFF808080瓶口封着厚重红蜡，必须趁热送到恶魔城外巡卫手中。|r',
  description = '|cffffffcc[任务物品]|r|n酒窖管事托付的一壶熔火酒。|n|cFF808080瓶口封着厚重红蜡，必须趁热送到恶魔城外巡卫手中。|r',
})

createEquipmentItem('I0JY', '遗失的仪式角饰', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\QuestItem\\lost_ritual_horn.blp',
  model = 'Objects\\InventoryItems\\CrystalShard\\CrystalShard.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n年轻恶魔成年仪式上必须佩戴的黑银角饰。|n|cFF808080表面留着恶魔犬的齿痕，好在核心刻纹没有受损。|r',
  description = '|cffffffcc[任务物品]|r|n年轻恶魔成年仪式上必须佩戴的黑银角饰。|n|cFF808080表面留着恶魔犬的齿痕，好在核心刻纹没有受损。|r',
})

createEquipmentItem('I0JZ', '王族旧誓印', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\QuestItem\\royal_old_oath_seal.blp',
  model = 'Objects\\InventoryItems\\tome\\tome.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n从旧墓门誓约标志下取出的王族印记。|n|cFF808080冰冷刻纹仍在低声重复守陵人的古老誓词。|r',
  description = '|cffffffcc[任务物品]|r|n从旧墓门誓约标志下取出的王族印记。|n|cFF808080冰冷刻纹仍在低声重复守陵人的古老誓词。|r',
})

createEquipmentItem('I0K0', '余焰采样器', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\QuestItem\\ember_sampling_vessel.blp',
  model = 'Objects\\InventoryItems\\CrystalShard\\CrystalShard.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n熔灵工匠制作的耐高温采样容器。|n|cFF808080需要依次记录四处余焰的温度与脉动，才能压出稳定样本。|r',
  description = '|cffffffcc[任务物品]|r|n熔灵工匠制作的耐高温采样容器。|n|cFF808080需要依次记录四处余焰的温度与脉动，才能压出稳定样本。|r',
})

createEquipmentItem('I0K1', '稳定余焰样本', {
  baseId = 'ratf',
  icon = 'Equipment\\Icon\\QuestItem\\stable_ember_sample.blp',
  model = 'Objects\\InventoryItems\\CrystalShard\\CrystalShard.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[任务物品]|r|n由四处熔核余焰共同压成的稳定样本。|n|cFF808080离开熔灵核心后仍保持固定脉动，可交给熔灵工匠重铸炉心。|r',
  description = '|cffffffcc[任务物品]|r|n由四处熔核余焰共同压成的稳定样本。|n|cFF808080离开熔灵核心后仍保持固定脉动，可交给熔灵工匠重铸炉心。|r',
})

createEquipmentItem('I0KE', '守誓圣铠合成书', {
  baseId = 'azhr',
  icon = 'Equipment\\Icon\\QuestItem\\oath_armor_recipe_book.blp',
  model = 'war3mapImported\\SpellBook.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[合成书]|r|n收录守誓圣铠的锻造图谱。|n|cffffcc99集齐：高原战衣、月纹熊革×3、古树韧藤×2 与本书，即会自动合成。|r|n|cFF808080圣地石匣里的锻造图谱，纸页浸过圣水却不晕墨——誓约比纸更耐久。|r',
  description = '|cffffffcc[合成书]|r|n收录守誓圣铠的锻造图谱。|n|cffffcc99集齐：高原战衣、月纹熊革×3、古树韧藤×2 与本书，即会自动合成。|r|n|cFF808080圣地石匣里的锻造图谱，纸页浸过圣水却不晕墨——誓约比纸更耐久。|r',
})

createEquipmentItem('I0KG', '熔渊坠饰合成书', {
  baseId = 'azhr',
  icon = 'Equipment\\Icon\\QuestItem\\abyss_pendant_recipe_book.blp',
  model = 'war3mapImported\\SpellBook.mdl',
  abilities = ' ',
  classification = 'Charged',
  level = 1,
  charges = 1,
  priority = 50,
  goldCost = 0,
  canBeDropped = true,
  canBeSoldByMerchants = false,
  canBeSoldToMerchants = false,
  tooltipExtended = '|cffffffcc[合成书]|r|n收录熔渊坠饰的重铸法。|n|cffffcc99集齐：夜行教团坠饰、恶魔锻火结晶、恶魔结晶×2、炽热能量×2 与本书，即会自动合成。|r|n|cFF808080宝藏深处的手抄本，墨迹用的是凝干的魔血。|r',
  description = '|cffffffcc[合成书]|r|n收录熔渊坠饰的重铸法。|n|cffffcc99集齐：夜行教团坠饰、恶魔锻火结晶、恶魔结晶×2、炽热能量×2 与本书，即会自动合成。|r|n|cFF808080宝藏深处的手抄本，墨迹用的是凝干的魔血。|r',
})