-- Chapter 3 main boss: Phoenixel.
-- Reuses the historical Undying Phoenix raw id N00U.

createRangedBossHeroUnit('N00U', '不死火鸟·菲尼克斯', {
  modelFile = 'war3mapImported\\Alisrazor.mdl',
  icon = 'Boss\\Phoenixel\\Phoenixel.blp',
  properNames = '不死火鸟·菲尼克斯',
  tooltipBasic = '不死火鸟·菲尼克斯',
  tooltipExtended = '不死火鸟·菲尼克斯',
  description = '不死火鸟·菲尼克斯',

  level = 40,
  hp = 46000,
  mana = 2000,
  initialMana = 2000,
  manaRegen = 20.0,
  speed = 322,
  movementType = MovementType.Fly,
  minHeight = 850.0,
  height = 850.0,
  turnRate = 0.6,
  strength = 20,
  agility = 24,
  intelligence = 20,
  strengthPerLevel = 2.0,
  agilityPerLevel = 2.4,
  intelligencePerLevel = 2.0,
  damageBase = 1400,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 1.6,
  attackType = AttackType.Magic,
  weaponType = WeaponType.Missile,
  projectileArt = 'Abilities\\Spells\\Human\\ManaFlare\\ManaFlareMissile.mdl',
  projectileSpeed = 900,
  defense = 30,
  hpRegen = 260.0,
  scale = 3.0,
  collision = 64.0,
  soundSet = 'Phoenix',
  classification = 'undead',
  abilities = 'AInv,A0F8,A0F7,A0F9',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 4500,
  pointValue = 460,
})
