-- Chapter 2 main boss 1: Tree Lord.

createMeleeBossHeroUnit('N05S', '树魔首领', {
  modelFile = "war3mapImported\\Vol'jin.mdl",
  icon = 'war3mapImported\\BossSMSL.blp',
  properNames = '凯金',
  tooltipBasic = '树魔首领',
  tooltipExtended = '树魔首领',
  description = '树魔首领',

  level = 30,
  hp = 13000,
  mana = 1000,
  initialMana = 1000,
  manaRegen = 5.0,
  speed = 372,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 2.0,
  agilityPerLevel = 2.0,
  intelligencePerLevel = 2.0,
  damageBase = 750,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 3.0,
  attackType = AttackType.Chaos,
  weaponType = WeaponType.Instant,
  defense = 35,
  hpRegen = 125.0,
  scale = 2.5,
  soundSet = 'ForestTroll',
  classification = 'undead',
  abilities = 'AInv,A0LL,A0LN,A0LM,AN00',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 2500,
  lumberBountyBase = 1,
  pointValue = 300,
})
