-- Chapter 2 hidden boss: Abyss Kraken Kasela.

createMeleeBossHeroUnit('N05V', '深渊巨鱿·卡瑟拉', {
  modelFile = 'war3mapImported\\Leviathan.mdl',
  icon = 'ReplaceableTextures\\CommandButtons\\BTNDuneWorm.blp',
  properNames = '深渊巨鱿·卡瑟拉',
  tooltipBasic = '深渊巨鱿·卡瑟拉',
  tooltipExtended = '深渊巨鱿·卡瑟拉',
  description = '深渊巨鱿·卡瑟拉',

  level = 35,
  hp = 20000,
  mana = 1000,
  initialMana = 1000,
  manaRegen = 12.5,
  speed = 382,
  movementType = MovementType.Hover,
  minHeight = 750.0,
  height = 750.0,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 2.0,
  agilityPerLevel = 2.0,
  intelligencePerLevel = 2.0,
  damageBase = 1000,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 2.0,
  attackType = AttackType.Chaos,
  weaponType = WeaponType.Instant,
  defense = 40,
  hpRegen = 150.0,
  scale = 3.0,
  collision = 64.0,
  soundSet = 'Naga',
  classification = 'undead',
  abilities = 'AInv,AN00,AN01,AT08,CT16',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 3500,
  lumberBountyBase = 2,
  pointValue = 390,
})
