-- Hero Boss object data entry.

dofile('Boss/HeroBoss/01-Thranduil.lua')
dofile('Boss/HeroBoss/02-Mia.lua')
dofile('Boss/HeroBoss/03-BalzarothAbilities.lua')
dofile('Boss/HeroBoss/03-Balzaroth.lua')
dofile('Boss/HeroBoss/03-BalzarothMechanicUnits.lua')
dofile('Boss/HeroBoss/04-PhoenixelAbilities.lua')
dofile('Boss/HeroBoss/04-Phoenixel.lua')
dofile('Boss/HeroBoss/04-PhoenixelMechanicUnits.lua')
dofile('Boss/HeroBoss/05-TreeLord.lua')
dofile('Boss/HeroBoss/06-Felice.lua')
dofile('Boss/HeroBoss/07-Ricote.lua')
dofile('Boss/HeroBoss/08-Kasela.lua')
dofile('Boss/HeroBoss/09-Moltes.lua')
dofile('Boss/HeroBoss/10-ShadowboneMotes.lua')
