-- Shared constructors for categorized unit object data.

function createAncestralTideUnit(id, parentId, name, modelFile, classification, scale, icon)
  local unit = UnitDefinition:new(id, parentId)
  unit:setName(name)
  unit:setTooltipBasic(name)
  unit:setTooltipExtended(name)
  unit:setDescription(name)
  unit:setModelFile(modelFile)
  unit:setModelFileExtraVersions('0')
  unit:setScalingValue(scale or 1.0)
  unit:setIconGameInterface(icon)
  unit:setRace(Race.Naga)
  unit:setNormalAbilities('')
  unit:setStructuresBuilt('')
  unit:setUpgradesUsed('R001,R002')
  unit:setUnitClassification(classification or 'ancient')
  unit:setCanFlee(false)
  unit:setCanDropItemsOnDeath(true)
  return unit
end

function createSecondLegionUnit(id, parentId, options)
  local unit = UnitDefinition:new(id, parentId)
  unit:setName(options.name)
  unit:setTooltipBasic(options.name)
  unit:setTooltipExtended(options.description)
  unit:setDescription(options.description)
  unit:setModelFile(options.modelFile)
  unit:setModelFileExtraVersions('0')
  unit:setIconGameInterface(options.icon)
  unit:setScalingValue(options.scale)
  unit:setRace(Race.Nightelf)
  unit:setNormalAbilities('')
  unit:setStructuresBuilt('')
  unit:setUpgradesUsed('R001,R002')
  unit:setUnitClassification('')
  unit:setCanFlee(false)
  unit:setHideMinimapDisplay(true)
  unit:setDisplayasNeutralHostile(true)
  unit:setLevel(30)
  unit:setHitPointsMaximumBase(options.hp)
  unit:setHitPointsRegenerationType('always')
  unit:setHitPointsRegenerationRate(options.hpRegen)
  unit:setManaMaximum(options.mana or 0)
  unit:setManaInitialAmount(options.mana or 0)
  unit:setManaRegeneration(options.manaRegen or 0.0)
  unit:setDefenseBase(options.defense)
  unit:setDefenseUpgradeBonus(0)
  unit:setArmorType(ArmorType.Normal)
  unit:setSpeedBase(options.speed)
  unit:setCollisionSize(options.collision)
  unit:setAcquisitionRange(options.acquire)
  unit:setSightRadiusDay(1600)
  unit:setSightRadiusNight(1200)
  unit:setTurnRate(1.0)
  unit:setPointValue(options.pointValue)
  unit:setGoldBountyAwardedBase(options.bounty)
  unit:setGoldBountyAwardedNumberofDice(0)
  unit:setGoldBountyAwardedSidesperDie(0)

  unit:setAttacksEnabled(AttacksEnabled.AttackOneOnly)
  unit:setAttack1AttackType(options.attackType)
  unit:setAttack1DamageBase(options.damage)
  unit:setAttack1DamageNumberofDice(1)
  unit:setAttack1DamageSidesperDie(1)
  unit:setAttack1CooldownTime(options.attackCooldown)
  unit:setAttack1Range(options.attackRange)
  unit:setAttack1RangeMotionBuffer(options.rangeBuffer)
  unit:setAttack1TargetsAllowed(options.attackTargets)
  unit:setAttack1WeaponType(options.weaponType)
  unit:setAttack1WeaponSound(options.weaponSound)
  unit:setAttack1ProjectileArt(options.projectileArt or '')
  unit:setAttack1ProjectileSpeed(options.projectileSpeed or 0)
  unit:setAttack1ProjectileArc(options.projectileArc or 0.0)
  unit:setAttack1ProjectileHomingEnabled(options.projectileHoming or false)
  unit:setAttack1AnimationBackswingPoint(options.attackBackswing)
  unit:setAttack1AnimationDamagePoint(options.attackDamagePoint)
  unit:setAttack1MaximumNumberofTargets(1)
  unit:setAttack1ShowUI(true)
  unit:setProjectileLaunchZ(options.projectileLaunchZ or 60.0)
  unit:setProjectileImpactZ(options.projectileImpactZ or 60.0)
  return unit
end
