-- Unit object data entry, grouped to mirror imports/Unit.

dofile('Unit/UnitTemplates.lua')
dofile('Unit/PlayerHero/Emilia.lua')
dofile('Unit/PlayerHero/Momiji.lua')
dofile('Unit/Elite/AncestralTide.lua')
dofile('Unit/Elite/SealGuard.lua')
dofile('Unit/Elite/Mia.lua')
dofile('Unit/Minion/SealGuard.lua')
dofile('Unit/Guard/SecondLegion.lua')
dofile('Unit/Minion/AncestralTide.lua')
dofile('Unit/Minion/TreeLord.lua')
dofile('Unit/Minion/SecondLegion.lua')
dofile('Unit/Minion/CultCleansers.lua')
dofile('Unit/Minion/Mia.lua')
dofile('Unit/Summon/Felice.lua')
dofile('Unit/NPC/NPC.lua')
dofile('Unit/Special/SecondLegion.lua')
dofile('Unit/Special/ElvenGateDefenseCircle.lua')
dofile('Unit/Special/SealEnergyCore.lua')
