/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";

export const 巴尔扎罗斯BuffID = {
  灼热: "BBZ1",
  熔核封印: "BBZ2",
  火焰锁链: "BBZ3",
  熔岩护盾: "BBZ4",
  炙热奉献: "BBZ5",
  塞拉火焰形态: "BBZ6",
  塞拉冰霜形态: "BBZ7",
  熔岩暴走: "BBZ8",
} as const;

export type 巴尔扎罗斯BuffID类型 = typeof 巴尔扎罗斯BuffID[keyof typeof 巴尔扎罗斯BuffID];

export const 巴尔扎罗斯Buff表: Record<string, BuffData> = {
  [巴尔扎罗斯BuffID.灼热]: {
    buffID: 巴尔扎罗斯BuffID.灼热,
    buffName: "灼热",
    icon: "BuffIcon\\Boss\\Balzaroth\\scorching_heat.blp",
    effect: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeEmbers.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:dot:fire:stack",
    interval: 1,
    maxStack: 12,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 86,
    canPurge: false,
    tooltip: "受到熔岩热浪灼烧。每层使巴尔扎罗斯相关火焰/熔岩伤害提高，并按机制承受周期伤害；可由绝对零度领域或冷却水晶清除。",
  },
  [巴尔扎罗斯BuffID.熔核封印]: {
    buffID: 巴尔扎罗斯BuffID.熔核封印,
    buffName: "熔核封印",
    icon: "BuffIcon\\Boss\\Balzaroth\\molten_core_seal.blp",
    effect: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:seal",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 95,
    canPurge: false,
    tooltip: "巴尔扎罗斯被熔核锁链封印在场地中心，无法移动，受到的伤害降低80%。双护卫死亡或进入第二阶段后解除。",
  },
  [巴尔扎罗斯BuffID.火焰锁链]: {
    buffID: 巴尔扎罗斯BuffID.火焰锁链,
    buffName: "火焰锁链",
    icon: "BuffIcon\\Boss\\Balzaroth\\flame_chain.blp",
    effect: "Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl",
    effectMode: "attach",
    effectAttachPoint: "chest",
    type: "Debuff:dot:fire:chain",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 92,
    canPurge: false,
    tooltip: "被巴尔扎罗斯的火焰锁链束缚。距离超过阈值时会周期受到火焰伤害；攻击锁链单位可提前切断。",
  },
  [巴尔扎罗斯BuffID.熔岩护盾]: {
    buffID: 巴尔扎罗斯BuffID.熔岩护盾,
    buffName: "熔岩护盾",
    icon: "BuffIcon\\Boss\\Balzaroth\\lava_shield.blp",
    effect: "Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:shield",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 88,
    canPurge: false,
    tooltip: "巴尔扎罗斯获得持续10秒的熔岩护盾，吸收最大生命值7%的伤害；近战攻击者每1秒最多受到一次来源最大生命值2%+Boss攻击力20%的火焰反弹，水/冰伤害使护盾消耗提高50%。",
  },
  [巴尔扎罗斯BuffID.炙热奉献]: {
    buffID: 巴尔扎罗斯BuffID.炙热奉献,
    buffName: "炙热奉献",
    icon: "BuffIcon\\Boss\\Balzaroth\\scorching_devotion.blp",
    effect: "Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:channel",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "格鲁姆正在献祭自身为巴尔扎罗斯恢复生命并提供强化。击杀或打断格鲁姆可阻止奉献完成。",
  },
  [巴尔扎罗斯BuffID.塞拉火焰形态]: {
    buffID: 巴尔扎罗斯BuffID.塞拉火焰形态,
    buffName: "塞拉·火焰形态",
    icon: "BuffIcon\\Boss\\Balzaroth\\sera_fire_stance.blp",
    effect: "Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:stance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "塞拉切换为火焰形态，火焰技能伤害提高25%，自身受到水/冰属性伤害提高20%。",
  },
  [巴尔扎罗斯BuffID.塞拉冰霜形态]: {
    buffID: 巴尔扎罗斯BuffID.塞拉冰霜形态,
    buffName: "塞拉·冰霜形态",
    icon: "BuffIcon\\Boss\\Balzaroth\\sera_frost_stance.blp",
    effect: "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:stance",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "塞拉切换为冰霜形态，冰霜技能伤害提高25%，自身受到火属性伤害提高20%。",
  },
  [巴尔扎罗斯BuffID.熔岩暴走]: {
    buffID: 巴尔扎罗斯BuffID.熔岩暴走,
    buffName: "熔岩暴走",
    icon: "BuffIcon\\Boss\\Balzaroth\\lava_rampage.blp",
    effect: "Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:rage",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 94,
    canPurge: false,
    tooltip: "巴尔扎罗斯进入地核暴走阶段，场地压力加速，技能强度提高，并周期触发末日熔爆威胁。",
  },
};

export default 巴尔扎罗斯Buff表;
