/** @noSelfInFile */

import type { BuffData } from "../../01．Buff表";

export const 里科特BuffID = {
  精灵之风: "BRC1",
  神明祝福: "BRC2",
  神风印记: "BRC3",
  神风护体: "BRC4",
  湮灭锁定: "BRC5",
  破魔反击: "BRC6",
} as const;

export type 里科特BuffID类型 = typeof 里科特BuffID[keyof typeof 里科特BuffID];

export const 里科特Buff表: Record<string, BuffData> = {
  [里科特BuffID.精灵之风]: {
    buffID: 里科特BuffID.精灵之风,
    buffName: "精灵之风",
    icon: "BuffIcon\\Boss\\Ricote\\spirit_wind.blp",
    effect: "Abilities\\Spells\\Human\\DispelMagic\\DispelMagicTarget.mdl",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:passive",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 70,
    canPurge: false,
    tooltip: "里科特受到精灵之风庇护，免疫或快速清除大部分减速效果。",
  },
  [里科特BuffID.神明祝福]: {
    buffID: 里科特BuffID.神明祝福,
    buffName: "神明祝福",
    icon: "BuffIcon\\Boss\\Ricote\\divine_blessing.blp",
    effect: "Common\\Effect\\Form\\Aura\\GaiaOrbs6.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:passive",
    interval: 1,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 86,
    canPurge: false,
    tooltip: "里科特每秒恢复1%生命值，受到的控制持续时间不会超过1秒，受到单次最大生命伤害存在上限。",
  },
  [里科特BuffID.神风印记]: {
    buffID: 里科特BuffID.神风印记,
    buffName: "神风印记",
    icon: "BuffIcon\\Boss\\Ricote\\kamikaze_mark.blp",
    effect: "Common\\Effect\\Form\\MagicCircle\\ShiningSquareAura_noTC.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Debuff:magic:stack",
    interval: 0,
    maxStack: 20,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 2,
    priority: 78,
    canPurge: true,
    tooltip: "攻击神风护体期间被反馈神风印记。粉碎会清除所有印记，并按层数造成精神伤害和眩晕。",
  },
  [里科特BuffID.神风护体]: {
    buffID: 里科特BuffID.神风护体,
    buffName: "神风护体",
    icon: "BuffIcon\\Boss\\Ricote\\wind_guard.blp",
    effect: "Common\\Effect\\Form\\Shield\\BlessingOfAzeroth.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:shield",
    interval: 0,
    maxStack: 12,
    stackRule: "stack",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 90,
    canPurge: false,
    tooltip: "里科特获得神风护体层数。每次被攻击减少1层，令本次伤害降低50%，并反馈攻击者1层神风印记。",
  },
  [里科特BuffID.湮灭锁定]: {
    buffID: 里科特BuffID.湮灭锁定,
    buffName: "湮灭锁定",
    icon: "BuffIcon\\Boss\\Ricote\\annihilation_lock.blp",
    effect: "",
    type: "Debuff:mark",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 82,
    canPurge: false,
    tooltip: "湮灭之炮投影正在锁定你的方向。持续期间投影会按锁定方向发射湮灭炮击。",
  },
  [里科特BuffID.破魔反击]: {
    buffID: 里科特BuffID.破魔反击,
    buffName: "破魔反击",
    icon: "BuffIcon\\Boss\\Ricote\\counter_reflect.blp",
    effect: "Common\\Effect\\Form\\Shield\\CounterShieldImpact.mdx",
    effectMode: "attach",
    effectAttachPoint: "origin",
    type: "Buff:boss:counter",
    interval: 0,
    maxStack: 1,
    stackRule: "highest",
    stackRefresh: true,
    dispelLevel: 3,
    priority: 94,
    canPurge: false,
    tooltip: "里科特进入2秒破魔反击窗口。窗口内受到伤害会强制反击伤害来源，按距离移除当前生命并眩晕。",
  },
};

export default 里科特Buff表;
