--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
---
-- @noSelfInFile
____exports["菲利斯数值与表现配置"] = {
    ["领袖光环"] = {
        ["技能槽位"] = "A0LQ",
        ["检查间隔毫秒"] = 1000,
        ["生命切换阈值"] = 0.5,
        ["高血物编等级"] = 1,
        ["低血物编等级"] = 2,
        ["高血友军攻击提高"] = 0.3,
        ["低血友军攻击降低"] = 0.5,
        ["低血剑气灵斩冷却缩短"] = 0.5,
        ["高血光环特效路径"] = "Common\\Effect\\Form\\Aura\\HolyAura.mdx",
        ["低血光环特效路径"] = "Common\\Effect\\Form\\Aura\\BloodAura.mdx",
        ["光环特效缩放"] = 1.1
    },
    ["剑魂杀"] = {
        ["技能槽位"] = "A0LP",
        ["前摇秒"] = 1.5,
        ["动画编号"] = 6,
        ["动画速度"] = 0.9,
        ["吟唱条颜色ID"] = 2,
        ["吟唱条标题文本"] = "剑魂杀",
        ["吟唱条提示文本"] = "菲利斯正在释放两条剑魂狼。",
        ["剑气数量"] = 2,
        ["起点偏移距离"] = 250,
        ["起点夹角"] = 45,
        ["路径距离"] = 1250,
        ["路径宽度"] = 330,
        ["飞行持续秒"] = 1.4,
        ["Tick间隔毫秒"] = 40,
        ["路径伤害Boss攻击力比例"] = 4,
        ["命中半径"] = 165,
        ["合并命中次数"] = 2,
        ["小狼生命点"] = 4,
        ["大狼生命点"] = 8,
        ["小狼缩放"] = 1.15,
        ["大狼缩放"] = 2.2,
        ["狼持续秒"] = 12,
        ["狼移动速度"] = 452,
        ["狼单位类型"] = "o00A",
        ["狼模型路径"] = "units\\orc\\Spiritwolf\\Spiritwolf.mdx",
        ["狼攻击索敌范围"] = 1800,
        ["小狼目标最大生命伤害比例"] = 0.1,
        ["大狼目标最大生命伤害比例"] = 0.2,
        ["狼攻击回魔Boss最大魔法比例"] = 0.05,
        ["异形化狼攻击回血Boss最大生命比例"] = 0.05,
        ["狼魂路径特效路径"] = "Abilities\\Spells\\Demon\\DemonBoltImpact\\DemonBoltImpact.mdl",
        ["狼魂路径特效缩放"] = 1,
        ["狼魂路径特效持续秒"] = 0.35,
        ["召唤爆点特效路径"] = "Abilities\\Spells\\Orc\\FeralSpirit\\feralspirittarget.mdl",
        ["召唤爆点持续秒"] = 1
    },
    ["剑气灵斩"] = {
        ["技能槽位"] = "A0LR",
        ["冷却秒"] = 12,
        ["低血冷却秒"] = 6,
        ["施法硬直秒"] = 0.2,
        ["动画编号"] = 5,
        ["动画速度"] = 1.1,
        ["距离"] = 1500,
        ["宽度"] = 260,
        ["异形化宽度倍率"] = 1.5,
        ["Boss攻击力比例"] = 2,
        ["目标最大生命比例"] = 0.1,
        ["侵蚀持续秒"] = 240,
        ["侵蚀Tick秒"] = 1,
        ["侵蚀Buff残留秒"] = 1.4,
        ["侵蚀Boss攻击力比例"] = 0.5,
        ["侵蚀目标最大生命比例"] = 0.05,
        ["侵蚀扣魔当前魔法比例"] = 0.1,
        ["侵蚀补魔倍率"] = 2,
        ["剑气特效路径"] = "war3mapImported\\redbladeshockwave.mdl",
        ["剑气特效缩放"] = 2,
        ["剑气特效持续秒"] = 1.5,
        ["残留特效路径"] = "Common\\Effect\\Form\\Line\\ChaosWall.mdx",
        ["残留特效缩放"] = 1,
        ["残留特效高度"] = 0,
        ["Tick命中特效路径"] = "Abilities\\Spells\\Human\\Feedback\\ArcaneTowerAttack.mdl",
        ["Tick命中特效持续秒"] = 0.6
    },
    ["全力封印斩"] = {
        ["技能槽位"] = "A0LS",
        ["基础冷却秒"] = 30,
        ["每难度冷却减少秒"] = 2,
        ["前摇秒"] = 1,
        ["动画编号"] = 7,
        ["动画速度"] = 0.8,
        ["吟唱条颜色ID"] = 4,
        ["吟唱条标题文本"] = "全力封印斩",
        ["吟唱条提示文本"] = "QWER 全部冷却的玩家会被封印。",
        ["魔法扣除基础比例"] = 0.35,
        ["魔法扣除每难度追加比例"] = 0.05,
        ["基础眩晕秒"] = 0.3,
        ["每难度眩晕追加秒"] = 0.2,
        ["瞬移距离"] = 96,
        ["Boss起手特效路径"] = "war3mapImported\\Undead Lightning.mdl",
        ["Boss附身特效路径"] = "war3mapImported\\a.mdx",
        ["玩家封印特效路径"] = "Common\\Effect\\Form\\MagicCircle\\Mage aura.mdx",
        ["命中特效路径"] = "war3mapImported\\desecrate.mdl",
        ["特效持续秒"] = 1
    },
    ["异形化"] = {
        ["技能槽位"] = "A0LT",
        ["魔法阈值"] = 10000,
        ["持续秒"] = 5,
        ["动画编号"] = 10,
        ["动画速度"] = 0.9,
        ["吟唱条颜色ID"] = 5,
        ["吟唱条标题文本"] = "异形化",
        ["吟唱条提示文本"] = "菲利斯进入短暂强化形态。",
        ["伤害回魔基础比例"] = 0.7,
        ["伤害回魔每难度追加比例"] = 0.05,
        ["造成和受到伤害提高"] = 0.5,
        ["光伤缩短秒"] = 1.5,
        ["Tick秒"] = 1,
        ["近身扣血半径"] = 250,
        ["近身扣血目标最大生命基础比例"] = 0.07,
        ["近身扣血每难度追加比例"] = 0.01,
        ["近战扣血倍率"] = 0.5,
        ["牵引半径"] = 1000,
        ["牵引每秒速度"] = 150,
        ["牵引持续秒"] = 0.7,
        ["牵引最小距离"] = 96,
        ["牵引闪电代码"] = "AFOD",
        ["爆发柱特效路径"] = "war3mapImported\\darkpillar.mdl",
        ["持续气场特效路径"] = "Common\\Effect\\Form\\Aura\\devil aura.mdx",
        ["周期波动特效路径"] = "war3mapImported\\ddcyz1.mdl",
        ["近身命中特效路径"] = "war3mapImported\\darkhand.mdx",
        ["特效持续秒"] = 1
    }
}
____exports["菲利斯音效配置"] = {
    ["默认裁断距离"] = 2800,
    ["领袖光环"] = {["低血切换"] = "Sound\\Boss\\Felice\\SFX\\felice_leader_aura_lowhp_shift_01.mp3"},
    ["剑魂杀"] = {["路径释放"] = "Sound\\Boss\\Felice\\SFX\\felice_sword_soul_wolves_path_release_03.mp3", ["小狼成形"] = "Sound\\Boss\\Felice\\SFX\\felice_sword_soul_wolf_form_01.mp3", ["大狼合并"] = "Sound\\Boss\\Felice\\SFX\\felice_sword_soul_wolf_form_02.mp3"},
    ["剑气灵斩"] = {["斩出侵蚀"] = "Sound\\Boss\\Felice\\SFX\\felice_crimson_soul_slash_erosion_01.mp3"},
    ["全力封印斩"] = {["起手标记"] = "Sound\\Boss\\Felice\\SFX\\felice_full_seal_slash_mark_start_03.mp3", ["结算"] = "Sound\\Boss\\Felice\\SFX\\felice_full_seal_slash_execute_02.mp3"},
    ["异形化"] = {["启动"] = "Sound\\Boss\\Felice\\SFX\\felice_aberration_transform_start_01.mp3", ["牵引波动"] = "Sound\\Boss\\Felice\\SFX\\felice_aberration_pull_wave_combo_03.mp3", ["牵引波动延迟Ms"] = 650}
}
return ____exports
