--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
---
-- @noSelfInFile
____exports["里科特数值与表现配置"] = {
    ["阶段阈值"] = {["P2生命比例"] = 0.65, ["P3生命比例"] = 0.3},
    ["被动"] = {["每秒回血比例"] = 0.01, ["控制最大持续秒"] = 1, ["普攻必中"] = true},
    ["四重风刃"] = {
        ["施法距离"] = 800,
        ["冷却秒"] = 13,
        ["技能槽位"] = "AT04",
        ["前摇秒"] = 0.8,
        ["动画编号"] = 7,
        ["动画速度"] = 1.2,
        ["吟唱条颜色ID"] = 2,
        ["吟唱条标题文本"] = "精灵魔法·四重风刃",
        ["吟唱条提示文本"] = "跳劈目标区域后释放四道风刃",
        ["跳劈半径"] = 300,
        ["跳劈Boss攻击力比例"] = 2,
        ["跳劈减速比例"] = 0.4,
        ["跳劈减速秒"] = 1,
        ["龙卷风数量"] = 4,
        ["龙卷风延迟秒"] = 1,
        ["龙卷风速度"] = 900,
        ["龙卷风射程"] = 1200,
        ["龙卷风命中半径"] = 130,
        ["龙卷风Boss攻击力比例"] = 4,
        ["龙卷风模型路径"] = "war3mapImported\\xuanfeng4.mdx",
        ["龙卷风缩放"] = 1,
        ["龙卷风飞行高度"] = 80,
        ["P2回转延迟秒"] = 1,
        ["P3追踪延迟秒"] = 1
    },
    ["追击风刃"] = {
        ["施法距离"] = 1250,
        ["冷却秒"] = 13,
        ["技能槽位"] = "AT09",
        ["前摇秒"] = 0.55,
        ["动画编号"] = 7,
        ["动画速度"] = 1.35,
        ["吟唱条颜色ID"] = 2,
        ["吟唱条标题文本"] = "精灵魔法·追击风刃",
        ["射程"] = 1250,
        ["速度"] = 1250,
        ["命中半径"] = 120,
        ["Boss攻击力比例"] = 3,
        ["模型路径"] = "Common\\Effect\\Form\\Charge\\getsugabluenew.mdx",
        ["缩放"] = 1,
        ["飞行高度"] = 70,
        ["P2回转延迟秒"] = 1,
        ["P3追踪延迟秒"] = 1
    },
    ["神风护体"] = {
        ["持续秒"] = 4,
        ["技能槽位"] = "AN00",
        ["基础层数"] = 7,
        ["受击减伤比例"] = 0.5,
        ["粉碎基础眩晕秒"] = 0.4,
        ["粉碎每层眩晕秒"] = 0.2,
        ["粉碎每层最大生命比例"] = 0.2,
        ["护体特效路径"] = "Common\\Effect\\Form\\Shield\\BlessingOfAzeroth.mdx",
        ["粉碎特效路径"] = "Abilities\\Spells\\Other\\Monsoon\\MonsoonBoltTarget.mdl"
    },
    ["湮灭之炮"] = {
        ["技能槽位"] = "AN01",
        ["锁定前延迟秒"] = 3,
        ["P2锁定前延迟秒"] = 2,
        ["锁定持续秒"] = 3,
        ["tick秒"] = 0.1,
        ["射程"] = 1200,
        ["投影距离"] = 300,
        ["投影单位类型"] = "hfoo",
        ["投影模型路径"] = "Boss\\Ricote\\Ricote.mdx",
        ["投影缩放"] = 1.35,
        ["投影透明度"] = 135,
        ["出现特效路径"] = "Common\\Effect\\Form\\Illusion\\MirrorImageIllusion.mdx",
        ["射线特效路径"] = "Common\\Effect\\Form\\Line\\AnnihilationBeam.mdx",
        ["射线持续秒"] = 0.18,
        ["每跳Boss攻击力比例"] = 0.1,
        ["P3眩晕炮延迟秒"] = 1,
        ["P3眩晕炮半径"] = 250,
        ["P3眩晕秒"] = 1
    },
    ["湮灭之风"] = {
        ["技能槽位"] = "AN02",
        ["持续秒"] = 8,
        ["沉默秒"] = 1.5,
        ["冷却秒"] = 60,
        ["tick秒"] = 0.5,
        ["半径"] = 1200,
        ["Boss攻击力比例"] = 2,
        ["风场特效路径"] = "Common\\Effect\\Element\\Wind\\AnnihilationWindField.mdx",
        ["风场缩放"] = 2.8,
        ["风场特效持续秒"] = 8,
        ["扩散特效路径"] = "Common\\Effect\\Form\\Explosion\\WhiteWindExpansion.mdx",
        ["扩散特效持续秒"] = 1.2,
        ["随机控制持续秒"] = 2,
        ["随机眩晕秒"] = 1,
        ["随机减速比例"] = 0.3,
        ["随机减速秒"] = 4
    },
    ["破魔反击"] = {
        ["技能槽位"] = "AN03",
        ["预备最小秒"] = 1,
        ["预备最大秒"] = 5,
        ["反击窗口秒"] = 2,
        ["冷却秒"] = 40,
        ["近距离阈值"] = 300,
        ["近距离当前生命移除比例"] = 0.7,
        ["远距离当前生命移除比例"] = 0.99,
        ["眩晕秒"] = 0.8,
        ["反击特效路径"] = "Common\\Effect\\Form\\Shield\\CounterShieldImpact.mdx"
    }
}
____exports["里科特音效配置"] = {
    ["默认裁断距离"] = 2800,
    ["四重风刃"] = {["跳劈身法掠风"] = "Sound\\Boss\\Ricote\\SFX\\ricote_quad_windblade_leap_impact_07.mp3", ["四龙卷发射"] = "Sound\\Boss\\Ricote\\SFX\\ricote_quad_windblade_tornado_x_release_03.mp3"},
    ["追击风刃"] = {["发射"] = "Sound\\Boss\\Ricote\\SFX\\ricote_chasing_windblade_release_01.mp3"},
    ["神风护体"] = {["展开"] = "Sound\\Boss\\Ricote\\SFX\\ricote_divine_wind_shield_open_01.mp3", ["粉碎清算"] = "Sound\\Boss\\Ricote\\SFX\\ricote_divine_wind_mark_shatter_resolve_02.mp3"},
    ["湮灭之炮"] = {["投影锁定"] = "Sound\\Boss\\Ricote\\SFX\\ricote_annihilation_cannon_projection_lock_02.mp3", ["射线开火"] = "Sound\\Boss\\Ricote\\SFX\\ricote_annihilation_cannon_beam_fire_01.mp3"},
    ["湮灭之风"] = {["风场展开"] = "Sound\\Boss\\Ricote\\SFX\\ricote_annihilation_wind_field_open_02.mp3"},
    ["破魔反击"] = {["窗口开启"] = "Sound\\Boss\\Ricote\\SFX\\ricote_counter_window_open_04.mp3", ["触发剥离"] = "Sound\\Boss\\Ricote\\SFX\\ricote_counter_trigger_life_strip_01.mp3"}
}
return ____exports
