-- Polluted-water route minions for the Mia side quest.

local sludgeWarrior = UnitDefinition:new('n07B', 'nslm')
sludgeWarrior:setName('腐淤战士')
sludgeWarrior:setTooltipBasic('腐淤战士')
sludgeWarrior:setTooltipExtended('由污染水源凝成的近战淤泥怪。')
sludgeWarrior:setDescription('由污染水源凝成的近战淤泥怪。')
sludgeWarrior:setIconGameInterface('Unit\\Minion\\Icon\\mia_sludge_warrior.blp')
sludgeWarrior:setLevel(27)
sludgeWarrior:setHitPointsMaximumBase(7200)
sludgeWarrior:setHitPointsRegenerationType('always')
sludgeWarrior:setHitPointsRegenerationRate(57.6)
sludgeWarrior:setDefenseBase(22)
sludgeWarrior:setAttack1DamageBase(1150)
sludgeWarrior:setAttack1CooldownTime(1.15)
sludgeWarrior:setSpeedBase(310)
sludgeWarrior:setUpgradesUsed('R001,R002')
sludgeWarrior:setCanFlee(false)
sludgeWarrior:setDisplayasNeutralHostile(true)
sludgeWarrior:setCanDropItemsOnDeath(true)

local sludgeThrower = UnitDefinition:new('n07C', 'nslf')
sludgeThrower:setName('腐淤投手')
sludgeThrower:setTooltipBasic('腐淤投手')
sludgeThrower:setTooltipExtended('把自身污泥凝成腐蚀弹块投向敌人的淤泥怪。')
sludgeThrower:setDescription('把自身污泥凝成腐蚀弹块投向敌人的淤泥怪。')
sludgeThrower:setIconGameInterface('Unit\\Minion\\Icon\\mia_sludge_thrower.blp')
sludgeThrower:setLevel(27)
sludgeThrower:setHitPointsMaximumBase(6400)
sludgeThrower:setHitPointsRegenerationType('always')
sludgeThrower:setHitPointsRegenerationRate(51.2)
sludgeThrower:setDefenseBase(18)
sludgeThrower:setAttack1DamageBase(1320)
sludgeThrower:setAttack1CooldownTime(1.70)
sludgeThrower:setAttack1Range(650)
sludgeThrower:setAcquisitionRange(850)
sludgeThrower:setSpeedBase(295)
sludgeThrower:setUpgradesUsed('R001,R002')
sludgeThrower:setCanFlee(false)
sludgeThrower:setDisplayasNeutralHostile(true)
sludgeThrower:setCanDropItemsOnDeath(true)
