-- Special wave units for the seal defense encounter.

local function createSealGuardMinion(id, name, options)
  options.name = name
  options.upgrades = 'R001'
  options.defense = 10
  options.classification = ''
  return createSealGuardUnit(id, options.parentId, options)
end

createSealGuardMinion('n06A', '夺灵祭司', {
  parentId = 'nw2w',
  description = '争夺封印锚点并阻断修复的灵体祭司。',
  level = 25,
  modelFile = 'Unit\\Minion\\SealGuard\\SoulSeizingPriest\\MagosExplorators.mdx',
  icon = 'Unit\\Minion\\Icon\\SoulSeizingPriest.blp',
  scale = 2.30,
  hp = 6200,
  hpRegen = 62.0,
  mana = 1000,
  manaRegen = 10.0,
  speed = 300,
  collision = 24.0,
  acquire = 900.0,
  pointValue = 120,
  bounty = 0,
  damage = 1000,
  attackCooldown = 2.30,
  attackRange = 700,
  rangeBuffer = 250.0,
  attackTargets = 'ground,air,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Magic,
  weaponType = WeaponType.Missile,
  weaponSound = WeaponSound.Nothing,
  projectileArt = 'Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl',
  projectileSpeed = 900,
  projectileArc = 0.15,
  projectileHoming = true,
  projectileLaunchZ = 90.0,
  projectileImpactZ = 60.0,
  attackBackswing = 0.60,
  attackDamagePoint = 0.50,
})

createSealGuardMinion('n06B', '失控英灵', {
  parentId = 'nban',
  description = '被封印残响驱使的失控古代战魂。',
  level = 25,
  modelFile = 'Unit\\Minion\\SealGuard\\UncontrolledRevenant\\MawConstructGuillotine.mdx',
  icon = 'Unit\\Minion\\Icon\\UncontrolledRevenant.blp',
  scale = 2.30,
  hp = 7600,
  hpRegen = 76.0,
  speed = 310,
  collision = 32.0,
  acquire = 800.0,
  pointValue = 110,
  bounty = 0,
  damage = 1450,
  attackCooldown = 2.00,
  attackRange = 128,
  rangeBuffer = 250.0,
  attackTargets = 'ground,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Normal,
  weaponType = WeaponType.Normal,
  weaponSound = WeaponSound.MetalHeavyChop,
  attackBackswing = 0.50,
  attackDamagePoint = 0.40,
})

createSealGuardMinion('n06C', '锚蚀兽', {
  parentId = 'nban',
  description = '绕过正面战线、冲向封印核心的快速锚蚀兽。',
  level = 25,
  modelFile = 'Unit\\Minion\\SealGuard\\AnchorCorrodingBeast\\AnchorCorrodingBeast.mdx',
  icon = 'Unit\\Minion\\Icon\\AnchorCorrodingBeast.blp',
  scale = 4.20,
  hp = 4800,
  hpRegen = 48.0,
  speed = 360,
  collision = 24.0,
  acquire = 1200.0,
  pointValue = 100,
  bounty = 0,
  damage = 900,
  attackCooldown = 2.00,
  attackRange = 100,
  rangeBuffer = 200.0,
  attackTargets = 'ground,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Normal,
  weaponType = WeaponType.Normal,
  weaponSound = WeaponSound.MetalLightChop,
  attackBackswing = 0.35,
  attackDamagePoint = 0.25,
})

createSealGuardMinion('n06D', '断誓猎手', {
  parentId = 'earc',
  description = '在后方压制封印核心的断誓猎手。',
  level = 25,
  modelFile = 'Unit\\Minion\\SealGuard\\OathbreakerHunter\\DraeneiArcher.mdx',
  icon = 'Unit\\Minion\\Icon\\OathbreakerHunter.blp',
  scale = 2.20,
  hp = 5600,
  hpRegen = 56.0,
  speed = 320,
  collision = 24.0,
  acquire = 1000.0,
  pointValue = 105,
  bounty = 0,
  damage = 1050,
  attackCooldown = 2.00,
  attackRange = 800,
  rangeBuffer = 250.0,
  attackTargets = 'ground,air,enemy,neutral,structure,debris,item,ward',
  attackType = AttackType.Pierce,
  weaponType = WeaponType.Missile,
  weaponSound = WeaponSound.Nothing,
  projectileArt = 'Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl',
  projectileSpeed = 1100,
  projectileArc = 0.10,
  projectileHoming = true,
  projectileLaunchZ = 110.0,
  projectileImpactZ = 60.0,
  attackBackswing = 0.50,
  attackDamagePoint = 0.35,
})
