-- Tree Lord permanent minions. Keep raw ids aligned with the source map.

local headhunter = UnitDefinition:new('ohun', 'ohun')
headhunter:setName('巨魔猎头者')
headhunter:setHitPointsMaximumBase(20000)
headhunter:setAttack1CooldownTime(3.0)
headhunter:setAttack1DamageBase(100)
headhunter:setModelFile('Unit\\Minion\\ForestTrollTrapper.mdx')
headhunter:setIconGameInterface('Unit\\Minion\\Icon\\TrollHeadhunter.blp')
headhunter:setLevel(25)
headhunter:setManaInitialAmount(1000)
headhunter:setManaMaximum(1000)
headhunter:setScalingValue(1.75)
headhunter:setHitPointsRegenerationRate(200.0)
headhunter:setManaRegeneration(10.0)
headhunter:setSpeedBase(472)
headhunter:setUpgradesUsed('R001,R002')

local witchDoctor = UnitDefinition:new('odoc', 'odoc')
witchDoctor:setName('巨魔巫医')
witchDoctor:setNormalAbilities('')
witchDoctor:setModelFile('Unit\\Minion\\Trollwuyi.mdx')
witchDoctor:setIconGameInterface('Unit\\Minion\\Icon\\TrollWitchDoctor.blp')
witchDoctor:setScalingValue(1.8)
witchDoctor:setUpgradesUsed('R001,R002')

local thrower = UnitDefinition:new('h00U', 'hmtm')
thrower:setName('巨魔投掷者')
thrower:setHitPointsMaximumBase(7000)
thrower:setNormalAbilities('Afsh')
thrower:setAcquisitionRange(1250.0)
thrower:setCanFlee(false)
thrower:setAttack1CooldownTime(3.0)
thrower:setAttack2CooldownTime(3.0)
thrower:setDefenseBase(30)
thrower:setAttack1DamageBase(3000)
thrower:setAttack2DamageBase(3000)
thrower:setAttack1ProjectileSpeed(250)
thrower:setModelFile('Unit\\Minion\\TrollStonehurler.mdx')
thrower:setIconGameInterface('Unit\\Minion\\Icon\\TrollThrower.blp')
thrower:setHideMinimapDisplay(true)
thrower:setDisplayasNeutralHostile(true)
thrower:setLevel(25)
thrower:setMinimumAttackRange(0)
thrower:setRace(Race.Creeps)
thrower:setAttack1Range(1250)
thrower:setHitPointsRegenerationRate(20.0)
thrower:setSpeedBase(200)
thrower:setAttack1TargetsAllowed('debris,ground,wall,ward,item')
thrower:setUpgradesUsed('R001,R002')
