-- Tree Lord permanent minions. Keep raw ids aligned with the source map.

local headhunter = UnitDefinition:new('ohun')
headhunter:setName('巨魔猎头者')
headhunter:setHitPointsMaximumBase(6800)
headhunter:setAttack1CooldownTime(1.5)
headhunter:setAttack1DamageBase(950)
headhunter:setDefenseBase(20)
headhunter:setModelFile('Unit\\Minion\\ForestTrollTrapper.mdx')
headhunter:setIconGameInterface('Unit\\Minion\\Icon\\TrollHeadhunter.blp')
headhunter:setLevel(25)
headhunter:setManaInitialAmount(1000)
headhunter:setManaMaximum(1000)
headhunter:setScalingValue(1.75)
headhunter:setHitPointsRegenerationRate(54.4)
headhunter:setManaRegeneration(10.0)
headhunter:setSpeedBase(472)
headhunter:setUpgradesUsed('R001,R002')

local witchDoctor = UnitDefinition:new('odoc')
witchDoctor:setName('巨魔巫医')
witchDoctor:setNormalAbilities('')
witchDoctor:setHitPointsMaximumBase(6000)
witchDoctor:setAttack1CooldownTime(1.8)
witchDoctor:setAttack1DamageBase(1100)
witchDoctor:setDefenseBase(15)
witchDoctor:setModelFile('Unit\\Minion\\Trollwuyi.mdx')
witchDoctor:setIconGameInterface('Unit\\Minion\\Icon\\TrollWitchDoctor.blp')
witchDoctor:setScalingValue(1.8)
witchDoctor:setHitPointsRegenerationRate(48.0)
witchDoctor:setUpgradesUsed('R001,R002')

local thrower = UnitDefinition:new('h00U', 'hmtm')
thrower:setName('巨魔投掷者')
thrower:setHitPointsMaximumBase(7600)
thrower:setNormalAbilities('Afsh')
thrower:setAcquisitionRange(1250.0)
thrower:setCanFlee(false)
thrower:setAttack1CooldownTime(2.2)
thrower:setAttack2CooldownTime(2.2)
thrower:setDefenseBase(20)
thrower:setAttack1DamageBase(1500)
thrower:setAttack2DamageBase(1500)
thrower:setAttack1ProjectileSpeed(250)
thrower:setModelFile('Unit\\Minion\\TrollStonehurler.mdx')
thrower:setIconGameInterface('Unit\\Minion\\Icon\\TrollThrower.blp')
thrower:setHideMinimapDisplay(true)
thrower:setDisplayasNeutralHostile(true)
thrower:setLevel(25)
thrower:setMinimumAttackRange(0)
thrower:setRace(Race.Creeps)
thrower:setAttack1Range(1250)
thrower:setHitPointsRegenerationRate(60.8)
thrower:setSpeedBase(200)
thrower:setAttack1TargetsAllowed('debris,ground,wall,ward,item')
thrower:setUpgradesUsed('R001,R002')
