/** @noSelfInFile */

export const 夏提雅单位技能配置 = {
  BossKey: 'ShalltearBloodfallen',
  单位名称: '夏提雅·布拉德弗伦',
  正式单位ID: 'U009',
  模型路径: 'Boss\\ShalltearBloodfallen\\Shalltear.mdx',
  女武神形态: {
    单位ID: 'U00A',
    模型路径: 'Boss\\ShalltearBloodfallen\\ShalltearValkyrie.mdx',
  },
  阶段阈值: {
    P2生命比例: 0.7,
    P3生命比例: 0.35,
  },
  广播持续时间Ms: 5200,
  配音裁断距离: 4000,
  开场台词时间: {
    战斗开始延迟Ms: 10500,
    英灵战乙女延迟Ms: 7200,
  },
  台词: {
    登场: ['能来到妾身面前，倒还有几分能耐。来吧，让妾身好好品尝你们的力量。'],
    战斗开始: ['那么，决斗开始。可别太快坏掉哦。'],
    滴管穿心: ['无论逃到哪里，滴管长枪都会将你贯穿。'],
    汲血穿刺: ['真甜。你的鲜血，妾身收下了。'],
    血月轮舞: ['在血月之下陪妾身起舞吧。慢上一步，可就要被撕碎了。'],
    净化投枪: ['神圣之枪也不过是妾身的仆从。要逃，还是要净化污血，由你选择。'],
    鲜血回收: ['留在大地上的鲜血，全都是妾身的。来，回到妾身这里。'],
    进入P2: ['很好。那就让你们见识真正的战乙女。'],
    英灵战乙女: ['英灵战乙女，映照妾身的长枪。'],
    镜像夹击: ['躲开一次可不算本事。第二枪，已经在你面前了。'],
    进入P3: ['啊，真令人兴奋。妾身的真祖之血，已经按捺不住了！'],
    血月终舞: ['血月之下已无处可逃。来吧，陪妾身跳完最后一支舞。'],
    血之复生: ['就凭这样，也想让妾身倒下？鲜血啊，再一次赋予妾身生命！'],
    复生成功: ['呵呵，只差一步。可惜，妾身还站在这里。'],
    复生失败: ['……竟然连复生之血都斩断了。好吧，这一次，是你们赢了。'],
    再次战败: ['胜负已分。妾身会将这场决斗，铭记于心。'],
  },
  配音资源: {
    登场: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\01_intro_trial.mp3'],
    战斗开始: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\02_battle_start.mp3'],
    滴管穿心: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\03_pipette_lance.mp3'],
    汲血穿刺: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\04_blood_drain.mp3'],
    血月轮舞: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\05_blood_moon_waltz.mp3'],
    净化投枪: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\06_purifying_javelin.mp3'],
    鲜血回收: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\07_blood_recall.mp3'],
    进入P2: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\08_phase_two_valkyrie.mp3'],
    英灵战乙女: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\09_einherjar_summon.mp3'],
    镜像夹击: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\10_mirror_pincer.mp3'],
    进入P3: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\11_true_ancestor_feast.mp3'],
    血月终舞: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\12_blood_moon_finale.mp3'],
    血之复生: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\13_blood_resurrection.mp3'],
    复生成功: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\14_resurrection_success.mp3'],
    复生失败: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\15_resurrection_failure.mp3'],
    再次战败: ['Sound\\Boss\\ShalltearBloodfallen\\Voice\\16_final_defeat.mp3'],
  },
  当前状态: {
    目录结构已建立: true,
    单位数据已确认: true,
    普攻核心已实现: true,
    技能已实现: true,
    战斗已注册: true,
  },
} as const;

export type 夏提雅台词类型 = keyof typeof 夏提雅单位技能配置.台词;
