-- System abilities

local asg1 = AbilityDefinitionAttackBonusPlus1:new('ASG1')
asg1:setName('[系统]攻击力增加')
asg1:setAttackBonus(1, 0)

local asg2 = AbilityDefinitionDefenseBonusPlus1:new('ASG2')
asg2:setName('[系统]护甲增加')
asg2:setDefenseBonus(1, 0)

local asg3 = AbilityDefinitionAttributeModifierSkill:new('ASG3')
asg3:setName('[系统]属性增加')
asg3:setStrengthBonus(1, 0)
asg3:setAgilityBonus(1, 0)
asg3:setIntelligenceBonus(1, 0)
asg3:setHideButton(1, true)
asg3:setLevels(1)
asg3:setHeroAbility(false)
asg3:setItemAbility(true)
asg3:setArtCaster('')

local asg6 = AbilityDefinitionMoveSpeedBonus:new('ASG6')
asg6:setName('[系统]移动速度增加')
asg6:setMovementSpeedBonus(1, 0)

local asg7 = AbilityDefinitionAttackSpeedIncrease:new('ASG7')
asg7:setName('[系统]攻击速度增加')
asg7:setAttackSpeedIncrease(1, 0)

-- Buff abilities

local asby = AbilityDefinitionPolymorph:new('ASBy')
asby:setName('[Buff系统]变羊')
asby:setMissileArt('')
asby:setMissileSpeed(10000)
asby:setAnimationNames('')
asby:setLevels(1)
asby:setCooldown(1, 0)
asby:setManaCost(1, 0)
asby:setCastRange(1, 999999)
asby:setDurationNormal(1, 1)
asby:setDurationHero(1, 1)
asby:setRequirements('')
asby:setTargetsAllowed(1, 'ground,air')
asby:setMaximumCreepLevel(1, 0)

local asb0 = AbilityDefinitionMountainKingThunderBolt:new('ASB0')
asb0:setName('[Buff系统]击晕')
asb0:setMissileArt('')
asb0:setMissileSpeed(0)
asb0:setAnimationNames('')
asb0:setLevels(1)
asb0:setCooldown(1, 0)
asb0:setManaCost(1, 0)
asb0:setCastRange(1, 999999)
asb0:setDurationNormal(1, 1)
asb0:setDurationHero(1, 1)
asb0:setRequirements('')
asb0:setTargetsAllowed(1, 'ground,air')
asb0:setDamage(1, 0)

local asbx = AbilityDefinitionInvisibility:new('ASBX')
asbx:setName('[Buff系统]隐形')
asbx:setMissileArt('')
asbx:setMissileSpeed(0)
asbx:setAnimationNames('')
asbx:setLevels(1)
asbx:setCooldown(1, 0)
asbx:setManaCost(1, 0)
asbx:setCastRange(1, 999999)
asbx:setDurationNormal(1, 1)
asbx:setDurationHero(1, 1)
asbx:setRequirements('')
asbx:setTargetsAllowed(1, 'ground,air')

local asb4 = AbilityDefinitionThunderBoltCreep:new('ASB4')
asb4:setName('[Buff系统]冰冻')
asb4:setMissileArt('')
asb4:setMissileSpeed(0)
asb4:setLevels(1)
asb4:setCooldown(1, 0)
asb4:setManaCost(1, 0)
asb4:setCastRange(1, 999999)
asb4:setDurationNormal(1, 1)
asb4:setDurationHero(1, 1)
asb4:setRequirements('')
asb4:setBuffs(1, 'Bfrz')
asb4:setTargetsAllowed(1, 'ground,air')
asb4:setDamage(1, 0)

local asb9 = AbilityDefinitionSlow:new('ASB9')
asb9:setName('[Buff系统]减速')
asb9:setAnimationNames('')
asb9:setMovementSpeedFactor(1, 0.1)
asb9:setAttackSpeedFactor(1, 0)
asb9:setLevels(1)
asb9:setCooldown(1, 0)
asb9:setManaCost(1, 0)
asb9:setCastRange(1, 999999)
asb9:setDurationNormal(1, 1)
asb9:setDurationHero(1, 1)
asb9:setRequirements('')
asb9:setTargetsAllowed(1, 'ground,air')

local asb8 = AbilityDefinitionSilenceCreep:new('ASB8')
asb8:setName('[Buff系统]沉默')
asb8:setAnimationNames('')
asb8:setAttacksPrevented(1, 8)
asb8:setChanceToMiss(1, 0)
asb8:setLevels(1)
asb8:setCooldown(1, 0)
asb8:setManaCost(1, 0)
asb8:setCastRange(1, 999999)
asb8:setDurationNormal(1, 1)
asb8:setDurationHero(1, 1)
asb8:setRequirements('')
asb8:setAreaofEffect(1, 1)
asb8:setTargetsAllowed(1, 'ground,air')
