--[[
ObjEditing notes:
1. This file is executed by ObjEditing.exe only.
2. Do not require runtime libraries here.
3. Use raw ids and minimal verified setters.
4. If deletion does not sync, run Clean Project and save again.
5. Chinese hover docs are in objediting/objediting_zh_docs.lua.
]]

-- System abilities

local asg1 = AbilityDefinitionAttackBonusPlus1:new('ASG1')
asg1:setName('[系统]攻击力增加')
asg1:setAttackBonus(1, 0)

local asg2 = AbilityDefinitionDefenseBonusPlus1:new('ASG2')
asg2:setName('[系统]护甲增加')
asg2:setDefenseBonus(1, 0)

local asg3 = AbilityDefinitionAttributeModifierSkill:new('ASG3')
asg3:setName('[系统]属性增加')
asg3:setStrengthBonus(1, 0)
asg3:setAgilityBonus(1, 0)
asg3:setIntelligenceBonus(1, 0)
asg3:setHideButton(1, true)
asg3:setLevels(1)
asg3:setHeroAbility(false)
asg3:setItemAbility(true)
asg3:setArtCaster('')

local asg6 = AbilityDefinitionMoveSpeedBonus:new('ASG6')
asg6:setName('[系统]移动速度增加')
asg6:setMovementSpeedBonus(1, 0)

local asg7 = AbilityDefinitionAttackSpeedIncrease:new('ASG7')
asg7:setName('[系统]攻击速度增加')
asg7:setAttackSpeedIncrease(1, 0)

-- Buff abilities

local asby = AbilityDefinitionPolymorph:new('ASBy')
asby:setName('[Buff系统]变羊')
asby:setMissileArt('')
asby:setMissileSpeed(10000)
asby:setAnimationNames('')
asby:setLevels(1)
asby:setCooldown(1, 0)
asby:setManaCost(1, 0)
asby:setCastRange(1, 999999)
asby:setDurationNormal(1, 1)
asby:setDurationHero(1, 1)
asby:setRequirements('')
asby:setTargetsAllowed(1, 'ground,air')
asby:setMaximumCreepLevel(1, 0)

-- ThunderBolt class name here is only the template source.
-- Keep only verified setters for the stun version.
local asb0 = AbilityDefinitionMountainKingThunderBolt:new('ASB0')
asb0:setName('[Buff系统]击晕')
asb0:setMissileArt('')
asb0:setMissileSpeed(0)
asb0:setAnimationNames('')
asb0:setLevels(1)
asb0:setCooldown(1, 0)
asb0:setManaCost(1, 0)
asb0:setCastRange(1, 999999)
asb0:setDurationNormal(1, 1)
asb0:setDurationHero(1, 1)
asb0:setRequirements('')
asb0:setTargetsAllowed(1, 'ground,air')

local asbx = AbilityDefinitionInvisibility:new('ASBX')
asbx:setName('[Buff系统]隐形')
asbx:setMissileArt('')
asbx:setMissileSpeed(0)
asbx:setAnimationNames('')
asbx:setLevels(1)
asbx:setCooldown(1, 0)
asbx:setManaCost(1, 0)
asbx:setCastRange(1, 999999)
asbx:setDurationNormal(1, 1)
asbx:setDurationHero(1, 1)
asbx:setRequirements('')
asbx:setTargetsAllowed(1, 'ground,air')

local asb4 = AbilityDefinitionThunderBoltCreep:new('ASB4')
asb4:setName('[Buff系统]冰冻')
asb4:setMissileArt('')
asb4:setMissileSpeed(0)
asb4:setLevels(1)
asb4:setCooldown(1, 0)
asb4:setManaCost(1, 0)
asb4:setCastRange(1, 999999)
asb4:setDurationNormal(1, 1)
asb4:setDurationHero(1, 1)
asb4:setRequirements('')
asb4:setBuffs(1, 'Bfrz')
asb4:setTargetsAllowed(1, 'ground,air')

local asb9 = AbilityDefinitionSlow:new('ASB9')
asb9:setName('[Buff系统]减速')
asb9:setAnimationNames('')
asb9:setMovementSpeedFactor(1, 0.1)
asb9:setAttackSpeedFactor(1, 0)
asb9:setLevels(1)
asb9:setCooldown(1, 0)
asb9:setManaCost(1, 0)
asb9:setCastRange(1, 999999)
asb9:setDurationNormal(1, 1)
asb9:setDurationHero(1, 1)
asb9:setRequirements('')
asb9:setTargetsAllowed(1, 'ground,air')

local asb8 = AbilityDefinitionSilenceCreep:new('ASB8')
asb8:setName('[Buff系统]沉默')
asb8:setAnimationNames('')
asb8:setAttacksPrevented(1, 8)
asb8:setChanceToMiss(1, 0)
asb8:setLevels(1)
asb8:setCooldown(1, 0)
asb8:setManaCost(1, 0)
asb8:setCastRange(1, 999999)
asb8:setDurationNormal(1, 1)
asb8:setDurationHero(1, 1)
asb8:setRequirements('')
asb8:setAreaofEffect(1, 1)
asb8:setTargetsAllowed(1, 'ground,air')

-- Buff dummy unit

local bHun = UnitDefinition:new('bHun', 'ewsp')
bHun:setNormalAbilities('Aloc')
bHun:setCollisionSize(0.0)
bHun:setName('SFB_Unit')
bHun:setModelFile('.mdl')
bHun:setStructuresBuilt('')
bHun:setUpgradesUsed('')
bHun:setUnitSoundSet('')
bHun:setAnimationCastBackswing(0.0)
bHun:setMovementType(MovementType.Fly)
bHun:setUnitClassification('ancient')
bHun:setHitPointsRegenerationType('always')
bHun:setManaMaximum(10000)
bHun:setManaRegeneration(1000.0)
bHun:setManaInitialAmount(1000)
bHun:setFoodProduced(0)
bHun:setHitPointsMaximumBase(10000)
bHun:setHitPointsRegenerationRate(100.0)
bHun:setHideMinimapDisplay(true)
bHun:setSightRadiusDay(0)
bHun:setSightRadiusNight(0)
bHun:setTurnRate(3.0)
bHun:setPropulsionWindowdegrees(360.0)

-- Charge / cast progress bar unit
-- Parent id: ewsp
local e011 = UnitDefinition:new('e011', 'ewsp')
e011:setName('[系统]施法进度条')
e011:setTooltipBasic('')
e011:setTooltipExtended('')
e011:setDescription('')
e011:setNormalAbilities('Aloc')
e011:setCollisionSize(0.0)
e011:setModelFile('resource\\models\\Common\\Progressbar.mdx')
e011:setScalingValue(1.0)
e011:setStructuresBuilt('')
e011:setUpgradesUsed('')
e011:setUnitSoundSet('')
e011:setAnimationCastBackswing(0.0)
e011:setAnimationCastPoint(0.0)
e011:setMovementType(MovementType.Fly)
e011:setMovementHeightMinimum(275.0)
e011:setMovementHeight(275.0)
e011:setSpeedBase(1)
e011:setSpeedMinimum(0)
e011:setSpeedMaximum(0)
e011:setUnitClassification('ancient')
e011:setHitPointsRegenerationType('always')
e011:setFoodProduced(0)
e011:setHitPointsMaximumBase(1)
e011:setHitPointsRegenerationRate(0.0)
e011:setHideMinimapDisplay(true)
e011:setSightRadiusDay(0)
e011:setSightRadiusNight(0)
e011:setTurnRate(3.0)
e011:setPropulsionWindowdegrees(360.0)
e011:setSelectionScale(0.0)
