-- Buff dummy unit helper
local function createBuffUnit(id, name)
  local u = UnitDefinition:new(id, 'ewsp')
  u:setNormalAbilities('Aloc')
  u:setCollisionSize(0.0)
  u:setName(name)
  u:setModelFile('.mdl')
  -- 单位“物编-Art-图标”不要写 setArt。
  -- 这套 ObjEditing 的真实单位 API 需要去 `.def/def/` 查定义：
  -- 例如单位图标字段 `uico` 对应 `.def/def/UnitOrBuildingOrHeroDefinition.lua`
  -- 真实 setter 是 `setIconGameInterface(...)`。
  u:setIconGameInterface('ReplaceableTextures\\CommandButtons\\BTNNecromancerAdept.blp')
  u:setStructuresBuilt('')
  u:setUpgradesUsed('')
  u:setUnitSoundSet('')
  u:setAnimationCastBackswing(0.0)
  u:setMovementType(MovementType.Fly)
  u:setUnitClassification('ancient')
  u:setHitPointsRegenerationType('always')
  u:setManaMaximum(10000)
  u:setManaRegeneration(1000.0)
  u:setManaInitialAmount(1000)
  u:setFoodProduced(0)
  u:setHitPointsMaximumBase(10000)
  u:setHitPointsRegenerationRate(100.0)
  u:setHideMinimapDisplay(true)
  u:setSightRadiusDay(0)
  u:setSightRadiusNight(0)
  u:setTurnRate(3.0)
  u:setPropulsionWindowdegrees(360.0)
  return u
end

createBuffUnit('bHun', 'SFB_Unit')
createBuffUnit('sfb1', '[系统]增益buff')
createBuffUnit('sfb2', '[系统]负面buff')

-- Charge / cast progress bar unit
local e011 = UnitDefinition:new('e011', 'ewsp')
e011:setName('[系统]施法进度条')
e011:setTooltipBasic('')
e011:setTooltipExtended('')
e011:setDescription('')
e011:setNormalAbilities('Aloc')
e011:setCollisionSize(0.0)
e011:setModelFile('resource\\models\\Common\\Progressbar.mdx')
e011:setIconGameInterface('ReplaceableTextures\\CommandButtons\\BTNNecromancerAdept.blp')
e011:setScalingValue(1.0)
e011:setStructuresBuilt('')
e011:setUpgradesUsed('')
e011:setUnitSoundSet('')
e011:setAnimationCastBackswing(0.0)
e011:setAnimationCastPoint(0.0)
e011:setMovementType(MovementType.Fly)
e011:setMovementHeightMinimum(275.0)
e011:setMovementHeight(275.0)
e011:setSpeedBase(1)
e011:setSpeedMinimum(0)
e011:setSpeedMaximum(0)
e011:setUnitClassification('ancient')
e011:setHitPointsRegenerationType('always')
e011:setFoodProduced(0)
e011:setHitPointsMaximumBase(1)
e011:setHitPointsRegenerationRate(0.0)
e011:setHideMinimapDisplay(true)
e011:setSightRadiusDay(0)
e011:setSightRadiusNight(0)
e011:setTurnRate(3.0)
e011:setPropulsionWindowdegrees(360.0)
e011:setSelectionScale(0.0)
