--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
---
-- @noSelfInFile
____exports["巴尔扎罗斯单位技能配置"] = {
    ["单位ID"] = "N03G",
    ["单位名"] = "熔岩恶魔王·巴尔扎罗斯",
    ["Boss单位ID"] = "N03G",
    ["护卫"] = {["格鲁姆"] = {
        ["名称"] = "熔岩破坏者·格鲁姆",
        ["单位ID"] = "N03J",
        ["模型路径"] = "Boss\\Balzaroth\\Grum\\Grum.mdx",
        ["图标路径"] = "Boss\\Balzaroth\\Icon\\GrumPortrait.blp",
        ["广播持续时间Ms"] = 3200,
        ["配音裁断距离"] = 4000,
        ["配音生成配置"] = {
            ["显示台词字段"] = "台词",
            ["配音台词字段"] = "配音台词",
            ["声线名称"] = "Azgar - Intimidating Orc Troll",
            ["声线ID"] = "3VkFsBHdRPqWKsitgYhJ",
            ["模型ID"] = "eleven_v3",
            ["语言"] = "en",
            ["整体提示词"] = "A massive demonic orc enforcer in molten heavy armor, fiercely loyal to an infernal king. Deep battle-worn growl, blunt military obedience, crushing physical menace, and clear Warcraft-style combat delivery. Speak at a forceful battle pace with restrained grit. Not comedic, not mindless, not a roaring animal.",
            ["说明"] = "格鲁姆是重甲近战护卫，语气粗粝、忠诚、直接。回应君王时服从但不卑怯；技能台词短促有冲击力，避免拖成长吼。"
        },
        ["台词"] = {["响应召令"] = {"遵命，吾王。（优先处理格鲁姆，避开他的正面锤击与熔岩火线。）"}, ["熔岩重锤"] = {"都趴下！我要把你们砸进地底！（远离格鲁姆正面90°扇形、半径360码的预警区；命中会眩晕1.25秒并叠2层灼热。）"}, ["熔岩火径"] = {"火路已开。无路可退。（避开长640、宽120码的火线；线上每0.25秒叠1层灼热，穿越火线还会受到额外伤害。）"}, ["死亡"] = {"吾王……格鲁姆不能再战了……"}},
        ["配音台词"] = {["响应召令"] = {"[obedient growl] As you command, my king."}, ["熔岩重锤"] = {"[battle roar] Down! I will hammer you into the earth!"}, ["熔岩火径"] = {"[grim] The path burns. There is no retreat."}, ["死亡"] = {"[dying strain] My king... Grum can fight no longer..."}},
        ["配音资源"] = {["响应召令"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_grum_answer_command_01_v3.mp3"}, ["熔岩重锤"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_grum_molten_hammer_01_v3.mp3"}, ["熔岩火径"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_grum_lava_path_01_v3.mp3"}, ["死亡"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_grum_death_01_v3.mp3"}}
    }, ["塞拉"] = {
        ["名称"] = "冰焰巫师·塞拉",
        ["单位ID"] = "N03K",
        ["模型路径"] = "Boss\\Balzaroth\\Sera\\Sera.mdx",
        ["图标路径"] = "Boss\\Balzaroth\\Icon\\SeraPortrait.blp",
        ["默认普攻弹道模型"] = "Abilities\\Weapons\\FrostWyrmMissile\\FrostWyrmMissile.mdl",
        ["火焰普攻弹道模型"] = "Abilities\\Weapons\\RedDragonBreath\\RedDragonMissile.mdl",
        ["普攻弹道弧度"] = 0.15,
        ["普攻弹道速度"] = 900,
        ["普攻弹道自导"] = true,
        ["广播持续时间Ms"] = 3200,
        ["配音裁断距离"] = 4000,
        ["配音生成配置"] = {
            ["显示台词字段"] = "台词",
            ["配音台词字段"] = "配音台词",
            ["声线名称"] = "Altáriel - Storyteller of the Light",
            ["声线ID"] = "oBVK5gDykyUkoVXUPyCU",
            ["模型ID"] = "eleven_v3",
            ["语言"] = "en",
            ["整体提示词"] = "A pale elven battle mage serving an infernal king, wielding frost and flame with cold precision. Low feminine elven timbre, controlled danger, disciplined loyalty, and concise Warcraft-style spellcasting. Keep the delivery clear and combat-paced, with a faint arcane resonance. Not gentle, not pastoral, not a storyteller.",
            ["说明"] = "塞拉是冷静危险的冰焰法师护卫。以低沉精灵女声为底，通过提示词压住森林神谕感；台词强调精准施法、元素控制和克制的忠诚。"
        },
        ["台词"] = {
            ["响应召令"] = {"遵命，陛下。（注意冰焰双星弹道，并准备利用绝对零度领域清除灼热。）"},
            ["冰焰双星"] = {"冰与火，将同时索命。（冰球与火球命中点影响300码范围；冰球减速35%持续3秒，火球叠2层灼热，沿弹道移动躲避。）"},
            ["绝对零度领域"] = {"绝对零度，封锁战场。（进入半径320码领域可清除灼热，但领域内造成的伤害降低15%，离开后仍持续3秒。）"},
            ["元素转换火焰"] = {"冰霜退去，烈焰接管。（火焰形态持续22秒，火焰技能伤害提高25%，受到克制属性伤害提高20%。）"},
            ["元素转换冰霜"] = {"烈焰沉寂，寒冬降临。（冰霜形态持续22秒，冰霜技能伤害提高25%，受到克制属性伤害提高20%。）"},
            ["死亡"] = {"陛下……元素失衡了……"}
        },
        ["配音台词"] = {
            ["响应召令"] = {"[coldly obedient] As you command, my liege."},
            ["冰焰双星"] = {"[cold precision] Ice and flame will claim you together."},
            ["绝对零度领域"] = {"[commanding] Absolute zero. Seal the battlefield."},
            ["元素转换火焰"] = {"[rising intensity] Frost recedes. Flame takes command."},
            ["元素转换冰霜"] = {"[coldly] Flame falls silent. Winter descends."},
            ["死亡"] = {"[fading disbelief] My liege... the elements... are breaking..."}
        },
        ["配音资源"] = {
            ["响应召令"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_sera_answer_command_01_v3.mp3"},
            ["冰焰双星"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_sera_frostfire_twins_01_v3.mp3"},
            ["绝对零度领域"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_sera_absolute_zero_01_v3.mp3"},
            ["元素转换火焰"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_sera_shift_to_flame_01_v3.mp3"},
            ["元素转换冰霜"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_sera_shift_to_frost_01_v3.mp3"},
            ["死亡"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_guard_sera_death_01_v3.mp3"}
        }
    }},
    ["技能壳"] = {["恶魔咆哮波"] = "A0C9", ["熔岩喷发"] = "A0CC", ["王者天罚"] = "A0CA", ["火焰锁链"] = "A0CB"},
    ["主动技能提示"] = {{["技能ID"] = "A0C9", ["提示"] = "恶魔咆哮波", ["扩展提示"] = "施法硬直1.2秒后，向正面发射宽220、长1200码的直线冲击；命中一次造成Boss当前攻击力×200%+目标最大生命值×5%伤害。8秒内第二次命中同一目标会眩晕1秒，命中护卫会恢复其最大生命值8%（护卫模仿版本宽度与伤害均为本体60%）。离开正面路径即可规避。"}, {["技能ID"] = "A0CC", ["提示"] = "熔岩喷发", ["扩展提示"] = "施法硬直1.2秒，目标附近180码内随机落点；1.2秒后在半径260码内爆发，造成Boss攻击力×140%+目标最大生命值×4%伤害并顶飞0.6秒，附加1层灼热。爆发后生成半径240码熔岩残留，持续8秒，每1秒造成目标最大生命值×1%并附加1层灼热。离开红色预警圈并避开残留区。"}, {["技能ID"] = "A0CA", ["提示"] = "王者天罚", ["扩展提示"] = "引导5秒，在第1、3、5秒落下三波天罚；基础落点半径260码，P2扩大为299码，P3每波额外增加2个随机落点（半径220码）。每波造成Boss攻击力×120%+目标最大生命值×4%伤害；同一目标连续命中3波会额外叠2层灼热。离开每次脚下预警圈。"}, {["技能ID"] = "A0CB", ["提示"] = "火焰锁链", ["扩展提示"] = "施法硬直0.9秒，优先点名距Boss至少600码的最远目标，不足600码时随机点名；目标脚下显示半径180码锁定预警。锁链持续8秒，场中生成可攻击锁链单位（最大生命=Boss最大生命值×7%）；Boss与目标距离超过650码时每1秒造成Boss当前攻击力×80%+目标最大生命值×2%伤害。击杀锁链单位，或保持与Boss不超过650码，可结束威胁。"}},
    ["广播持续时间Ms"] = 4200,
    ["配音裁断距离"] = 4000,
    ["配音生成配置"] = {
        ["显示台词字段"] = "台词",
        ["配音台词字段"] = "配音台词",
        ["声线名称"] = "Matthew Schmitz - Unholy, Wicked Demon",
        ["声线ID"] = "rCYFsCX2waxtHCgVD0e8",
        ["模型ID"] = "eleven_v3",
        ["语言"] = "en",
        ["整体提示词"] = "An ancient molten demon king, colossal and heavily armored, with deep infernal resonance, imperious royal command, controlled wrath, and volcanic cavern weight. Speak clearly at battle pace, authoritative rather than theatrical, with restrained rumble and slight stone chamber reverb. Not a mindless beast, not a whispering demon, not a human villain.",
        ["说明"] = "系统消息和广播继续显示中文台词；AI Voice 使用后续确认的英文配音台词。整体表演强调熔岩恶魔王的统治感与清晰度，战斗台词不要拖慢，情绪标签仅适用于 eleven_v3。"
    },
    BuffID = {
        ["灼热"] = "BBZ1",
        ["熔核封印"] = "BBZ2",
        ["火焰锁链"] = "BBZ3",
        ["熔岩护盾"] = "BBZ4",
        ["炙热奉献"] = "BBZ5",
        ["塞拉火焰形态"] = "BBZ6",
        ["塞拉冰霜形态"] = "BBZ7",
        ["熔岩暴走"] = "BBZ8",
        ["绝对零度领域"] = "BBZ9"
    },
    ["模型"] = {Boss = "Boss\\Balzaroth\\Balzaroth.mdx"},
    ["台词"] = {
        ["开场"] = {"地核的锁链，终将为王让路。（优先击杀两名护卫；护卫存活时本体无法移动且受到的最终伤害降低80%。）"},
        ["转阶段2"] = {"护卫已尽，封印松动。（双护卫全部死亡后解除本体80%减伤，巴尔扎罗斯开始移动并进入P2。）"},
        ["转阶段3"] = {"大地开始燃烧。（进入P3后每55秒触发末日熔爆；提前记住固定安全区位置。）"},
        ["死亡"] = {"熔核...不该归于沉寂..."},
        ["熔岩重锤"] = {"格鲁姆，碾碎他们。（远离格鲁姆正面90°扇形、半径360码的预警区；命中会眩晕1.25秒并叠2层灼热。）"},
        ["熔岩火径"] = {"火线会告诉你们边界在哪里。（避开长640、宽120码的火线；线上每0.25秒叠1层灼热，穿越火线会受到额外伤害。）"},
        ["炙热奉献"] = {"把你的余烬献给王。（若出现8秒献祭读条，优先击杀或打断格鲁姆；完成后按设计恢复Boss最大生命值12%。）"},
        ["冰焰双星"] = {"塞拉，让冰火同时坠落。（冰球与火球命中点影响300码范围；冰球减速35%持续3秒，火球叠2层灼热，沿弹道移动躲避。）"},
        ["绝对零度领域"] = {"寒意也要臣服于熔核。（进入半径320码领域可清3层灼热，领域内每1秒再清2层，但造成伤害降低15%，离开后持续3秒。）"},
        ["元素转换"] = {"元素换相，战场重铸。（塞拉每20秒切换火焰/冰霜形态；对应元素技能伤害提高25%，受到克制属性伤害提高20%。）"},
        ["恶魔咆哮波"] = {"听见王的怒吼了吗？（正面宽220、长1200码的直线冲击；离开路径可躲避，8秒内第二次命中会眩晕1秒。）"},
        ["王者天罚"] = {"天罚落下，跪地求生。（第1、3、5秒落下三波，离开脚下预警圈；P2范围扩大15%，P3每波额外增加2个随机落点。）"},
        ["熔岩喷发"] = {"地底已经醒来。（脚下预警1.2秒后在半径260码内爆发；离开预警圈，并避开爆发后的半径240码熔岩残留8秒。）"},
        ["火焰锁链"] = {"锁住他。（优先攻击场中的锁链单位，或保持与Boss距离不超过650码；超距时每1秒受到伤害。）"},
        ["地核召唤"] = {"地核仆从，苏醒。（地核每3秒为全场叠1层灼热；优先击破地核，击破后会掉落冷却水晶。）"},
        ["熔岩护盾"] = {"熔岩即我的甲胄。（护盾持续10秒、吸收Boss最大生命值7%的伤害；近战攻击会反弹，冰霜伤害更易破盾。）"},
        ["末日熔爆"] = {"站进安全区，或者成为下一层岩浆。（引导6秒后结算；进入固定安全区可规避外圈95%最大生命值+Boss攻击力×200%的伤害。）"},
        ["末日熔爆中途"] = {"还剩一息，安全区不会等人。（距离爆发还有3秒，立即进入固定安全区。）"},
        ["末日熔爆爆发"] = {"看，这就是地核的呼吸。（伤害已经结算；安全区内仅承受目标最大生命值×12%的余波并清除3层灼热。）"}
    },
    ["配音台词"] = {
        ["开场"] = {"[commanding, restrained fury] The chains of the molten core will yield before their king."},
        ["转阶段2"] = {"[low satisfaction] My guards have fallen... [rising menace] and with them, the seal begins to break."},
        ["转阶段3"] = {"[growing wrath] The earth itself... [triumphant] now burns at my command."},
        ["死亡"] = {"[shocked, weakening] The molten core... [fading disbelief] cannot fall silent..."},
        ["熔岩重锤"] = {"[commanding] Grum. Crush them."},
        ["熔岩火径"] = {"[cold warning] Let the line of flame teach you where your world ends."},
        ["炙热奉献"] = {"[imperious] Yield your embers to your king."},
        ["冰焰双星"] = {"[commanding] Sera. Let frost and flame fall as one."},
        ["绝对零度领域"] = {"[contemptuous] Even the cold must kneel before the molten core."},
        ["元素转换"] = {"[arcane command] Let the elements turn. [rising power] Reforge this battlefield."},
        ["恶魔咆哮波"] = {"[taunting] Do you hear it? [infernal fury] The wrath of your king!"},
        ["王者天罚"] = {"[royal condemnation] Judgment descends. [merciless] Kneel... and beg to survive."},
        ["熔岩喷发"] = {"[ominous] The depths... have awakened."},
        ["火焰锁链"] = {"[sharp command] Bind them."},
        ["地核召唤"] = {"[summoning command] Servants of the core... awaken."},
        ["熔岩护盾"] = {"[unyielding] Molten fire is my armor."},
        ["末日熔爆"] = {"[coldly commanding] Enter the sanctuary... [volcanic menace] or become another layer of molten stone."},
        ["末日熔爆中途"] = {"[pressing menace] One breath remains. [cold] The sanctuary will not wait."},
        ["末日熔爆爆发"] = {"[dark awe] Behold... [volcanic triumph] the breath of the molten core."}
    },
    ["配音资源"] = {
        ["开场"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_opening_molten_core_king_unholy_01_v3.mp3"},
        ["转阶段2"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_phase2_guards_fallen_seal_breaks_01_v3.mp3"},
        ["转阶段3"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_phase3_earth_burns_command_01_v3.mp3"},
        ["死亡"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_death_molten_core_silence_01_v3.mp3"},
        ["熔岩重锤"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_molten_hammer_command_01_v3.mp3"},
        ["熔岩火径"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_lava_path_boundary_01_v3.mp3"},
        ["炙热奉献"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_searing_offering_embers_01_v3.mp3"},
        ["冰焰双星"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_frostfire_twins_command_01_v3.mp3"},
        ["绝对零度领域"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_absolute_zero_submission_01_v3.mp3"},
        ["元素转换"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_element_shift_reforge_01_v3.mp3"},
        ["恶魔咆哮波"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_demonic_roar_wave_wrath_01_v3.mp3"},
        ["王者天罚"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_royal_judgment_kneel_01_v3.mp3"},
        ["熔岩喷发"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_lava_eruption_depths_awaken_01_v3.mp3"},
        ["火焰锁链"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_flame_chains_bind_01_v3.mp3"},
        ["地核召唤"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_core_summon_servants_awaken_01_v3.mp3"},
        ["熔岩护盾"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_molten_shield_armor_01_v3.mp3"},
        ["末日熔爆"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_doom_meltdown_sanctuary_warning_01_v3.mp3"},
        ["末日熔爆中途"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_doom_meltdown_one_breath_01_v3.mp3"},
        ["末日熔爆爆发"] = {"Sound\\Boss\\Balzaroth\\Voice\\balzaroth_doom_meltdown_core_breath_01_v3.mp3"}
    }
}
return ____exports
