--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
local ____00_FF0EBuff_767B_8BB0 = require("系统.05．Buff系统.03．Buff表.00．Buff登记")
local _____5E38_89C4BuffID = ____00_FF0EBuff_767B_8BB0["常规BuffID"]
____exports["菲利斯装备Buff表"] = {[_____5E38_89C4BuffID["菲利斯的统御纹章_统御号令"]] = {
    buffID = _____5E38_89C4BuffID["菲利斯的统御纹章_统御号令"],
    buffName = "统御号令",
    icon = "Equipment\\Icon\\Item\\phyllis_command_emblem.blp",
    effect = "",
    type = "Buff:equipment:attribute",
    interval = 0,
    maxStack = 1,
    stackRule = "highest",
    stackRefresh = true,
    dispelLevel = 0,
    priority = 5,
    canPurge = false,
    tooltip = "受到了「统御号令」，在time秒内魔法伤害提高data%。"
}, [_____5E38_89C4BuffID["攻城号令圣印_攻城号令"]] = {
    buffID = _____5E38_89C4BuffID["攻城号令圣印_攻城号令"],
    buffName = "攻城号令",
    icon = "Equipment\\Icon\\Item\\siege_command_signet.blp",
    effect = "",
    type = "Buff:equipment:attribute",
    interval = 0,
    maxStack = 1,
    stackRule = "highest",
    stackRefresh = true,
    dispelLevel = 0,
    priority = 5,
    canPurge = false,
    tooltip = "受到了「攻城号令」，在time秒内受到的治疗效果提高data%。"
}, [_____5E38_89C4BuffID["净化者手套_净化增幅"]] = {
    buffID = _____5E38_89C4BuffID["净化者手套_净化增幅"],
    buffName = "净化增幅",
    icon = "Equipment\\Icon\\Gloves\\purifier_gloves.blp",
    effect = "",
    type = "Buff:equipment:attribute",
    interval = 0,
    maxStack = 1,
    stackRule = "highest",
    stackRefresh = true,
    dispelLevel = 0,
    priority = 5,
    canPurge = false,
    tooltip = "受到了「净化增幅」，在time秒内技能治疗效率提高data%。"
}}
____exports.default = ____exports["菲利斯装备Buff表"]
return ____exports
