--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports["米亚Buff表"] = {BMI1 = {
    buffID = "BMI1",
    buffName = "腐化感染",
    icon = "BuffIcon\\Boss\\Mia\\corruption_infection.blp",
    effect = "Units\\Undead\\PlagueCloud\\PlagueCloudtarget.mdl",
    effectMode = "attach",
    effectAttachPoint = "origin",
    type = "Debuff:poison",
    interval = 0,
    maxStack = 15,
    stackRule = "stack",
    stackRefresh = true,
    dispelLevel = 3,
    priority = 85,
    canPurge = false,
    tooltip = "受到米亚的腐化感染：每层受到米亚相关伤害提高2%、受到治疗效果降低4%。满15层时伤害提高30%、治疗降低60%；终极污染完成时达到15层会立即死亡。"
}, BMI2 = {
    buffID = "BMI2",
    buffName = "污染标记",
    icon = "BuffIcon\\Boss\\Mia\\pollution_mark.blp",
    effect = "",
    type = "Debuff:mark",
    interval = 0,
    maxStack = 1,
    stackRule = "highest",
    stackRefresh = true,
    dispelLevel = 3,
    priority = 90,
    canPurge = false,
    tooltip = "被米亚标记为污染最重的目标：米亚对你造成的伤害提高20%；若你死亡，米亚恢复10%最大生命值。"
}, BMI3 = {
    buffID = "BMI3",
    buffName = "平台超载",
    icon = "BuffIcon\\Boss\\Mia\\platform_overload.blp",
    effect = "",
    type = "Debuff:field",
    interval = 0,
    maxStack = 1,
    stackRule = "highest",
    stackRefresh = true,
    dispelLevel = 3,
    priority = 88,
    canPurge = false,
    tooltip = "所在平台人数超过容量：每秒额外获得1层腐化感染，且米亚对你造成的伤害提高30%。"
}, BMI4 = {
    buffID = "BMI4",
    buffName = "腐化黏液涂层",
    icon = "BuffIcon\\Boss\\Mia\\corrupt_slime_coating.blp",
    effect = "",
    type = "Buff:boss",
    interval = 0,
    maxStack = 1,
    stackRule = "highest",
    stackRefresh = true,
    dispelLevel = 3,
    priority = 86,
    canPurge = false,
    tooltip = "米亚被腐化黏液覆盖：近战攻击米亚者每次获得1层腐化感染；米亚每10秒向全场甩出黏液，使所有玩家获得1层腐化感染；米亚受到的伤害提高20%。"
}}
____exports.default = ____exports["米亚Buff表"]
return ____exports
