--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.TASK_UI_TOC_PATHS = {"UI\\TaskUI.toc"}
____exports.TASK_UI_TOC_LOAD_KEY = "TaskUI"
--- 二分开关：关则任务UI客户端不初始化
____exports.ENABLE_TASK_UI_CLIENT = true
____exports.ENABLE_FDF_A = true
____exports.ENABLE_FDF_B = true
____exports.ENABLE_FDF_SCROLLBAR = true
____exports.ENABLE_FDF_SCROLLBAR_BORDER = true
____exports.ENABLE_FDF_SCROLLBAR_THUMB = true
____exports.ENABLE_MOUSE_WHEEL_SCROLL = true
--- 每分类预设最大页数（用于固定次数遍历隐藏，不依赖 pages.length）
____exports.MAX_PAGES_PER_CATEGORY = 20
--- 二分开关：关则主面板不创建右侧滚动轨道/滑块/拖拽命中（排除 VerticalScrollbarTrack 常驻逻辑）
____exports.ENABLE_TASK_UI_RIGHT_SCROLLBAR = true
____exports.ENTRY_W = 0.059 * 1.3
____exports.ENTRY_H = 0.0156 * 1.4
____exports.ENTRY_X = 0.005
____exports.ENTRY_Y = 0.6
____exports.ENTRY_TITLE_TEXT_BOX_W = 0.82
____exports.ENTRY_TITLE_TEXT_BOX_H = 0.46
____exports.PANEL_W = 0.35
____exports.PANEL_H = 0.5
____exports.TAB_FRAME_W = 0.04
____exports.TAB_FRAME_H = 0.035
____exports.TAB_CATEGORY_FONT_SCALE = 0.012
____exports.LIST_ITEM_H = 0.12
____exports.BG_TEX = "UI\\Widgets\\EscMenu\\Human\\human-options-menu-background.blp"
____exports.PANEL_TOP = 0.46
____exports.PANEL_TOP_UP = 0.015
____exports.LEGACY_ENTRY_X_REF = 0.06
____exports.LEGACY_ENTRY_Y_REF = 0.51
____exports.LEGACY_PANEL_TOP_Y = ____exports.PANEL_TOP + ____exports.PANEL_TOP_UP
____exports.LEGACY_LIST_TOP = 0.41 + ____exports.PANEL_TOP_UP - 0.04
____exports.PANEL_TOPLEFT_OFF_X = 0
____exports.PANEL_TOPLEFT_OFF_Y = ____exports.LEGACY_PANEL_TOP_Y - ____exports.LEGACY_ENTRY_Y_REF
____exports.PANEL_EXPANDED_UP = 0.015
____exports.PANEL_REL_TO_ENTRY_X = ____exports.PANEL_TOPLEFT_OFF_X
____exports.PANEL_REL_TO_ENTRY_Y = ____exports.PANEL_TOPLEFT_OFF_Y + ____exports.PANEL_EXPANDED_UP
____exports.LIST_FIRST_ROW_REL_Y = ____exports.LEGACY_LIST_TOP - ____exports.LEGACY_PANEL_TOP_Y
____exports.LIST_ROW_LEFT_REL_X = 0.09 - ____exports.LEGACY_ENTRY_X_REF - 0.01
____exports.TAB_Y = 0.44
____exports.TAB_REL_Y = ____exports.TAB_Y - ____exports.PANEL_TOP
____exports.COLLAPSED_ROW_PITCH = ____exports.LIST_ITEM_H * 0.4 + 0.01
____exports.LIST_VIEW_TARGET_ROWS = 7
____exports.LIST_VIEW_H = ____exports.COLLAPSED_ROW_PITCH * ____exports.LIST_VIEW_TARGET_ROWS + 0.012
____exports.SCROLLBAR_BOTTOM_INSET = 0.03
____exports.SCROLLBAR_TOP_INSET = ____exports.PANEL_H - ____exports.LIST_VIEW_H - ____exports.SCROLLBAR_BOTTOM_INSET
____exports.LIST_CONTAINER_REL_TO_PANEL_X = 0.015
____exports.LIST_CONTAINER_REL_TO_PANEL_Y = -0.1
____exports.LIST_CONTENT_LEFT_INSET = ____exports.LIST_ROW_LEFT_REL_X - ____exports.LIST_CONTAINER_REL_TO_PANEL_X
____exports.LIST_CONTENT_TOP_INSET = ____exports.LIST_FIRST_ROW_REL_Y - ____exports.LIST_CONTAINER_REL_TO_PANEL_Y + 0.025
____exports.LIST_CONTAINER_W = 0.32
____exports.SCROLLBAR_W = 0.015
____exports.SCROLLBAR_REL_X = -0.006 - 0.005 - 0.004
____exports.SCROLL_THUMB_SIZE = 0.02
____exports.SCROLL_THUMB_TOP_COMPENSATION = 0
____exports.SCROLL_THUMB_BOTTOM_COMPENSATION = 0
____exports.THUMB_DRAG_TICK = 0.03
____exports.THUMB_DRAG_SENSITIVITY = 1
____exports.QUEST_ROW_ICON_HEIGHT_FACTOR = 0.84
____exports.QUEST_ROW_ICON_PAD_LEFT = 0.003
____exports.QUEST_ROW_TEXT_GAP_AFTER_ICON = 0.006
____exports.QUEST_ROW_ICON_Y_OFFSET = 0.004
return ____exports
