--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
---
-- @noSelfInFile
____exports["莫尔特斯模型动画配置"] = {["模型路径"] = "Boss\\Moltes\\Moltes.mdx", ["动画序列"] = {
    {
        ["编号"] = 0,
        ["名称"] = "Stand",
        ["原始时长秒"] = 1.833,
        ["循环"] = true,
        ["语义"] = "待机"
    },
    {
        ["编号"] = 1,
        ["名称"] = "Stand 2",
        ["原始时长秒"] = 3.567,
        ["循环"] = true,
        ["语义"] = "待机变化"
    },
    {
        ["编号"] = 2,
        ["名称"] = "Stand 3",
        ["原始时长秒"] = 4.034,
        ["循环"] = true,
        ["语义"] = "约 1 秒后进入双臂抬起姿势"
    },
    {
        ["编号"] = 3,
        ["名称"] = "Stand 4",
        ["原始时长秒"] = 3.633,
        ["循环"] = true,
        ["语义"] = "抖动身体"
    },
    {
        ["编号"] = 4,
        ["名称"] = "Stand Ready",
        ["原始时长秒"] = 1.4,
        ["循环"] = true,
        ["语义"] = "战斗待机"
    },
    {
        ["编号"] = 5,
        ["名称"] = "Attack",
        ["原始时长秒"] = 1,
        ["循环"] = false,
        ["语义"] = "向右前方横扫"
    },
    {
        ["编号"] = 6,
        ["名称"] = "Attack 2",
        ["原始时长秒"] = 1,
        ["循环"] = false,
        ["语义"] = "双手举起后砸向地面"
    },
    {
        ["编号"] = 7,
        ["名称"] = "Death",
        ["原始时长秒"] = 3.333,
        ["循环"] = false,
        ["语义"] = "死亡"
    },
    {
        ["编号"] = 8,
        ["名称"] = "Walk",
        ["原始时长秒"] = 1.434,
        ["循环"] = true,
        ["语义"] = "行走"
    }
}}
____exports["莫尔特斯数值与表现配置"] = {
    ["运行时"] = {["推进间隔毫秒"] = 1000},
    ["阶段阈值"] = {["P2生命比例"] = 0.7, ["P3生命比例"] = 0.4},
    ["腐败值"] = {
        ["上限"] = 100,
        ["缠绕阈值"] = 100,
        ["Buff显示秒"] = 120,
        ["满层缠绕秒"] = 4,
        ["满层缠绕目标已损生命比例"] = 0.1,
        ["满层缠绕Boss攻击力比例"] = 0.5,
        ["净化光斑每秒清除"] = 10,
        ["虫尸清除值"] = 30
    },
    ["根须领域"] = {
        ["行数"] = 3,
        ["列数"] = 3,
        ["中心X"] = 5392,
        ["中心Y"] = -12976,
        ["单格边长"] = 512,
        ["闪电效果"] = "DRAB",
        ["闪电高度"] = 80
    },
    ["腐朽根须穿刺"] = {
        ["技能槽位"] = "AN00",
        ["动画编号"] = 6,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1,
        ["动作播放秒"] = 1,
        ["预警秒"] = 1.5,
        ["区域数量"] = 3,
        ["腐败值"] = 15,
        ["根须停留秒"] = 5,
        ["Boss攻击力比例"] = 1.2,
        ["根须特效路径"] = "Common\\Effect\\Element\\Nature\\RottenRootImpale.mdx",
        ["根须模型动画索引"] = 0,
        ["根须特效缩放"] = 2.2,
        ["穿刺特效路径"] = "Abilities\\Spells\\Undead\\Impale\\ImpaleHitTarget.mdl",
        ["穿刺命中特效缩放"] = 2,
        ["瞬时特效持续秒"] = 2
    },
    ["腐败孢子云"] = {
        ["技能槽位"] = "AN01",
        ["动画编号"] = 3,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 3.633,
        ["动作播放秒"] = 3,
        ["数量"] = 3,
        ["基础生命值"] = 2000,
        ["Boss最大生命比例"] = 0.03,
        ["每秒腐败值"] = 10,
        ["持续秒"] = 10,
        ["Tick间隔毫秒"] = 1000,
        ["半径"] = 200,
        ["移动距离"] = 200,
        ["每秒目标最大生命比例"] = 0.04,
        ["单位类型"] = "hfoo",
        ["模型路径"] = "units\\undead\\PlagueCloud\\PlagueCloud.mdl",
        ["受小怪倍率生命"] = false,
        ["缩放"] = 1,
        ["命中特效路径"] = "Common\\Effect\\Element\\Nature\\MoltesCorruptionTick.mdx",
        ["瞬时特效持续秒"] = 1.2
    },
    ["扭曲荆棘鞭笞"] = {
        ["技能槽位"] = "AT12",
        ["动画编号"] = 5,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1,
        ["动作播放秒"] = 1,
        ["藤蔓数量"] = 3,
        ["扫击次数"] = 3,
        ["开始延迟秒"] = 1.5,
        ["波次间隔秒"] = 1.5,
        ["预警秒"] = 1,
        ["矩形宽度"] = 512,
        ["矩形长度"] = 1536,
        ["Boss攻击力比例"] = 1,
        ["重复命中增伤比例"] = 0.3,
        ["寄生持续秒"] = 12,
        ["寄生每跳Boss攻击力比例"] = 0.2,
        ["寄生伤害间隔秒"] = 3,
        ["藤蔓模型路径"] = "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
        ["藤蔓缩放"] = 2,
        ["触手攻击动画索引"] = 2,
        ["触手下俯角度"] = 40,
        ["路径荆棘模型路径列表"] = {
            "Doodads\\Felwood\\Plants\\Felwood_Thorns\\Felwood_Thorns0.mdl",
            "Doodads\\Felwood\\Plants\\Felwood_Thorns\\Felwood_Thorns1.mdl",
            "Doodads\\Felwood\\Plants\\Felwood_Thorns\\Felwood_Thorns2.mdl",
            "Doodads\\Felwood\\Plants\\Felwood_Thorns\\Felwood_Thorns3.mdl",
            "Doodads\\Felwood\\Plants\\Felwood_Thorns\\Felwood_Thorns4.mdl"
        },
        ["路径荆棘缩放"] = 2,
        ["路径爆点特效路径"] = "war3mapImported\\explosion.mdl",
        ["瞬时特效持续秒"] = 2
    },
    ["腐败之种"] = {
        ["技能槽位"] = "BT08",
        ["动画编号"] = 5,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1,
        ["动作播放秒"] = 1,
        ["飞行秒"] = 1.2,
        ["弹道刷新间隔毫秒"] = 50,
        ["弧线高度"] = 260,
        ["中点偏移比例"] = 0.25,
        ["生长延迟秒"] = 3,
        ["波动半径"] = 360,
        ["波动间隔秒"] = 1,
        ["持续秒"] = 18,
        ["每跳腐败值"] = 8,
        ["每跳Boss攻击力比例"] = 0.35,
        ["种子单位类型"] = "hfoo",
        ["幼树单位类型"] = "hfoo",
        ["种子生命值"] = 350,
        ["幼树生命值"] = 1400,
        ["投射物模型路径"] = "war3mapImported\\StrangeSeeds.MDX",
        ["投射物缩放"] = 2,
        ["落地种子缩放"] = 1.7,
        ["强化进度UI高度"] = 220,
        ["强化进度刷新间隔毫秒"] = 100,
        ["幼树Tick特效路径"] = "Common\\Effect\\Element\\Nature\\MoltesCorruptionTick.mdx",
        ["幼树Tick特效持续秒"] = 1.2,
        ["幼树模型路径"] = "war3mapImported\\g1 (4).mdx",
        ["幼树缩放"] = 1.25
    },
    ["根系觉醒"] = {
        ["动画编号"] = 2,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 4.034,
        ["动作播放秒"] = 4.034,
        ["显形动作秒"] = 1.2,
        ["腐败之源数量"] = 3,
        ["限时秒"] = 30,
        ["失败回血比例"] = 0.15,
        ["腐败之源单位类型"] = "hfoo",
        ["腐败之源生命值"] = 2600,
        ["腐败之源模型路径"] = "Common\\Model\\Monster\\Mortus\\CorruptionSource\\CorruptionSource.mdx",
        ["腐败之源缩放"] = 1.45,
        ["腐败之源脚下特效路径"] = "Common\\Effect\\Form\\MagicCircle\\CorruptionSourceCircle.mdx",
        ["腐败之源摧毁特效路径"] = "Common\\Effect\\Form\\Explosion\\CorruptionSourceBurst.mdx",
        ["腐败之源摧毁特效缩放"] = 1.5,
        ["全屏爆发特效路径"] = "Common\\Effect\\Element\\Nature\\EarthNova.mdx",
        ["全屏爆发特效缩放"] = 1.5,
        ["瞬时特效持续秒"] = 2,
        ["全屏爆发伤害Boss攻击力比例"] = 2.2,
        ["全屏爆发腐败值"] = 25
    },
    ["腐朽领域"] = {
        ["动画编号"] = 6,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 1,
        ["动作播放秒"] = 1,
        ["减速比例"] = 0.3,
        ["根须触发间隔秒"] = 5,
        ["根须结算延迟毫秒"] = 1000,
        ["沼泽腐败间隔秒"] = 1,
        ["沼泽每跳腐败值"] = 5,
        ["沼泽Tick特效路径"] = "Common\\Effect\\Element\\Nature\\MoltesCorruptionTick.mdx",
        ["沼泽Tick特效缩放"] = 7,
        ["沼泽Tick特效持续秒"] = 1.2,
        ["沼泽贴图类型"] = "ULAR",
        ["沼泽贴图颜色"] = {r = 100, g = 100, b = 100, a = 0},
        ["沼泽贴图强制暂停"] = false,
        ["沼泽贴图无出生时间"] = false,
        ["沼泽贴图覆盖行数"] = 4,
        ["沼泽贴图覆盖列数"] = 4,
        ["净化符文数量"] = 4,
        ["净化符文半径"] = 260,
        ["净化持续秒"] = 8,
        ["净化符文模型路径"] = "Common\\Effect\\Form\\MagicCircle\\GaiaShield.mdx"
    },
    ["共生腐朽虫群"] = {
        ["动画编号"] = 3,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 3.633,
        ["动作播放秒"] = 1.5,
        ["触发间隔秒"] = 18,
        ["甲虫数量"] = 4,
        ["甲虫单位类型"] = "hfoo",
        ["甲虫模型路径"] = "units\\undead\\scarab\\scarab.mdl",
        ["甲虫生命值"] = 650,
        ["甲虫攻击力"] = 85,
        ["甲虫缩放"] = 0.9,
        ["接触半径"] = 150,
        ["追击刷新间隔毫秒"] = 1000,
        ["接触爆炸秒"] = 2,
        ["爆炸腐败值"] = 20,
        ["爆炸伤害Boss攻击力比例"] = 0.8,
        ["爆炸特效路径"] = "Common\\Effect\\Form\\Explosion\\MoltesCorruptionBeetleBurst.mdx",
        ["爆炸特效缩放"] = 1,
        ["爆炸特效持续秒"] = 2,
        ["虫尸模型路径"] = "units\\undead\\scarab\\scarab.mdl",
        ["虫尸持续秒"] = 18,
        ["虫尸死亡后延迟秒"] = 2,
        ["虫尸特效播放速度"] = 100,
        ["虫尸特效冻结延迟秒"] = 0.02,
        ["虫尸特效正常播放速度"] = 1,
        ["虫尸拾取驱散特效路径"] = "Abilities\\Spells\\Human\\DispelMagic\\DispelMagicTarget.mdl",
        ["虫尸拾取驱散特效缩放"] = 2,
        ["虫尸拾取驱散特效持续秒"] = 1,
        ["虫尸拾取半径"] = 160,
        ["测试击杀间隔毫秒"] = 200
    },
    ["古木悲鸣"] = {
        ["技能槽位"] = "AN02",
        ["动画编号"] = 2,
        ["动画速度"] = 1,
        ["动作原始时长秒"] = 4.034,
        ["动作播放秒"] = 4.034,
        ["腐败值"] = 25,
        ["恐惧阈值"] = 60,
        ["恐惧秒"] = 3,
        ["悲鸣特效路径"] = "Common\\Effect\\Element\\Nature\\gaiawave.mdx",
        ["悲鸣特效缩放"] = 1.4,
        ["弹幕速度"] = 1000,
        ["弹幕生命周期秒"] = 1.6,
        ["弹幕最大距离"] = 1400,
        ["弹幕命中半径"] = 160,
        ["目标最大生命比例"] = 0.4,
        ["瞬时特效持续秒"] = 2,
        ["蘑菇数量"] = 3,
        ["蘑菇同通道上限"] = 2,
        ["巨型蘑菇模型列表"] = {"Doodads\\Ashenvale\\Plants\\AshenShrooms\\AshenShrooms0.mdl", "Doodads\\Ashenvale\\Plants\\AshenShrooms\\AshenShrooms1.mdl", "Doodads\\Ashenvale\\Plants\\AshenShrooms\\AshenShrooms2.mdl", "Doodads\\Ashenvale\\Plants\\AshenShrooms\\AshenShrooms3.mdl"},
        ["巨型蘑菇缩放"] = 6,
        ["技能结束后蘑菇延迟删除秒"] = 2,
        ["蘑菇遮挡半径"] = 180,
        ["蘑菇遮挡角度"] = 24,
        ["蘑菇安全扇形半径"] = 512,
        ["安全区护盾特效路径"] = "Common\\Effect\\Form\\Shield\\JNTX (82).mdx",
        ["安全区护盾特效缩放"] = 1,
        ["安全区护盾持续秒"] = 2
    },
    ["腐败传输"] = {
        ["每档生命比例"] = 0.05,
        ["转移腐败值"] = 10,
        ["护盾持续秒"] = 10,
        ["护盾目标已损生命比例"] = 0.5,
        ["护盾最低值"] = 1000,
        ["连线效果"] = "DRAB",
        ["连线持续秒"] = 0.7,
        ["连线Tick间隔毫秒"] = 20,
        ["连线起点高度"] = 0,
        ["连线终点高度"] = 0,
        ["护盾破裂特效路径"] = "Common\\Effect\\Form\\Explosion\\CorruptionShieldBreak.mdx",
        ["护盾破裂特效持续秒"] = 1.2
    }
}
____exports["莫尔特斯音效配置"] = {
    ["默认裁断距离"] = 2800,
    ["怪物拟声"] = {
        ["标识"] = "MoltesCreature",
        ["音效路径列表"] = {"Sound\\Boss\\Moltes\\SFX\\moltes_corrupted_tree_creature_moan_01_80k.mp3", "Sound\\Boss\\Moltes\\SFX\\moltes_corrupted_tree_creature_moan_02_80k.mp3", "Sound\\Boss\\Moltes\\SFX\\moltes_corrupted_tree_creature_moan_03_80k.mp3"},
        ["冷却Ms"] = 9000,
        ["关键机制触发概率百分比"] = 55,
        ["转阶段触发概率百分比"] = 100
    },
    ["腐败值"] = {["满层缠绕"] = "Sound\\Boss\\Moltes\\SFX\\moltes_corruption_full_root_bind_02.mp3"},
    ["腐朽根须穿刺"] = {["结算"] = "Sound\\Boss\\Moltes\\SFX\\moltes_rotten_root_impale_barrier_13.mp3"},
    ["腐败孢子云"] = {["成形"] = "Sound\\Boss\\Moltes\\SFX\\moltes_spore_cloud_bloom_form_01.mp3"},
    ["扭曲荆棘鞭笞"] = {["扫击"] = "Sound\\Boss\\Moltes\\SFX\\moltes_twisted_thorn_lash_sweep_01.mp3"},
    ["腐败之种"] = {["扎根成长"] = "Sound\\Boss\\Moltes\\SFX\\moltes_corruption_seed_root_sapling_01.mp3"},
    ["根系觉醒"] = {["机制开始"] = "Sound\\Boss\\Moltes\\SFX\\moltes_root_awaken_sources_rise_03.mp3", ["腐败之源摧毁"] = "Sound\\Boss\\Moltes\\SFX\\moltes_corruption_source_shatter_05_softened.mp3", ["失败爆发"] = "Sound\\Boss\\Moltes\\SFX\\moltes_root_awaken_fail_roots_nova_overlap_02.mp3"},
    ["腐朽领域"] = {["展开"] = "Sound\\Boss\\Moltes\\SFX\\moltes_rotten_domain_marsh_runes_open_07_ducked_dang_80k.mp3"},
    ["共生腐朽虫群"] = {["甲虫入场"] = "Sound\\Boss\\Moltes\\SFX\\moltes_symbiotic_rotten_beetles_spawn_07_puchi_clear.mp3"},
    ["古木悲鸣"] = {["悲鸣波"] = "Sound\\Boss\\Moltes\\SFX\\moltes_ancient_tree_lament_fear_wave_06_water_muted_swarm.mp3"},
    ["腐败传输"] = {["护盾增长"] = "Sound\\Boss\\Moltes\\SFX\\moltes_corruption_transfer_shield_gain_04_tail_heavy_soft.mp3"}
}
return ____exports
