/** @noSelfInFile */

export type 祖地双灵卫名称 = '赤誓灵卫' | '苍影灵卫';

export const 祖地双灵卫单位技能配置 = {
  BossKey: 'AncestralTwinSpiritGuards',
  战斗名称: '祖地双灵卫',
  单位: {
    赤誓灵卫: {
      BossKey: 'AncestralRedOathGuard',
      正常名称: '赤誓灵卫',
      变异名称: '裂誓战躯',
      单位ID: 'U00F',
      变异单位ID: 'U00B',
      正常模型路径: 'Boss\\AncestralTwinSpiritGuards\\RedOathGuard.mdx',
      变异模型路径: 'Boss\\AncestralTwinSpiritGuards\\RedOathMutant.mdx',
      正常头像路径: 'Boss\\AncestralTwinSpiritGuards\\Icon\\BTNRedOathGuard.blp',
      变异头像路径: 'Boss\\AncestralTwinSpiritGuards\\Icon\\BTNRedOathMutant.blp',
      广播持续时间Ms: 3800,
      配音裁断距离: 4000,
      配音生成配置: {
        显示台词字段: '台词',
        配音台词字段: '配音台词',
        声线名称: '已确认男性声线',
        声线ID: 'V33LkP9pVLdcjeB2y5Na',
        模型ID: 'eleven_v3',
        语言: 'en',
        整体提示词: 'An ancient male elven oath-guard preserved as a disciplined spirit projection. Controlled British nobility, shield-bearing authority, restrained battlefield force, and centuries of exhausted duty. His normal form is precise and protective; corruption fractures commands into heavy, compulsive gatekeeping without turning him into a gleeful villain or mindless monster. Clear dark-fantasy combat diction, firm pace, subtle spectral resonance.',
        说明: '赤誓灵卫以王庭守卫式的克制男声为底。正常形态强调誓约、承伤和秩序；裂誓战躯仍保留守门职责，但语句会断裂、重复并带武魂过载的痛苦。净化收束恢复疲惫而清醒的人格。',
      },
      台词: {
        开场: ['祖地封门仍在。生者，止步。'],
        双灵同誓: ['苍影，守住你的灵识。我来承受。'],
        誓锋壁进: ['誓盾向前。越界者，退。'],
        盾刃裁决: ['盾定其罪，刃行其决。'],
        首次变异: ['不……武魂正在吞没誓约。离我远些！'],
        断誓践踏: ['誓约……不能断。闯入者，全部退下！'],
        裂魂坠斩: ['连灵魂，也不得越过此门！'],
        P3双蚀共鸣: ['双誓未灭……守门！'],
        双钥净化破壳: ['污染外壳……判定：击碎。'],
        封门误判: ['封门判定：入侵。执行肃清！'],
        同息回灌: ['还不能倒下……把我的魂力拿去。'],
        灵魂崩解: ['誓约……尚未完成……'],
        净化收束: ['那就证明……这一次，你们不会再让祖地关闭。'],
      },
      配音台词: {
        开场: ['[stern ancient command] The ancestral gate still stands. Living ones... halt.'],
        双灵同誓: ['[protective command] Azure, hold fast to your spirit. I will bear the weight.'],
        誓锋壁进: ['[fierce command] The oath-shield advances. Trespassers... fall back!'],
        盾刃裁决: ['[unyielding judgment] The shield names your guilt. The blade delivers the sentence!'],
        首次变异: ['[pained resistance] No... my battle-spirit is devouring the oath. [fierce warning] Stay away from me!'],
        断誓践踏: ['[fractured command] The oath... cannot break. [thunderous warning] All intruders, withdraw!'],
        裂魂坠斩: ['[corrupted fury] Not even your souls will pass this gate!'],
        P3双蚀共鸣: ['[strained, hollow] The twin oath endures... Guard the gate!'],
        双钥净化破壳: ['[strained protocol] Corrupted shell identified... [forceful command] destroy it!'],
        封门误判: ['[cold protocol] Gate judgment: intrusion. [rising fury] Execute the purge!'],
        同息回灌: ['[desperate resolve] You will not fall yet. Take what remains of my spirit.'],
        灵魂崩解: ['[fading duty] The oath... is not yet fulfilled...'],
        净化收束: ['[weary resolve] Then prove it... [quiet warning] Do not let the ancestral land close again.'],
      },
      配音资源: {
        开场: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_opening_gate_halt_01_v3.mp3'],
        双灵同誓: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_twin_oath_bear_weight_01_v3.mp3'],
        誓锋壁进: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_oathwall_advance_01_v3.mp3'],
        盾刃裁决: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_shieldblade_judgment_01_v3.mp3'],
        首次变异: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_first_mutation_spirit_devours_oath_01_v3.mp3'],
        断誓践踏: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_broken_oath_stomp_withdraw_01_v3.mp3'],
        裂魂坠斩: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_soulfall_slash_gate_01_v3.mp3'],
        P3双蚀共鸣: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_phase3_twin_oath_endures_01_v3.mp3'],
        双钥净化破壳: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_dual_key_break_shell_01_v3.mp3'],
        封门误判: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_gate_misjudgment_purge_01_v3.mp3'],
        同息回灌: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_shared_breath_restore_01_v3.mp3'],
        灵魂崩解: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_soul_collapse_oath_unfinished_01_v3.mp3'],
        净化收束: ['Sound\\Boss\\AncestralRedOathGuard\\Voice\\red_oath_purified_prove_gate_01_v3.mp3'],
      },
    },
    苍影灵卫: {
      BossKey: 'AncestralAzureShadeGuard',
      正常名称: '苍影灵卫',
      变异名称: '无面祷影',
      单位ID: 'U00E',
      变异单位ID: 'U00D',
      正常模型路径: 'Boss\\AncestralTwinSpiritGuards\\AzureShadeGuard.mdx',
      变异模型路径: 'Boss\\AncestralTwinSpiritGuards\\AzureShadeMutant.mdx',
      正常头像路径: 'Boss\\AncestralTwinSpiritGuards\\Icon\\BTNAzureShadeGuard.blp',
      变异头像路径: 'Boss\\AncestralTwinSpiritGuards\\Icon\\BTNAzureShadeMutant.blp',
      广播持续时间Ms: 4000,
      配音裁断距离: 4000,
      配音生成配置: {
        显示台词字段: '台词',
        配音台词字段: '配音台词',
        声线名称: '已确认男性声线',
        声线ID: 'LgVKhF8NfPN1eYSzWQpW',
        模型ID: 'eleven_v3',
        语言: 'en',
        整体提示词: 'An ancient male elven spirit-reader preserved as a cold blue guardian projection. Low ethereal male timbre, precise ritual diction, quiet authority, and the distant sorrow of a mind losing names and faces. Normal delivery is controlled and diagnostic; corruption hollows the voice into broken prayers and failing identification protocols. He is not a gentle narrator, not an evil warlock, and not a screaming ghost. Keep combat lines clear and restrained with subtle spectral resonance.',
        说明: '苍影灵卫使用低沉、偏冷、空灵的精灵男声，与赤誓灵卫厚重直接的男声形成清晰差异。正常形态强调灵印读取、校准和冷静判断；无面祷影逐步失去名字与身份，台词转为空洞祷文和错误判定。净化后只留下脆弱的清醒。',
      },
      台词: {
        开场: ['灵印……无法确认。侵蚀正在接近。不，是你们……正在接近。'],
        双灵同誓: ['赤誓，你的武魂正在失衡。我会稳住它。'],
        灵印折步: ['灵印留于此处。外来者，不得靠近。'],
        月纹缚魂: ['月纹已落。离开，或留下你的灵魂。'],
        首次变异: ['我的名字……为何读不出来？不，不要让它消失……'],
        失名祷潮: ['没有名字的灵魂……都应被潮声带走。'],
        记忆剥落: ['颜色、面容、名字……都从这里抹去。'],
        封门校验: ['校验失败。灵魂潮，执行驱逐。'],
        P3双蚀共鸣: ['身份已失。只剩封门。'],
        双钥净化校准: ['灵印偏移……重新校准。'],
        封门误判: ['所有灵印……均判定为入侵。'],
        同息回灌: ['回到守位。我的灵识会维持你。'],
        灵魂崩解: ['祷文……到这里，就结束了吗……'],
        净化收束: ['我们……守了多久？'],
      },
      配音台词: {
        开场: ['[controlled, alert] Spirit mark... unrecognized. Corruption is approaching. [disturbed realization] No... you are approaching.'],
        双灵同誓: ['[controlled concern] Red Oath, your battle-spirit is failing. I will hold it steady.'],
        灵印折步: ['[cold command] The spirit mark remains here. Outsiders... keep away.'],
        月纹缚魂: ['[cold warning] The moon sigil has fallen. Leave now... [firm threat] or leave your soul behind.'],
        首次变异: ['[confused, breaking] My name... why can I no longer read it? [fear breaking through] No... do not let it disappear!'],
        失名祷潮: ['[ritual warning] Souls without names... [rising spectral command] let the spirit tide carry you away!'],
        记忆剥落: ['[cold, fading] Color... face... name... [grave warning] all will be erased from this place.'],
        封门校验: ['[ritual command] Verification failed. [forceful] Spirit tide... expel the intruders!'],
        P3双蚀共鸣: ['[hollow resolve] Identity lost. [unyielding] Only the gate remains.'],
        双钥净化校准: ['[strained focus] Spirit mark displaced... [ritual command] recalibrating.'],
        封门误判: ['[alarmed, breaking] Every spirit mark... [cold protocol] classified as intrusion.'],
        同息回灌: ['[urgent prayer] Return to the watch. [strained resolve] My spirit will sustain you.'],
        灵魂崩解: ['[fading uncertainty] Does the prayer... end here at last?'],
        净化收束: ['[awaking, fragile] How long... have we been standing guard?'],
      },
      配音资源: {
        开场: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_opening_mark_unrecognized_01_v3.mp3'],
        双灵同誓: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_twin_oath_hold_spirit_01_v3.mp3'],
        灵印折步: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_spirit_step_mark_remains_01_v3.mp3'],
        月纹缚魂: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_moon_sigil_soul_warning_01_v3.mp3'],
        首次变异: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_first_mutation_name_fading_01_v3.mp3'],
        失名祷潮: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_nameless_tide_command_01_v3.mp3'],
        记忆剥落: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_memory_peel_erasure_01_v3.mp3'],
        封门校验: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_gate_verification_expulsion_01_v3.mp3'],
        P3双蚀共鸣: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_phase3_identity_lost_01_v3.mp3'],
        双钥净化校准: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_dual_key_recalibrate_01_v3.mp3'],
        封门误判: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_gate_misjudgment_intrusion_01_v3.mp3'],
        同息回灌: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_shared_breath_sustain_01_v3.mp3'],
        灵魂崩解: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_soul_collapse_prayer_ends_01_v3.mp3'],
        净化收束: ['Sound\\Boss\\AncestralAzureShadeGuard\\Voice\\azure_shade_purified_how_long_01_v3.mp3'],
      },
    },
  },
  阶段阈值: {
    首次变异生命比例: 0.65,
    混合阶段第二守卫最低生命比例: 0.55,
    灵魂崩解生命比例: 0.05,
    默认同步崩解窗口秒: 14,
    完成净化后同步崩解窗口秒: 18,
  },
  正式场地: {
    中心X: 0,
    中心Y: 0,
    可用半宽: 0,
    可用半高: 0,
    净化节点: [] as Array<{ X: number; Y: number }>,
  },
  当前状态: {
    设计已确认: true,
    目录结构已建立: true,
    单位数据已填写: true,
    正式模型已填写: true,
    正式头像已填写: true,
    表现资源已填写: false,
    技能已实现: false,
    战斗已注册: false,
  },
} as const;

export type 赤誓灵卫台词类型 = keyof typeof 祖地双灵卫单位技能配置.单位.赤誓灵卫.台词;
export type 苍影灵卫台词类型 = keyof typeof 祖地双灵卫单位技能配置.单位.苍影灵卫.台词;
