/** @noSelfInFile */

export const 亚伦柯斯单位技能配置 = {
  BossKey: 'SleepingHeroAronkos',
  单位ID: 'U006',
  单位名称: '沉睡英魂·亚伦柯斯',
  基础对象ID: 'Udea',
  模型路径: 'Boss\\SleepingHeroAronkos\\SleepingHeroAronkos.mdx',
  技能壳: {
    亡冥英斩: 'AT00',
    英灵陨星: 'AN00',
  },
  旧技能ID: {
    亡冥英斩: 'A0F4',
    英灵陨星: 'A0F5',
  },
  主动技能提示: [
    { 技能ID: 'AT00', 提示: '亡冥英斩', 扩展提示: '锁定目标方向突进，以亡灵剑气贯穿路径上的敌人。' },
    { 技能ID: 'AN00', 提示: '英灵陨星', 扩展提示: '在周围连续唤下多轮英灵陨星，落点预警后爆发。' },
  ] as Array<{ 技能ID: string; 提示: string; 扩展提示: string }>,
  广播持续时间Ms: 4200,
  配音裁断距离: 4000,
  配音生成配置: {
    显示台词字段: '台词',
    配音台词字段: '配音台词',
    声线名称: '已确认男性声线',
    声线ID: 'V33LkP9pVLdcjeB2y5Na',
    模型ID: 'eleven_v3',
    语言: 'en',
    整体提示词: 'An ancient human oath-knight and battle-worn commander whose soul has guarded a sealed military grave for centuries. Deep disciplined authority, solemn martial honor, restrained undead resonance, and visible fatigue beneath every command. He warns and drives intruders away because duty has outlived memory, never from cruelty or delight. As memories return, hostility becomes grave respect and determined completion of the final oath. Clear dark-fantasy combat diction; not a vampire, not a theatrical villain, not a mindless undead growl.',
    说明: '亚伦柯斯是主动背负污名并留下守墓的誓约骑士，不是嗜杀亡灵。P1 只执行驱逐命令；P2 因墓碑残响而动摇并恢复姓名；P3 已相信玩家，却必须战败才能解除最后誓约。战败应保留军人尊严与职责交接感。',
  },
  台词: {
    开场: ['停下。生者不得踏过誓约之墓。'],
    亡冥英斩: ['这条剑路，生者不得通过。'],
    英灵陨星: ['英灵列阵，为闯入者送葬。'],
    亡者凝视: ['直视守墓者，便要承受亡者的目光。'],
    转阶段2旧誓回响: ['你们惊醒的，不只是墓碑。旧誓仍会回应守墓者。'],
    旧誓墓碑: ['不得惊扰他们的安眠。离开墓碑！'],
    墓碑安魂: ['这段誓言……为何还记得我的声音？'],
    记忆恢复: ['西利乌斯将军……我想起来了。这里不是叛军墓地，是我们亲手选择的最后阵地。'],
    转阶段3最后誓约: ['我相信你们。但相信不能替代誓约。不要因怜悯收起武器。'],
    亡冥英斩归魂: ['剑路会记住每一个脚步。归魂！'],
    英灵陨星送葬: ['诸位英灵，为最后一战送行。'],
    不灭军魂: ['守墓者尚未倒下。最后一道门，仍由我守。'],
    最终强化10: ['只剩最后一息……也要完成最后一道命令。'],
    战败: ['很好……最后一道门，终于等到了能够接过它的人。'],
  },
  配音台词: {
    开场: ['[grave command] Halt! No living soul may cross the Tomb of Oaths.'],
    亡冥英斩: ['[grave warning] No living soul will cross this path of steel.'],
    英灵陨星: ['[commanding] Spirits of the fallen, form ranks. Give the intruders their burial.'],
    亡者凝视: ['[ominous warning] Look upon the gravekeeper... and bear the gaze of the dead.'],
    转阶段2旧誓回响: ['[low warning] You have awakened more than stone. [rising command] The old oath still answers its keeper.'],
    旧誓墓碑: ['[protective fury] Do not disturb their rest. Step away from the graves!'],
    墓碑安魂: ['[unsteady recognition] That oath... why does it still remember my voice?'],
    记忆恢复: ['[shaken memory] General Silius... I remember. [solemn realization] This was never a grave for traitors. It was the final stand we chose.'],
    转阶段3最后誓约: ['[grave respect] I believe you. But belief cannot replace an oath. [unyielding] Do not lower your weapons out of pity.'],
    亡冥英斩归魂: ['[fierce warning] The blade-path remembers every step. [commanding] Return, fallen steel!'],
    英灵陨星送葬: ['[solemn command] Honored dead... bear witness to our final battle.'],
    不灭军魂: ['[unyielding] The gravekeeper has not fallen. The final gate remains mine to hold.'],
    最终强化10: ['[dying strain] One breath remains... [fierce resolve] enough to finish the final command.'],
    战败: ['[spent, dignified] Good... At last, the final gate has found those who can take up its burden.'],
  },
  配音资源: {
    开场: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_opening_tomb_of_oaths_01_v3.mp3'],
    亡冥英斩: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_soul_slash_path_of_steel_01_v3.mp3'],
    英灵陨星: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_heroic_meteor_burial_01_v3.mp3'],
    亡者凝视: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_gaze_of_the_dead_01_v3.mp3'],
    转阶段2旧誓回响: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_phase2_old_oath_answers_01_v3.mp3'],
    旧誓墓碑: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_oath_tombstones_rest_01_v3.mp3'],
    墓碑安魂: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_tombstone_appeasement_voice_01_v3.mp3'],
    记忆恢复: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_memory_general_silius_01_v3.mp3'],
    转阶段3最后誓约: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_phase3_final_oath_01_v3.mp3'],
    亡冥英斩归魂: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_soul_slash_returning_steel_01_v3.mp3'],
    英灵陨星送葬: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_meteor_final_battle_01_v3.mp3'],
    不灭军魂: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_undying_soul_final_gate_01_v3.mp3'],
    最终强化10: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_final_ten_percent_command_01_v3.mp3'],
    战败: ['Sound\\Boss\\SleepingHeroAronkos\\Voice\\aronkos_defeat_gate_burden_01_v3.mp3'],
  },
  正式预置: {
    X: 8322.9,
    Y: -14452.7,
    朝向: 270,
  },
  正式场地: {
    中心X: 8400,
    中心Y: -14973,
    左边界: 6848,
    右边界: 9952,
    下边界: -16256,
    上边界: -13690,
  },
  通用测试场中心: {
    X: -540.6,
    Y: -2495.2,
  },
  当前状态: {
    结构已建立: true,
    技能已迁移: false,
    技能已注册: false,
  },
} as const;

export type 亚伦柯斯台词类型 = keyof typeof 亚伦柯斯单位技能配置.台词;
