/** @noSelfInFile */

// 旧 JASS 原型数值仅供后续 TS 重做参考，不代表最终设计。
export const 亚伦柯斯旧原型配置 = {
  亡冥英斩: {
    旧技能ID: 'A0F4',
    通用技能壳ID: 'AT00',
    推进距离: 800,
    碰撞半径: 200,
    旧固定伤害: 3500,
    每个目标最多命中次数: 1,
    突进斩击轨迹模型: 'war3mapImported\\[AKE]war3AKE.com - 6066773539508500345184343.mdl',
  },
  英灵陨星: {
    旧技能ID: 'A0F5',
    通用技能壳ID: 'AN00',
    生成范围: 900,
    每轮陨星数量: 12,
    旧轮数: 5,
    每轮间隔秒: 1,
    落点伤害半径: 300,
    旧固定伤害: 2000,
    旧最大生命伤害比例: 0.1,
    预警模型: 'war3mapImported\\CallTheSky.mdl',
    爆发模型: 'war3mapImported\\RoarBuff.mdl',
  },
} as const;

/** 正式设计已确认并接入运行时的阶段与表现参数。 */
export const 亚伦柯斯正式设计配置 = {
  阶段阈值: {
    P2生命比例: 0.7,
    P3生命比例: 0.35,
    最终强化生命比例: 0.1,
  },
  阶段表现: {
    开战苏醒硬直秒: 1.8,
    开战苏醒动画编号: 8,
    P2转换硬直秒: 1.5,
    P2转换动画编号: 8,
    P3转换硬直秒: 1.8,
    P3转换动画编号: 8,
  },
  亡者凝视: {
    冷却秒: 12,
    半径: 650,
    扇形角度: 80,
    前摇秒: 0.9,
    冲击持续秒: 0.5,
    动画编号: 8,
    伤害攻击力比例: 1.1,
    伤害目标最大生命比例: 0.03,
    硬直秒: 0.45,
  },
  亡冥英斩: {
    冷却秒: 9,
    前摇秒: 0.8,
    推进距离: 800,
    路径宽度: 220,
    命中半径: 170,
    推进秒: 0.65,
    前摇动画编号: 8,
    动画编号: 5,
    伤害攻击力比例: 1.35,
    伤害目标最大生命比例: 0.035,
    P3归魂延迟秒: 1.2,
    P3归魂推进秒: 0.45,
    P3剑痕模型基准长度: 800,
    P3剑痕模型基准宽度: 220,
    P3剑痕朝向修正角度: 270,
    P3归魂移动特效缩放: 1,
    P3归魂动画编号: 6,
    P3归魂伤害攻击力比例: 0.9,
    P3归魂伤害目标最大生命比例: 0.02,
  },
  英灵陨星: {
    冷却秒: 14,
    P1批次数量: 2,
    P2批次数量: 3,
    P3批次数量: 2,
    P1落点数量: 6,
    P2落点数量: 7,
    P3落点数量: 5,
    批次间隔秒: 1.5,
    生成半径: 900,
    P2墓碑加权比例: 0.4,
    P2墓碑安全间隔: 80,
    P2墓碑加权外环宽度: 180,
    预警秒: 1,
    施法硬直秒: 1,
    常规伤害半径: 270,
    P3伤害半径: 330,
    动画编号: 8,
    伤害攻击力比例: 1.05,
    伤害目标最大生命比例: 0.035,
    P3伤害攻击力比例: 1.35,
    P3伤害目标最大生命比例: 0.05,
  },
  旧誓墓碑: {
    启动硬直秒: 1,
    启动动画编号: 8,
    数量: 3,
    单人安魂持续秒: 1.2,
    多人安魂持续秒: 3,
    安魂范围: 260,
    检查间隔秒: 0.2,
    离开每次回退秒: 0.1,
    场地中心偏移半径: 760,
    未安魂减伤每层: 0.18,
    P2最低生命比例: 0.35,
    残影斩击间隔秒: 5.2,
    残影斩击预警秒: 0.8,
    残影斩击飞行秒: 0.5,
    残影斩击长度: 650,
    残影斩击宽度: 150,
    残影斩击伤害攻击力比例: 0.75,
    残影斩击伤害目标最大生命比例: 0.015,
  },
  不灭军魂: {
    启动硬直秒: 1,
    启动动画编号: 8,
    最终强化硬直秒: 1.2,
    最终强化动画编号: 3,
    P3技能间隔缩短比例: 0.12,
    最终强化攻击力比例: 0.2,
    最终强化攻击速度提高: 0.15,
    最终强化控制免疫秒: 2,
    最终强化施法无敌秒: 1.2,
    最终强化特效缩放: 1.5,
    最终强化叠加特效缩放: 2.2,
    最终强化特效次数: 3,
    最终强化特效间隔秒: 0.2,
    最终强化特效持续秒: 1.8,
  },
  音效默认裁断距离: 3000,
  音效: {
    亡冥英斩突进命中: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_soul_cleave_dash_hit.mp3',
    亡冥英斩蓄势: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_soul_cleave_charge.mp3',
    归魂剑痕: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_returning_soul_slash.mp3',
    英灵陨星坠落: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_fallen_spirit_descent.mp3',
    英灵陨星命中: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_fallen_spirit_impact.mp3',
    亡者凝视: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_grave_gaze_release.mp3',
    墓碑安魂: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_tombstone_rest_complete.mp3',
    不灭军魂: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_undying_oath_awaken.mp3',
    战败归静: 'Sound\\Boss\\Aronkos\\SFX\\aronkos_duty_ends_defeat.mp3',
  },
  表现资源: {
    开战苏醒特效路径: 'Common\\Effect\\Form\\Spread\\AronkosAwakeningSoulWave.mdx',
    常驻英魂特效路径: 'Common\\Effect\\Form\\Aura\\AronkosGraveSoulField.mdx',
    亡冥英斩蓄势特效路径: 'Common\\Effect\\Form\\MagicCircle\\AronkosSoulSwordSigil.mdx',
    亡冥英斩轨迹特效路径: 'Common\\Effect\\Form\\Line\\AronkosSoulSlashTrail.mdx',
    亡冥英斩附加轨迹特效路径: 'Common\\Effect\\Form\\Charge\\DashSfx.mdx',
    亡冥英斩命中特效路径: 'Common\\Effect\\Form\\Line\\AronkosSoulSlashImpact.mdx',
    亡冥英斩附加命中特效路径: 'Common\\Effect\\Form\\Explosion\\WhiteSlashImpact.mdx',
    归魂剑痕特效路径: 'Common\\Effect\\Form\\Line\\AronkosSoulSlashVolley.mdx',
    英灵陨星预警特效路径: 'Common\\Effect\\Form\\MagicCircle\\AronkosMeteorGraveRune.mdx',
    英灵陨星正式特效路径: 'Common\\Effect\\Form\\RiseFall\\ElectricBlizzTarget2.mdx',
    英灵陨星落地特效路径: 'Common\\Effect\\Form\\RiseFall\\AronkosMeteorImpactPillar.mdx',
    英灵陨星落地特效缩放: 0.02,
    英灵陨星余波特效路径: 'Common\\Effect\\Form\\Explosion\\AronkosMeteorAftershock.mdx',
    亡者凝视特效路径: 'Common\\Effect\\Form\\Spread\\AronkosGraveGazeShockwave.mdx',
    誓约墓碑模型路径: 'Common\\Effect\\Form\\Marker\\PeasantGrave1.mdx',
    墓碑安魂范围特效路径: 'Common\\Effect\\Form\\Aura\\AronkosGraveSoulField.mdx',
    墓碑安魂完成特效路径: 'Common\\Effect\\Form\\RiseFall\\AronkosSoulReleasePillar.mdx',
    墓碑残影模型路径: 'Common\\Effect\\Projectile\\AronkosTombstoneEchoSlash.mdx',
    不灭军魂特效路径: 'Common\\Effect\\Form\\Spread\\AronkosAwakeningSoulWave.mdx',
    最终强化叠加特效路径: 'Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl',
    战败归静特效路径: 'Common\\Effect\\Form\\RiseFall\\AronkosDefeatDissolve.mdx',
  },
} as const;
