/** @noSelfInFile */

export const 树魔首领模型动画配置 = {
  模型路径: "Boss\\TreeLord\\TreeLord.mdx",
  序列表: [
    { 编号: 0, 名称: "Spell Slam", 原始时长秒: 1, 循环: false, 语义: "双臂和武器向外展开的重施法" },
    { 编号: 1, 名称: "Portrait Talk", 原始时长秒: 2.667, 循环: true, 语义: "聊天动作" },
    { 编号: 2, 名称: "Stand Ready", 原始时长秒: 1.334, 循环: true, 语义: "战斗待机" },
    { 编号: 3, 名称: "Spell", 原始时长秒: 1, 循环: false, 语义: "双手摆出施法姿势" },
    { 编号: 4, 名称: "Attack", 原始时长秒: 1.034, 循环: false, 语义: "右手向前劈砍" },
    { 编号: 5, 名称: "Attack 2", 原始时长秒: 1, 循环: false, 语义: "右手横砍" },
    { 编号: 6, 名称: "Stand", 原始时长秒: 1.333, 循环: true, 语义: "待机" },
    { 编号: 7, 名称: "Stand 2", 原始时长秒: 4, 循环: true, 语义: "待机变化 2" },
    { 编号: 8, 名称: "Stand 3", 原始时长秒: 4, 循环: true, 语义: "待机变化 3" },
    { 编号: 9, 名称: "Stand Channel", 原始时长秒: 1, 循环: true, 语义: "维持 3 号之后的施法姿势" },
    { 编号: 10, 名称: "Walk", 原始时长秒: 0.8, 循环: true, 语义: "行走" },
    { 编号: 11, 名称: "Attack Slam", 原始时长秒: 1, 循环: false, 语义: "转圈劈砍" },
    { 编号: 12, 名称: "Death", 原始时长秒: 2.267, 循环: false, 语义: "死亡" },
    { 编号: 13, 名称: "Portrait", 原始时长秒: 2.667, 循环: true, 语义: "踮脚维持姿势" },
  ],
  默认待机编号: 6,
} as const;

export const 树魔首领数值与表现配置 = {
  随从特性: {
    初始召唤延迟秒: 0,
    补员间隔秒: 30,
    编制: {
      猎头者: { 数量: 2, 召唤距离: 360, 相对Boss朝向角度: 0, 槽位间隔角度: 80 },
      巫医: { 数量: 1, 召唤距离: 560, 相对Boss朝向角度: 180, 槽位间隔角度: 0 },
      投掷者: { 数量: 1, 召唤距离: 720, 相对Boss朝向角度: 140, 槽位间隔角度: 0 },
    },
    血条优先级: {
      猎头者: 100,
      巫医: 200,
      投掷者: 300,
    },
    召唤角度抖动: 12,
    出生索敌范围: 2200,
    追随刷新间隔毫秒: 1000,
    巫医治疗检测间隔秒: 2,
    巫医疗波首次延迟秒: 2,
    巫医疗波冷却秒: 12,
    巫医疗波Boss最大生命比例: 0.05,
    巫医优先治疗Boss缺血比例: 0.03,
    巫医疗波最大目标数: 5,
    巫医疗波每跳最大距离: 900,
    巫医疗波每跳衰减系数: 0.8,
    巫医疗波跳跃间隔秒: 0.12,
    巫医疗波施法硬直秒: 1,
    暴怒Buff刷新秒: 1.5,
    兽群Buff刷新秒: 1.5,
    兽群最高层数: 4,
    每个小弟攻击提高: 0.2,
    最高攻击提高: 0.8,
    无小弟攻速提高: 1.0,
    无小弟移速提高: 0.5,
    暴怒持续特效路径: "Common\\Effect\\Element\\Fire\\fireaura.mdx",
    暴怒持续特效刷新毫秒: 1000,
  },
  扩散冲击波: {
    技能槽位: "A0LL",
    前摇秒: 1,
    动画编号: 0,
    动画速度: 1.0,
    动作原始时长秒: 1,
    恢复动画编号: 6,
    吟唱条颜色ID: 2,
    吟唱条标题文本: "扩散冲击波正在外扩！",
    吟唱条提示文本: "远离树魔首领周围区域",
    初始半径: 300,
    每跳扩张半径: 20,
    最大扩张跳数: 15,
    Tick间隔毫秒: 90,
    预警半径: 620,
    Boss攻击力比例: 2.0,
    攻击降低比例: 0.4,
    攻击降低持续秒: 7,
    蓄力特效路径: "Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl",
    蓄力特效缩放: 1.6,
    蓄力特效持续秒: 1.1,
    扩散命中特效路径: "Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl",
    扩散命中特效缩放: 1.0,
    扩散命中特效持续秒: 0.6,
  },
  消耗反击: {
    技能槽位: "A0LM",
    持续秒: 3,
    起手动画编号: 3,
    起手动画原始时长秒: 1,
    维持动画编号: 9,
    维持动画原始时长秒: 1,
    反击动画编号: 4,
    反击动画原始时长秒: 1.034,
    恢复动画编号: 6,
    动画速度: 1.0,
    正面减伤比例: 0.9,
    正面判定角度: 270,
    背后判定角度: 120,
    背后增伤比例: 0.5,
    硬直秒: 2,
    反击Boss攻击力比例: 3.0,
    反击射程: 1000,
    反击宽度: 390,
    反击持续秒: 0.45,
    反击Tick毫秒: 40,
    抽魔伤害比例: 0.2,
    防御特效路径: "Abilities\\Spells\\Human\\Defend\\DefendCaster.mdl",
    防御特效刷新毫秒: 800,
    防御特效持续秒: 0.9,
    反击弹道特效路径: "Abilities\\Spells\\Orc\\Shockwave\\ShockwaveMissile.mdl",
    反击弹道特效持续秒: 1.2,
    抽魔特效路径: "Abilities\\Spells\\NightElf\\ManaBurn\\ManaBurnTarget.mdl",
    抽魔连线代码: "MBUR",
  },
  远古诅咒: {
    技能槽位: "A0LN",
    延迟秒: 3,
    动画编号: 3,
    动画速度: 1.0,
    动作原始时长秒: 1,
    后续动画编号: 9,
    后续动画速度: 1.0,
    后续动画延迟毫秒: 1000,
    恢复动画编号: 6,
    吟唱条颜色ID: 3,
    吟唱条标题文本: "远古诅咒正在锁定目标！",
    吟唱条提示文本: "靠近被点名者分摊伤害",
    分摊半径: 400,
    跟随提示圈刷新毫秒: 300,
    当前生命基础比例: 0.6,
    每名玩家当前生命追加比例: 0.2,
    点名特效路径: "Abilities\\Spells\\NightElf\\shadowstrike\\shadowstrike.mdl",
    点名叠加特效路径: "Common\\Effect\\Form\\Aura\\LightningAura.mdx",
    点名特效持续秒: 3,
    后续爆发延迟秒: 1.8,
    后续爆发半径: 650,
    后续爆发目标最大生命比例: 0.1,
    后续爆发Boss攻击力比例: 3.0,
    后续爆发特效路径: "war3mapImported\\Acid Ex.mdl",
    后续爆发特效持续秒: 1,
  },
  树魔图腾: {
    技能槽位: "AN00",
    施法硬直秒: 0.8,
    动画编号: 0,
    动画速度: 1.0,
    动作原始时长秒: 1,
    恢复动画编号: 6,
    吟唱条颜色ID: 2,
    吟唱条标题文本: "树魔图腾正在立起！",
    吟唱条提示文本: "根据图腾类型处理机制",
    图腾落点提示半径: 220,
    图腾缩放: 2.25,
    图腾飞行高度: 0,
    静止陷阱模型路径: "units\\orc\\StasisTotem\\StasisTotem.mdl",
    静止陷阱生命Boss最大生命比例: 0.3,
    静止陷阱基础持续秒: 7,
    静止陷阱每难度追加秒: 1.5,
    静止陷阱触发半径: 600,
    静止陷阱移动速度: 200,
    静止陷阱远距加速阈值: 1000,
    静止陷阱远距移动速度: 360,
    静止陷阱Tick毫秒: 250,
    静止陷阱范围提示间隔毫秒: 1000,
    静止陷阱眩晕秒: 8,
    生命陷阱模型路径: "war3mapImported\\SentryTotem.mdl",
    生命陷阱生命Boss最大生命比例: 0.3,
    生命陷阱持续秒: 20,
    生命陷阱影响半径: 900,
    生命陷阱Tick秒: 1,
    生命陷阱伤害目标最大生命比例: 0.03,
    生命陷阱治疗降低基础比例: 0.5,
    生命陷阱治疗降低每难度追加比例: 0.05,
    爆炸陷阱模型路径: "war3mapImported\\FireTotem.mdl",
    爆炸陷阱生命Boss最大生命比例: 0.12,
    爆炸陷阱持续秒: 10,
    爆炸陷阱传送基础间隔秒: 3.8,
    爆炸陷阱传送每难度减少秒: 0.3,
    爆炸陷阱传送最近距离: 150,
    爆炸陷阱传送最远距离: 425,
    爆炸陷阱被摧毁爆炸延迟秒: 0.5,
    爆炸陷阱当前生命伤害比例: 0.5,
    爆炸陷阱每难度固定伤害: 1800,
    爆炸陷阱爆炸提示半径: 650,
    爆炸陷阱爆炸特效路径: "Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl",
    爆炸陷阱爆炸特效持续秒: 1,
  },
} as const;

export const 树魔首领音效配置 = {
  默认裁断距离: 2800,
  随从特性: {
    召唤号令列表: [
      "Sound\\Boss\\TrollChief\\SFX\\troll_chief_minion_call_summon_combo_06_64k.mp3",
      "Sound\\Boss\\TrollChief\\SFX\\troll_chief_minion_call_summon_combo_07_64k.mp3",
    ],
    无从暴怒: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_minionless_rage_start_01.mp3",
  },
  怪物拟声: {
    标识: "TrollChiefCreature",
    音效路径列表: [
      "Sound\\Boss\\TrollChief\\SFX\\troll_chief_creature_gaga_laugh_01.mp3",
      "Sound\\Boss\\TrollChief\\SFX\\troll_chief_creature_gaga_laugh_02.mp3",
      "Sound\\Boss\\TrollChief\\SFX\\troll_chief_creature_gaga_laugh_03.mp3",
    ],
    冷却Ms: 8000,
    召唤触发概率百分比: 45,
    关键机制触发概率百分比: 60,
    暴怒触发概率百分比: 100,
  },
  扩散冲击波: {
    生效: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_expanding_shockwave_release_03.mp3",
  },
  消耗反击: {
    正面反击: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_counter_mana_burn_retaliation_08.mp3",
    背后破招: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_counter_backbreak_guard_shatter_02.mp3",
  },
  远古诅咒: {
    点名Boss: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_ancient_curse_mark_share_03.mp3",
    点名分摊圈: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_ancient_curse_mark_share_04.mp3",
    点名分摊圈延迟Ms: 200,
    二段爆发: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_ancient_curse_center_blast_04.mp3",
  },
  树魔图腾: {
    生成: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_totem_rise_spawn_02.mp3",
    陷阱触发: "Sound\\Boss\\TrollChief\\SFX\\troll_chief_totem_trap_trigger_burst_combo_07.mp3",
  },
} as const;
