-- Chapter 1 hidden boss: Shadowbone Motes.

createMeleeBossHeroUnit('N01Y', '影骨·莫特斯', {
  modelFile = 'Boss\\ShadowboneMortes\\ShadowboneMortes.mdx',
  icon = 'Boss\\ShadowboneMortes\\ShadowboneMortes.blp',
  properNames = '影骨·莫特斯',
  tooltipBasic = '影骨·莫特斯',
  tooltipExtended = '影骨·莫特斯',
  description = '影骨·莫特斯',

  level = 40,
  hp = 12880,
  mana = 800,
  initialMana = 800,
  manaRegen = 8.0,
  speed = 382,
  strength = 20,
  agility = 20,
  intelligence = 20,
  strengthPerLevel = 1,
  agilityPerLevel = 1,
  intelligencePerLevel = 1,
  damageBase = 736,
  damageDice = 1,
  damageSides = 1,
  attackCooldown = 1.2,
  attackType = AttackType.Chaos,
  weaponType = WeaponType.Instant,
  defense = 35,
  hpRegen = 128.8,
  scale = 5.0,
  soundSet = 'Bandit',
  classification = 'undead',
  abilities = 'AInv,AN00,AN01,AT06,AN02,AN03',
  upgrades = 'R001,R002',
  acquire = 1200.0,
  sightNight = 1400,
  goldBountyBase = 5000,
  lumberBountyBase = 2,
  pointValue = 340,
})
