--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.NPC_CONFIGS = {
    {
        NPCrequireName = "人类农民",
        requireID = 1000,
        NpcNameID = "收集豺狼皮2",
        unitcode = "hpea",
        requireType = "任务",
        X = -327.9,
        Y = -88.9,
        Facing = 270,
        modelFIle = "units\\human\\Peasant\\Peasant",
        enabled = true
    },
    {
        NPCrequireName = "人类猎人",
        requireID = 1001,
        NpcNameID = "人类猎人",
        unitcode = "hmil",
        requireType = "对话",
        X = -26819.3,
        Y = -8344.6,
        Facing = 180,
        enabled = true
    },
    {
        NPCrequireName = "精灵村信使",
        requireID = 1002,
        NpcNameID = "精灵村信使",
        unitcode = "n01H",
        requireType = "对话",
        X = -27392.3,
        Y = -28285.2,
        Facing = 200,
        modelFIle = "units\\critters\\HighElfPeasant\\HighElfPeasant",
        enabled = true
    },
    {
        NPCrequireName = "精灵村村民",
        requireID = 1003,
        NpcNameID = "精灵",
        unitcode = "nhef",
        requireType = "对话",
        X = -26657.5,
        Y = -28275.3,
        Facing = 165,
        modelFIle = "war3mapImported\\ElfVillagerWomanV2.02.mdl",
        enabled = true
    },
    {
        NPCrequireName = "沙漠神秘刺客",
        requireID = 1004,
        NpcNameID = "沙漠神秘刺客",
        unitcode = "nass",
        requireType = "对话",
        X = -15871.9,
        Y = -20945.1,
        Facing = 270,
        modelFIle = "units\\creeps\\BanditSpearThrower\\BanditSpearThrower",
        initAction = "RemoveItemFromStockBJ:itemId(I0AG|I0AH|I0AI);random1",
        enabled = true
    },
    {
        NPCrequireName = "沙漠战斗商人",
        requireID = 1005,
        NpcNameID = "沙漠战斗商人",
        unitcode = "n02I",
        requireType = "对话",
        X = -6926.7,
        Y = -22781,
        Facing = 62.82,
        modelFIle = "units\\creeps\\Bandit\\Bandit.mdl",
        enabled = true
    },
    {
        NPCrequireName = "精灵村弓箭手",
        requireID = 10001,
        NpcNameID = "猎杀豺狼人",
        unitcode = "n01I",
        requireType = "任务",
        X = -25549.1,
        Y = -26008.7,
        Facing = 120,
        modelFIle = "units\\creeps\\HighElfArcher\\HighElfArcher",
        enabled = true
    },
    {
        NPCrequireName = "精灵村民",
        requireID = 10002,
        NpcNameID = "采集荧光草",
        unitcode = "n01J",
        requireType = "任务",
        X = -23827.3,
        Y = -27726.2,
        Facing = 220,
        modelFIle = "war3mapImported\\ElfVillagerWomanV2.02.mdl",
        enabled = true
    },
    {
        NPCrequireName = "黑暗巫师",
        requireID = 10003,
        NpcNameID = "收集蜘蛛毒液",
        unitcode = "n01N",
        requireType = "任务",
        X = -18313.7,
        Y = -25518.5,
        Facing = 0,
        modelFIle = "units\\creeps\\BanditMage\\BanditMage",
        enabled = true
    },
    {
        NPCrequireName = "亡灵法师-安格斯",
        requireID = 10004,
        NpcNameID = "收集熔岩能量",
        unitcode = "n040",
        requireType = "任务",
        modelFIle = "units\\undead\\Necromancer\\Necromancer.mdl",
        enabled = true
    },
    {
        NPCrequireName = "精灵村民",
        requireID = 10005,
        NpcNameID = "收集豺狼皮",
        unitcode = "nhef",
        requireType = "任务",
        X = -26609,
        Y = -26978,
        Facing = 138,
        modelFIle = "war3mapImported\\ElfVillagerWomanV2.02.mdl",
        enabled = true
    },
    {
        NPCrequireName = "布里强",
        requireID = 10006,
        NpcNameID = "收集20个蝎肉",
        unitcode = "nban",
        requireType = "任务",
        X = -5460.2,
        Y = -24955.4,
        Facing = 90,
        modelFIle = "units\\creeps\\Bandit\\Bandit",
        enabled = true
    },
    {
        NPCrequireName = "树魔",
        requireID = 10007,
        NpcNameID = "收集7个蝎壳",
        unitcode = "nftt",
        requireType = "任务",
        X = -8105.6,
        Y = -21191.5,
        Facing = 270,
        modelFIle = "war3mapImported\\ForestTrollShadowPriest.mdl",
        enabled = true
    },
    {
        NPCrequireName = "精灵猎手",
        requireID = 10008,
        NpcNameID = "收集有毒杂草",
        unitcode = "e08B",
        requireType = "任务",
        X = -23856.2,
        Y = -29293.1,
        Facing = 270,
        modelFIle = "war3mapImported\\Watcher.mdl",
        enabled = true
    },
    {
        NPCrequireName = "精灵村民",
        requireID = 10009,
        NpcNameID = "寻找聚灵花",
        unitcode = "nhef",
        requireType = "任务",
        X = -23161.8,
        Y = -26556.9,
        Facing = 45,
        modelFIle = "war3mapImported\\ElfVillagerWomanV2.02.mdl",
        enabled = true
    },
    {
        NPCrequireName = "熔岩术士",
        requireID = 10010,
        NpcNameID = "送信",
        unitcode = "nsra",
        requireType = "任务",
        X = 6903.8,
        Y = -25005.3,
        Facing = 10,
        modelFIle = "units\\creeps\\OrcWarlock\\OrcWarlock",
        enabled = true
    },
    {
        NPCrequireName = "守望者",
        requireID = 10011,
        NpcNameID = "希望获得品质较好的道具或饰品",
        unitcode = "n036",
        requireType = "任务",
        X = 8864.6,
        Y = -22209.2,
        Facing = 255.96,
        modelFIle = "units\\creeps\\assassin\\assassin",
        enabled = true
    },
    {
        NPCrequireName = "精灵弓箭手",
        requireID = 10012,
        NpcNameID = "有提高视力的道具吗",
        unitcode = "e06Q",
        requireType = "任务",
        X = -27950.6,
        Y = -26851.8,
        Facing = 45,
        modelFIle = "war3mapImported\\maleelfarcher.mdl",
        enabled = true
    },
    {
        NPCrequireName = "冒险者阿利亚",
        requireID = 10013,
        NpcNameID = "消失的笛子",
        unitcode = "n058",
        requireType = "任务",
        X = -27974.4,
        Y = -7209.5,
        Facing = 270,
        modelFIle = "units\\critters\\VillagerMan\\VillagerMan",
        enabled = true
    },
    {
        NPCrequireName = "德鲁伊学者-卢伊",
        requireID = 10014,
        NpcNameID = "暗狱之书",
        unitcode = "n059",
        requireType = "任务",
        X = 29335.3,
        Y = -27943.2,
        Facing = 270,
        modelFIle = "war3mapImported\\Hero Druid.mdl",
        enabled = true
    },
    {
        NPCrequireName = "德鲁伊指引者-阿莫斯",
        requireID = 10016,
        NpcNameID = "净化狂暴之熊",
        unitcode = "n04M",
        requireType = "任务",
        X = -22620.5,
        Y = -14275.9,
        Facing = 235,
        modelFIle = "war3mapImported\\DruidGuide.mdl",
        enabled = true
    },
    {
        NPCrequireName = "德鲁伊看守者-阿尔文",
        requireID = 10017,
        NpcNameID = "给予圣果",
        unitcode = "n04O",
        requireType = "任务",
        modelFIle = "war3mapImported\\Annurion.mdl",
        enabled = true
    },
    {
        NPCrequireName = "知识古树",
        requireID = 10018,
        NpcNameID = "补充生命力",
        unitcode = "e06N",
        requireType = "任务",
        X = -18950.5,
        Y = -14412.4,
        Facing = 270,
        modelFIle = "war3mapImported\\druidtreeform.mdl",
        enabled = true
    },
    {
        NPCrequireName = "精灵族长-斯韦尔",
        requireID = 10019,
        NpcNameID = "|cffff0000失踪的精灵村民（Boss战任务）|r",
        unitcode = "edot",
        requireType = "任务",
        modelFIle = "units\\nightelf\\DruidoftheTalon\\DruidoftheTalon",
        enabled = true
    }
}
____exports.default = ____exports.NPC_CONFIGS
return ____exports
