/** @noSelfInFile */

export const 卡瑟拉数值与表现配置 = {
  阶段阈值: { P2生命比例: 0.7, P3生命比例: 0.5 },
  深海涡流: {
    技能槽位: "AN00",
    冷却秒: 30,
    爆发延迟秒: 3,
    最大半径: 720,
    拉力速度: 520,
    抵抗夹角: 55,
    抵抗后拉力倍率: 0.25,
    基础水伤害: 4500,
    最近伤害系数: 1,
    最远伤害系数: 0.3,
    眩晕秒: 1,
    涡流模型路径: "war3mapImported\\WaterTornado.mdx",
    涡流特效持续秒: 3.2,
  },
  触手鞭笞: {
    技能槽位: "AN01",
    冷却秒: 20,
    延迟秒: 2,
    触手数量: 3,
    触手半径: 260,
    触手持续秒: 8,
    触手生命值: 3000,
    触手攻击间隔秒: 0.7,
    触手攻击半径: 220,
    触手Boss攻击力比例: 0.7,
    缠绕减速比例: 0.4,
    缠绕持续秒: 3,
    触手模型路径: "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
    触手缩放: 1.4,
    触手残片掉落概率: 0.45,
  },
  墨汁喷吐: {
    技能槽位: "AT08",
    持续秒: 6,
    残留秒: 20,
    tick秒: 1,
    视野降低: 1200,
    水抗门槛: 0.35,
    达标效果倍率: 0.35,
    扇形半径: 900,
    扇形角度: 70,
    每秒Boss攻击力比例: 0.55,
    墨汁残留模型路径: "Common\\Effect\\Element\\Water\\InkGroundPoolAnimated.mdx",
    墨汁抛射模型路径: "Common\\Effect\\Projectile\\Ink Missile.mdx",
  },
  深渊召唤: {
    触发间隔秒: 45,
    幼鱿数量: 3,
    吞噬等待秒: 30,
    吞噬回血比例: 0.1,
    幼鱿单位类型: "hfoo",
    幼鱿模型路径: "war3mapImported\\Kraken.mdl",
    幼鱿生命值: 3500,
    幼鱿攻击力: 450,
    幼鱿缩放: 2,
  },
  高压水炮: {
    技能槽位: "CT16",
    前摇秒: 1,
    距离: 2400,
    宽度: 200,
    Boss攻击力比例: 4.5,
    路径水花间隔: 180,
    路径水花模型路径: "Objects\\Spawnmodels\\Naga\\NagaDeath\\NagaDeath.mdl",
    水抗门槛: 0.35,
    击退到边缘眩晕秒: 1,
  },
  触手解放: {
    触发生命比例: 0.5,
    触手数量: 4,
    限时秒: 30,
    失败回血比例: 0.25,
    每条破甲比例: 0.05,
    巨型触手生命值: 8000,
    巨型触手模型路径: "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
    巨型触手缩放: 2.6,
    潜入特效路径: "war3mapImported\\WaterTornado.mdx",
  },
  共生电击: {
    间隔秒: 20,
    预警秒: 3,
    雷伤害: 6500,
    麻痹秒: 3,
    安全半径: 300,
    珊瑚数量: 3,
    珊瑚距离: 620,
    珊瑚装饰物ID: "YOtf",
    珊瑚模型路径: "Doodads\\Ruins\\Water\\Coral\\Coral0.mdl",
    珊瑚缩放: 1.15,
    抵消残片数: 3,
    蓄力特效路径: "Common\\Effect\\Element\\Thunder\\ThunderChargeField.mdx",
    全屏命中特效路径: "Common\\Effect\\Element\\Thunder\\ThunderScreenBurst.mdx",
    麻痹命中特效路径: "Common\\Effect\\Element\\Thunder\\ThunderParalyzeHit.mdx",
  },
  触手残片: {
    玩家持有上限: 5,
    水抗加成: 0.07,
    大于数量时恢复已损生命: 2,
    已损生命恢复比例: 0.2,
    Boss吸收间隔秒: 30,
    Boss每片回血比例: 0.02,
    精华每层攻击加成: 0.03,
    精华持续秒: 20,
    地面模型路径: "Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdl",
    地面模型缩放: 0.45,
    吸引间隔秒: 3,
    吸引距离: 200,
    再生触手生命值: 4200,
    再生触手攻击间隔秒: 1,
    再生触手攻击半径: 260,
    再生触手Boss攻击力比例: 0.45,
    再生触手吸血比例: 0.5,
    再生触手持续秒: 18,
  },
} as const;
