/** @noSelfInFile */

export const 藤原妹红单位技能配置 = {
  英雄名: "藤原妹红",
  单位类型ID: "H00R",
  普通Q技能ID: "A0GB",
  普通Q二段技能ID: "A0GA",
  主技能ID: "A0G6",
  引爆技能ID: "A0G8",
  普通R技能ID: "A0G7",
  普通D技能ID: "A0G9",
  符卡开关技能ID: "A0GG",
  符卡关闭技能ID: "A0GF",
  符卡Q技能ID: "A0GC",
  符卡W技能ID: "A0GD",
  符卡R技能ID: "A0GE",
  普通模式技能ID列表: ["A0GA", "A0GB", "A0G6", "A0G8", "A0G7"],
  符卡模式技能ID列表: ["A0GC", "A0GD", "A0GE"],
  动作恢复速度: 1,
  技能实例持续秒: 8,
  普通Q: {
    快捷键序号: 1,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0.5,
    全局音效键: "gg_snd_mh_q2",
    生命消耗最大生命比例: 0.04,
    最大移动距离: 800,
    最大移动秒: 0.5,
    移动间隔毫秒: 10,
    每次移动距离: 16,
    捕捉范围: 250,
    携带单位更新间隔毫秒: 10,
    携带单位抬升阶段秒: 0.25,
    携带单位高度增量: 40,
    命中控制秒: 1,
    命中伤害攻击力倍率: 1,
    命中伤害最大生命倍率: 0.09,
    无命中冷却秒: 4,
    形态恢复秒: 3,
    凤凰特效: {
      模型路径: "units\\human\\phoenix\\phoenix.mdl",
      Z: 110,
      缩放: 3,
      持续秒: 0.6,
    },
    移动特效: {
      模型路径: "Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl",
      Z: 50,
      缩放: 2.3,
      持续秒: 2.2,
      触发间隔秒: 0.1,
    },
    结束特效: {
      模型路径: "Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl",
      Z: 50,
      缩放: 5,
      持续秒: 2.2,
    },
    命中特效: [
      { 模型路径: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeDamageTarget.mdl", 挂点: "origin", 持续秒: 0.1 },
      { 模型路径: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl", 挂点: "origin", 持续秒: 0.1 },
    ],
  },
  普通Q二段: {
    快捷键序号: 1,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0.05,
    全局音效键: "gg_snd_mh_q",
    生命消耗最大生命比例: 0.04,
    搜索范围: 600,
    伤害英雄恶魔攻击力倍率: 2.25,
    伤害普通敌人攻击力倍率: 3.36,
    控制秒: 0.5,
    击退距离: 200,
    击退持续秒: 0.3,
    环形特效半径列表: [250, 500],
    环形特效间隔角度: 40,
    环形特效模型路径: "Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl",
    环形特效缩放: 1,
    环形特效持续秒: 2,
  },
  符卡Q: {
    快捷键序号: 1,
    动作编号: 12,
    动作速度: 1,
    硬直秒: 0.25,
    全局音效键: "gg_snd_mhw",
    启动延迟秒: 0.25,
    移动间隔毫秒: 20,
    最大移动秒: 0.5,
    最大移动距离: 1000,
    每次移动距离: 40,
    捕捉范围: 210,
    首次伤害攻击力倍率: 3,
    灼烧伤害攻击力倍率: 0.5,
    灼烧间隔秒: 1,
    灼烧次数: 3,
    灼烧Buff额外宽限秒: 0.2,
    灼烧命中特效: [
      { 模型路径: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeDamageTarget.mdl", 挂点: "origin", 持续秒: 0.1 },
      { 模型路径: "Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl", 挂点: "origin", 持续秒: 0.1 },
    ],
    凤凰特效: {
      模型路径: "units\\human\\phoenix\\phoenix.mdl",
      Z: 0,
      缩放: 3,
      持续秒: 0.6,
    },
    移动特效: [
      { 模型路径: "Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl", Z: 30, 缩放: 1.2, 持续秒: 1 },
      { 模型路径: "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl", Z: 30, 缩放: 1.2, 持续秒: 1 },
    ],
  },
  符卡W: {
    快捷键序号: 2,
    动作编号: 8,
    动作速度: 1.5,
    硬直秒: 0.8,
    全局音效键: "gg_snd_mh_e2",
    结算音效键: "gg_snd_MK_WW",
    命中延迟秒: 0.5,
    贴近目标距离: 40,
    命中动作编号: 6,
    命中动作速度: 2,
    进度条高度偏移: 233,
    进度条动画速度: 2,
    搜索范围: 233,
    伤害攻击力倍率: 3,
    撞地形追加伤害攻击力倍率: 1.5,
    控制秒: 1.5,
    击退距离: 62.5,
    击退持续秒: 0.4,
    推进表现间隔毫秒: 20,
    推进表现时间增量秒: 0.08,
    命中特效: [
      { 模型路径: "war3mapImported\\a_p.blast2.mdx", 缩放: 0.8, 持续秒: 2.5 },
      { 模型路径: "Abilities\\Spells\\Human\\Thunderclap\\ThunderClapCaster.mdl", 缩放: 0.9, 持续秒: 1.5 },
      { 模型路径: "Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl", 缩放: 1.45, 持续秒: 1.5 },
    ],
    收尾特效: { 模型路径: "war3mapImported\\akiha claw.mdx", Z: 80, 缩放: 1.5, 动画速度: 1, 持续秒: 1 },
    目标预警特效: "Abilities\\Spells\\Other\\Charm\\CharmTarget.mdl",
  },
  符卡R: {
    快捷键序号: 4,
    动作编号: 13,
    动作速度: 1,
    硬直秒: 1,
    全局音效键: "gg_snd_MK_FF",
    结算延迟秒: 0.5,
    收尾延迟秒: 1.2,
    控制秒: 1,
    搜索范围: 400,
    目标最大生命倍率: 0.18,
    目标已损失生命倍率: 0.11,
    外围特效半径: 350,
    外围特效数量: 12,
    外围特效间隔角度: 30,
    进度条特效: { 模型路径: "war3mapImported\\Progressbar.mdl", Z: 233, 动画速度: 2, 持续秒: 0.5 },
    镜头震动幅度: 200,
    镜头震动持续秒: 0.7,
    中心特效: { 模型路径: "war3mapImported\\a_p.blast2.mdl", 缩放: 0.8, 持续秒: 1.2 },
    外围特效: { 模型路径: "war3mapImported\\kamehameexplode.mdl", 缩放: 0.8, 持续秒: 2.5 },
  },
  普通R: {
    快捷键序号: 4,
    动作编号: 2,
    动作速度: 1,
    硬直秒: 0.5,
    全局音效键: "gg_snd_mh_r2",
    移动间隔毫秒: 10,
    最大移动秒: 0.5,
    每次移动距离: 12,
    捕捉范围: 250,
    抓取后控制秒: 0.5,
    目标飞行秒: 0.5,
    携带升空秒: 0.25,
    携带下降秒: 0.25,
    携带高度: 1000,
    自损延迟秒: 1.35,
    自损最大生命比例: 0.2,
    伤害攻击力倍率: 7,
    胸口特效: "Abilities\\Weapons\\PhoenixMissile\\Phoenix_Missile_mini.mdl",
    胸口特效持续秒: 2,
    凤凰特效: { 模型路径: "units\\human\\phoenix\\phoenix.mdl", Z: 110, 缩放: 3, 持续秒: 0.6 },
    凤凰二段特效: { 模型路径: "units\\human\\phoenix\\phoenix.mdl", Z: 110, 缩放: 3, 持续秒: 0.6 },
    命中特效: [
      { 模型路径: "Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl", 缩放: 4.5, 持续秒: 2 },
      { 模型路径: "war3mapImported\\lw10.mdl", 缩放: 2.5, 持续秒: 0.7 },
      { 模型路径: "Abilities\\Spells\\Orc\\WarStomp\\WarStompCaster.mdl", 缩放: 1.45, 持续秒: 1.5 },
      { 模型路径: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl", 缩放: 6, 动画速度: 4, 持续秒: 2 },
    ],
  },
  普通D: {
    快捷键序号: 5,
    动作编号: -1,
    动作速度: 1,
    硬直秒: 0.2,
    全局音效键: "gg_snd_mh_T",
    启动间隔毫秒: 200,
    爆炸延迟秒: 1.6,
    爆炸范围: 600,
    燃烧间隔毫秒: 100,
    燃烧次数: 20,
    伤害攻击力倍率: 0.35,
    控制秒: 0.6,
    击飞距离: 350,
    击飞持续秒: 0.5,
    中心特效: { 模型路径: "war3mapImported\\kamehameexplode.mdl", 缩放: 1.5, 持续秒: 1.5 },
    外围特效数量: 9,
    外围特效半径: 300,
    外围特效间隔角度: 40,
    外围特效: { 模型路径: "war3mapImported\\kamehameexplode.mdl", 缩放: 1, 持续秒: 1.5 },
    持续特效: "Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl",
    持续特效资源: { 模型路径: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeTarget.mdl", 动画索引: 0, 持续秒: 0.5 },
    持续特效半径: 400,
    持续特效角度列表: [90, 135, 180, 225, 270, 315, 360, 90],
  },
  护盾标签: "藤原妹红-火焰护盾",
  护盾值攻击力倍率: 4,
  周期伤害攻击力倍率: 0.4,
  周期伤害间隔毫秒: 500,
  护盾持续秒: 5,
  周期伤害半径: 350,
  引爆范围: 600,
  表现资源: {
    护盾特效路径: "Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl",
    护盾特效挂点: "chest",
    护盾特效键: "藤原妹红-火焰护盾",
    引爆特效路径: "war3mapImported\\lw10.mdl",
    引爆特效持续秒: 1.5,
  },
  被动: {
    快捷键序号: 0,
    技能ID: "A0G6",
    魔法值百分比门槛: 15,
    致命判定护盾抵扣: true,
    被动冷却秒: 240,
    重生无敌持续秒: 1.8,
    重生周期毫秒: 300,
    重生阶段增量: 0.2,
    爆炸阶段: 1,
    火焰阶段: 0.8,
    伤害范围: 800,
    重生生命百分比: 100,
    起手音效键: "gg_snd_mh_r",
    重生爆炸特效: { 模型路径: "war3mapImported\\kamehameexplode.mdl", 缩放: 1.2, 持续秒: 2.5 },
    火焰特效: { 模型路径: "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl", 缩放: 8, 动画速度: 4, 持续秒: 2 },
    环形特效: { 模型路径: "Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl", 缩放: 1, 持续秒: 2 },
    环形半径: 160,
    环形数量: 9,
    环形间隔角度: 40,
    复活伤害攻击力倍率: 1,
    复活伤害最大生命倍率: 0.03,
  },
} as const;
